// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "anychar", "symbols": ["notBanned"]},
    {"name": "Text$ebnf$1", "symbols": []},
    {"name": "Text$ebnf$1", "symbols": ["Text$ebnf$1", "anychar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Text", "symbols": ["Text$ebnf$1"]},
    {"name": "Integer$ebnf$1", "symbols": ["digit"]},
    {"name": "Integer$ebnf$1", "symbols": ["Integer$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Integer", "symbols": ["Integer$ebnf$1"]},
    {"name": "stdEnum", "symbols": ["stdTag"]},
    {"name": "stdEnum", "symbols": ["Integer"]},
    {"name": "Enum", "symbols": ["stdEnum"]},
    {"name": "Enum", "symbols": ["extTag"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["date"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["DatePeriod"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateRange"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateApprox"]},
    {"name": "DateValue$ebnf$1", "symbols": ["DateValue$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DateValue$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DateValue", "symbols": ["DateValue$ebnf$1"]},
    {"name": "DateExact", "symbols": ["day", "D", "month", "D", "year"]},
    {"name": "DatePeriod$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$1$subexpression$1", "symbols": ["DatePeriod$ebnf$1$subexpression$1$string$1", "D", "date"]},
    {"name": "DatePeriod$ebnf$1", "symbols": ["DatePeriod$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": ["DatePeriod$ebnf$1"]},
    {"name": "DatePeriod$string$1", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"O"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$2$subexpression$1$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$2$subexpression$1", "symbols": ["D", "DatePeriod$ebnf$2$subexpression$1$string$1", "D", "date"]},
    {"name": "DatePeriod$ebnf$2", "symbols": ["DatePeriod$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": ["DatePeriod$string$1", "D", "date", "DatePeriod$ebnf$2"]},
    {"name": "date$ebnf$1$subexpression$1", "symbols": ["calendar", "D"]},
    {"name": "date$ebnf$1", "symbols": ["date$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1$subexpression$1", "symbols": ["day", "D"]},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1", "month", "D"]},
    {"name": "date$ebnf$2", "symbols": ["date$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$3$subexpression$1", "symbols": ["D", "epoch"]},
    {"name": "date$ebnf$3", "symbols": ["date$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date", "symbols": ["date$ebnf$1", "date$ebnf$2", "year", "date$ebnf$3"]},
    {"name": "dateRange$string$1", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange$string$2", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$1", "D", "date", "D", "dateRange$string$2", "D", "date"]},
    {"name": "dateRange$string$3", "symbols": [{"literal":"A"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$3", "D", "date"]},
    {"name": "dateRange$string$4", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$4", "D", "date"]},
    {"name": "dateApprox$subexpression$1$string$1", "symbols": [{"literal":"A"}, {"literal":"B"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$1"]},
    {"name": "dateApprox$subexpression$1$string$2", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$2"]},
    {"name": "dateApprox$subexpression$1$string$3", "symbols": [{"literal":"E"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$3"]},
    {"name": "dateApprox", "symbols": ["dateApprox$subexpression$1", "D", "date"]},
    {"name": "dateRestrict$string$1", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"O"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$1"]},
    {"name": "dateRestrict$string$2", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$2"]},
    {"name": "dateRestrict$string$3", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$3"]},
    {"name": "dateRestrict$string$4", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$4"]},
    {"name": "dateRestrict$string$5", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$5"]},
    {"name": "dateRestrict$string$6", "symbols": [{"literal":"A"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$6"]},
    {"name": "dateRestrict$string$7", "symbols": [{"literal":"A"}, {"literal":"B"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$7"]},
    {"name": "dateRestrict$string$8", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$8"]},
    {"name": "dateRestrict$string$9", "symbols": [{"literal":"E"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$9"]},
    {"name": "dateRestrict$string$10", "symbols": [{"literal":"B"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$10"]},
    {"name": "calendar$string$1", "symbols": [{"literal":"G"}, {"literal":"R"}, {"literal":"E"}, {"literal":"G"}, {"literal":"O"}, {"literal":"R"}, {"literal":"I"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$1"]},
    {"name": "calendar$string$2", "symbols": [{"literal":"J"}, {"literal":"U"}, {"literal":"L"}, {"literal":"I"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$2"]},
    {"name": "calendar$string$3", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"E"}, {"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"_"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$3"]},
    {"name": "calendar$string$4", "symbols": [{"literal":"H"}, {"literal":"E"}, {"literal":"B"}, {"literal":"R"}, {"literal":"E"}, {"literal":"W"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$4"]},
    {"name": "calendar", "symbols": ["extTag"]},
    {"name": "day", "symbols": ["Integer"]},
    {"name": "year", "symbols": ["Integer"]},
    {"name": "month", "symbols": ["stdTag"]},
    {"name": "month", "symbols": ["extTag"]},
    {"name": "epoch$string$1", "symbols": [{"literal":"B"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "epoch", "symbols": ["epoch$string$1"]},
    {"name": "epoch", "symbols": ["extTag"]},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [{"literal":"."}, "fraction"]},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$1$subexpression$1", "symbols": [{"literal":":"}, "second", "Time$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "Time$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$2$subexpression$1", "symbols": [{"literal":"Z"}]},
    {"name": "Time$ebnf$2", "symbols": ["Time$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time", "symbols": ["hour", {"literal":":"}, "minute", "Time$ebnf$1", "Time$ebnf$2"]},
    {"name": "hour", "symbols": ["digit"]},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "hour", "symbols": ["hour$subexpression$1", "digit"]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"1"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"2"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"3"}]},
    {"name": "hour", "symbols": [{"literal":"2"}, "hour$subexpression$2"]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "minute", "symbols": ["minute$subexpression$1", "digit"]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "second", "symbols": ["second$subexpression$1", "digit"]},
    {"name": "fraction$ebnf$1", "symbols": ["digit"]},
    {"name": "fraction$ebnf$1", "symbols": ["fraction$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "fraction", "symbols": ["fraction$ebnf$1"]},
    {"name": "Age$ebnf$1$subexpression$1", "symbols": ["ageBound", "D"]},
    {"name": "Age$ebnf$1", "symbols": ["Age$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Age$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Age", "symbols": ["Age$ebnf$1", "ageDuration"]},
    {"name": "ageBound", "symbols": [{"literal":"<"}]},
    {"name": "ageBound", "symbols": [{"literal":">"}]},
    {"name": "years", "symbols": ["Integer", {"literal":"y"}]},
    {"name": "months", "symbols": ["Integer", {"literal":"m"}]},
    {"name": "weeks", "symbols": ["Integer", {"literal":"w"}]},
    {"name": "days", "symbols": ["Integer", {"literal":"d"}]},
    {"name": "ageDuration$ebnf$1$subexpression$1", "symbols": ["D", "months"]},
    {"name": "ageDuration$ebnf$1", "symbols": ["ageDuration$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$2$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$2", "symbols": ["ageDuration$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$3$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$3", "symbols": ["ageDuration$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["years", "ageDuration$ebnf$1", "ageDuration$ebnf$2", "ageDuration$ebnf$3"]},
    {"name": "ageDuration$ebnf$4$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$4", "symbols": ["ageDuration$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$5$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$5", "symbols": ["ageDuration$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["months", "ageDuration$ebnf$4", "ageDuration$ebnf$5"]},
    {"name": "ageDuration$ebnf$6$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$6", "symbols": ["ageDuration$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["weeks", "ageDuration$ebnf$6"]},
    {"name": "ageDuration", "symbols": ["days"]},
    {"name": "list$ebnf$1", "symbols": []},
    {"name": "list$ebnf$1$subexpression$1", "symbols": ["listDelim", "listItem"]},
    {"name": "list$ebnf$1", "symbols": ["list$ebnf$1", "list$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "list", "symbols": ["listItem", "list$ebnf$1"]},
    {"name": "listItem$ebnf$1$subexpression$1", "symbols": ["nocommasp"]},
    {"name": "listItem$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "listItem$ebnf$1$subexpression$1$ebnf$1", "symbols": ["listItem$ebnf$1$subexpression$1$ebnf$1", "nocomma"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listItem$ebnf$1$subexpression$1", "symbols": ["nocommasp", "listItem$ebnf$1$subexpression$1$ebnf$1", "nocommasp"]},
    {"name": "listItem$ebnf$1", "symbols": ["listItem$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "listItem$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "listItem", "symbols": ["listItem$ebnf$1"]},
    {"name": "listDelim$ebnf$1", "symbols": []},
    {"name": "listDelim$ebnf$1", "symbols": ["listDelim$ebnf$1", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listDelim$ebnf$2", "symbols": []},
    {"name": "listDelim$ebnf$2", "symbols": ["listDelim$ebnf$2", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listDelim", "symbols": ["listDelim$ebnf$1", {"literal":","}, "listDelim$ebnf$2"]},
    {"name": "nocomma", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x2C]/]},
    {"name": "nocommasp", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x2C\x1E-\x20]/]},
    {"name": "List_Text", "symbols": ["list"]},
    {"name": "List_Enum$ebnf$1", "symbols": []},
    {"name": "List_Enum$ebnf$1$subexpression$1", "symbols": ["listDelim", "Enum"]},
    {"name": "List_Enum$ebnf$1", "symbols": ["List_Enum$ebnf$1", "List_Enum$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "List_Enum", "symbols": ["Enum", "List_Enum$ebnf$1"]},
    {"name": "PersonalName", "symbols": ["nameStr"]},
    {"name": "PersonalName$ebnf$1", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$2", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$3", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName", "symbols": ["PersonalName$ebnf$1", {"literal":"/"}, "PersonalName$ebnf$2", {"literal":"/"}, "PersonalName$ebnf$3"]},
    {"name": "nameChar", "symbols": [/[^\x00-\x19\x2F]/]},
    {"name": "nameStr$ebnf$1", "symbols": ["nameChar"]},
    {"name": "nameStr$ebnf$1", "symbols": ["nameStr$ebnf$1", "nameChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "nameStr", "symbols": ["nameStr$ebnf$1"]},
    {"name": "LangTag$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "script"]},
    {"name": "LangTag$ebnf$1", "symbols": ["LangTag$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "region"]},
    {"name": "LangTag$ebnf$2", "symbols": ["LangTag$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag$ebnf$3", "symbols": []},
    {"name": "LangTag$ebnf$3$subexpression$1", "symbols": [{"literal":"-"}, "variant"]},
    {"name": "LangTag$ebnf$3", "symbols": ["LangTag$ebnf$3", "LangTag$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "LangTag$ebnf$4", "symbols": []},
    {"name": "LangTag$ebnf$4$subexpression$1", "symbols": [{"literal":"-"}, "extension"]},
    {"name": "LangTag$ebnf$4", "symbols": ["LangTag$ebnf$4", "LangTag$ebnf$4$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "LangTag$ebnf$5$subexpression$1", "symbols": [{"literal":"-"}, "privateuse"]},
    {"name": "LangTag$ebnf$5", "symbols": ["LangTag$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag", "symbols": ["language", "LangTag$ebnf$1", "LangTag$ebnf$2", "LangTag$ebnf$3", "LangTag$ebnf$4", "LangTag$ebnf$5"]},
    {"name": "language$ebnf$1", "symbols": ["alpha"], "postprocess": id},
    {"name": "language$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "extlang"]},
    {"name": "language$ebnf$2", "symbols": ["language$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language", "symbols": ["alpha", "alpha", "language$ebnf$1", "language$ebnf$2"]},
    {"name": "language", "symbols": ["alpha", "alpha", "alpha", "alpha"]},
    {"name": "language$ebnf$3$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$3", "symbols": ["language$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$4$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$4", "symbols": ["language$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$5$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$5", "symbols": ["language$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language", "symbols": ["alpha", "alpha", "alpha", "alpha", "alpha", "language$ebnf$3", "language$ebnf$4", "language$ebnf$5"]},
    {"name": "extlang$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$1", "symbols": ["extlang$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$2", "symbols": ["extlang$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang", "symbols": ["alpha", "alpha", "alpha", "extlang$ebnf$1", "extlang$ebnf$2"]},
    {"name": "script", "symbols": ["alpha", "alpha", "alpha", "alpha"]},
    {"name": "region", "symbols": ["alpha", "alpha"]},
    {"name": "region", "symbols": ["digit", "digit", "digit"]},
    {"name": "variant", "symbols": ["digit", "alphanum", "alphanum", "alphanum"]},
    {"name": "variant$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$1", "symbols": ["variant$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$2", "symbols": ["variant$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$3", "symbols": ["variant$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant", "symbols": ["alphanum", "alphanum", "alphanum", "alphanum", "alphanum", "variant$ebnf$1", "variant$ebnf$2", "variant$ebnf$3"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$1$ebnf$1", "extension$ebnf$1$subexpression$1$ebnf$2", "extension$ebnf$1$subexpression$1$ebnf$3", "extension$ebnf$1$subexpression$1$ebnf$4", "extension$ebnf$1$subexpression$1$ebnf$5", "extension$ebnf$1$subexpression$1$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$2$ebnf$1", "extension$ebnf$1$subexpression$2$ebnf$2", "extension$ebnf$1$subexpression$2$ebnf$3", "extension$ebnf$1$subexpression$2$ebnf$4", "extension$ebnf$1$subexpression$2$ebnf$5", "extension$ebnf$1$subexpression$2$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1", "extension$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extension", "symbols": ["singleton", "extension$ebnf$1"]},
    {"name": "singleton", "symbols": ["digit"]},
    {"name": "singleton", "symbols": [/[\x41-\x57\x59-\x5A\x61-\x77\x79-\x7A]/]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$1$ebnf$1", "privateuse$ebnf$1$subexpression$1$ebnf$2", "privateuse$ebnf$1$subexpression$1$ebnf$3", "privateuse$ebnf$1$subexpression$1$ebnf$4", "privateuse$ebnf$1$subexpression$1$ebnf$5", "privateuse$ebnf$1$subexpression$1$ebnf$6", "privateuse$ebnf$1$subexpression$1$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$2$ebnf$1", "privateuse$ebnf$1$subexpression$2$ebnf$2", "privateuse$ebnf$1$subexpression$2$ebnf$3", "privateuse$ebnf$1$subexpression$2$ebnf$4", "privateuse$ebnf$1$subexpression$2$ebnf$5", "privateuse$ebnf$1$subexpression$2$ebnf$6", "privateuse$ebnf$1$subexpression$2$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1", "privateuse$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "privateuse", "symbols": [{"literal":"x"}, "privateuse$ebnf$1"]},
    {"name": "alpha", "symbols": [/[a-zA-z]/]},
    {"name": "alphanum", "symbols": ["alpha"]},
    {"name": "alphanum", "symbols": ["digit"]},
    {"name": "irregular$string$1", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"-"}, {"literal":"G"}, {"literal":"B"}, {"literal":"-"}, {"literal":"o"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$1"]},
    {"name": "irregular$string$2", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"a"}, {"literal":"m"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$2"]},
    {"name": "irregular$string$3", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"b"}, {"literal":"n"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$3"]},
    {"name": "irregular$string$4", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$4"]},
    {"name": "irregular$string$5", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"e"}, {"literal":"n"}, {"literal":"o"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$5"]},
    {"name": "irregular$string$6", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"h"}, {"literal":"a"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$6"]},
    {"name": "irregular$string$7", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"k"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$7"]},
    {"name": "irregular$string$8", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"l"}, {"literal":"u"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$8"]},
    {"name": "irregular$string$9", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$9"]},
    {"name": "irregular$string$10", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"n"}, {"literal":"a"}, {"literal":"v"}, {"literal":"a"}, {"literal":"j"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$10"]},
    {"name": "irregular$string$11", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"p"}, {"literal":"w"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$11"]},
    {"name": "irregular$string$12", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"a"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$12"]},
    {"name": "irregular$string$13", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$13"]},
    {"name": "irregular$string$14", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"s"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$14"]},
    {"name": "irregular$string$15", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"B"}, {"literal":"E"}, {"literal":"-"}, {"literal":"F"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$15"]},
    {"name": "irregular$string$16", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"B"}, {"literal":"E"}, {"literal":"-"}, {"literal":"N"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$16"]},
    {"name": "irregular$string$17", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"C"}, {"literal":"H"}, {"literal":"-"}, {"literal":"D"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$17"]},
    {"name": "regular$string$1", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"-"}, {"literal":"l"}, {"literal":"o"}, {"literal":"j"}, {"literal":"b"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$1"]},
    {"name": "regular$string$2", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"l"}, {"literal":"-"}, {"literal":"g"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$2"]},
    {"name": "regular$string$3", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"-"}, {"literal":"b"}, {"literal":"o"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$3"]},
    {"name": "regular$string$4", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"-"}, {"literal":"n"}, {"literal":"y"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$4"]},
    {"name": "regular$string$5", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"g"}, {"literal":"u"}, {"literal":"o"}, {"literal":"y"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$5"]},
    {"name": "regular$string$6", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"h"}, {"literal":"a"}, {"literal":"k"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$6"]},
    {"name": "regular$string$7", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$7"]},
    {"name": "regular$string$8", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"-"}, {"literal":"n"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$8"]},
    {"name": "regular$string$9", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"x"}, {"literal":"i"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$9"]},
    {"name": "grandfathered", "symbols": ["irregular"]},
    {"name": "grandfathered", "symbols": ["regular"]},
    {"name": "MediaType$ebnf$1", "symbols": []},
    {"name": "MediaType$ebnf$1$subexpression$1", "symbols": [{"literal":";"}, "mt_parameter"]},
    {"name": "MediaType$ebnf$1", "symbols": ["MediaType$ebnf$1", "MediaType$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "MediaType", "symbols": ["mt_type", {"literal":"/"}, "mt_subtype", "MediaType$ebnf$1"]},
    {"name": "mt_type", "symbols": ["mt_token"]},
    {"name": "mt_subtype", "symbols": ["mt_token"]},
    {"name": "mt_parameter", "symbols": ["mt_attribute", {"literal":"="}, "mt_value"]},
    {"name": "mt_token$ebnf$1$subexpression$1", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1$subexpression$1"]},
    {"name": "mt_token$ebnf$1$subexpression$2", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1", "mt_token$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_token", "symbols": ["mt_token$ebnf$1"]},
    {"name": "mt_attribute", "symbols": ["mt_token"]},
    {"name": "mt_value", "symbols": ["mt_token"]},
    {"name": "mt_value", "symbols": ["mt_qstring"]},
    {"name": "mt_char", "symbols": [/[\x20-\x21]/]},
    {"name": "mt_char", "symbols": [/[\x23-\x27]/]},
    {"name": "mt_char", "symbols": [/[\x2A-\x2B]/]},
    {"name": "mt_char", "symbols": [/[\x2D-\x2E]/]},
    {"name": "mt_char", "symbols": [/[\x30-\x39]/]},
    {"name": "mt_char", "symbols": [/[\x41-\x5A]/]},
    {"name": "mt_char", "symbols": [/[\x5E-\x7E]/]},
    {"name": "mt_qstring$ebnf$1", "symbols": []},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qtext"]},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qpair"]},
    {"name": "mt_qstring$ebnf$1", "symbols": ["mt_qstring$ebnf$1", "mt_qstring$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_qstring", "symbols": [/[\x22]/, "mt_qstring$ebnf$1", /[\x22]/]},
    {"name": "mt_qtext", "symbols": [/[\x09-\x0A]/]},
    {"name": "mt_qtext", "symbols": [/[\x20-\x21]/]},
    {"name": "mt_qtext", "symbols": [/[\x23-\x5B]/]},
    {"name": "mt_qtext", "symbols": [/[\x5D-\x7E]/]},
    {"name": "mt_qpair", "symbols": [{"literal":"\\"}, /[\x09-7E]/]},
    {"name": "Special", "symbols": ["Text"]},
    {"name": "Level", "symbols": [{"literal":"0"}]},
    {"name": "Level$ebnf$1", "symbols": []},
    {"name": "Level$ebnf$1", "symbols": ["Level$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Level", "symbols": ["nonzero", "Level$ebnf$1"]},
    {"name": "D", "symbols": [/[ ]/]},
    {"name": "Xref$ebnf$1", "symbols": ["tagChar"]},
    {"name": "Xref$ebnf$1", "symbols": ["Xref$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Xref", "symbols": ["atsign", "Xref$ebnf$1", "atsign"]},
    {"name": "Tag", "symbols": ["stdTag"]},
    {"name": "Tag", "symbols": ["extTag"]},
    {"name": "LineVal", "symbols": ["pointer"]},
    {"name": "LineVal", "symbols": ["lineStr"]},
    {"name": "EOL$ebnf$1", "symbols": [/[\x0A]/], "postprocess": id},
    {"name": "EOL$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "EOL", "symbols": [/[\x0D]/, "EOL$ebnf$1"]},
    {"name": "EOL", "symbols": [/[\x0A]/]},
    {"name": "stdTag$ebnf$1", "symbols": []},
    {"name": "stdTag$ebnf$1", "symbols": ["stdTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "stdTag", "symbols": ["ucletter", "stdTag$ebnf$1"]},
    {"name": "extTag$ebnf$1", "symbols": ["tagChar"]},
    {"name": "extTag$ebnf$1", "symbols": ["extTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extTag", "symbols": ["underscore", "extTag$ebnf$1"]},
    {"name": "tagChar", "symbols": ["ucletter"]},
    {"name": "tagChar", "symbols": ["digit"]},
    {"name": "tagChar", "symbols": ["underscore"]},
    {"name": "pointer", "symbols": ["voidPrt"]},
    {"name": "pointer", "symbols": ["Xref"]},
    {"name": "voidPrt$string$1", "symbols": [{"literal":"@"}, {"literal":"V"}, {"literal":"O"}, {"literal":"I"}, {"literal":"D"}, {"literal":"@"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "voidPrt", "symbols": ["voidPrt$string$1"]},
    {"name": "nonAt", "symbols": [/[^@\n]/]},
    {"name": "nonEOL", "symbols": [/[^\n]/]},
    {"name": "lineStr$ebnf$1", "symbols": []},
    {"name": "lineStr$ebnf$1", "symbols": ["lineStr$ebnf$1", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["nonAt", "lineStr$ebnf$1"]},
    {"name": "lineStr$ebnf$2", "symbols": []},
    {"name": "lineStr$ebnf$2", "symbols": ["lineStr$ebnf$2", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["atsign", "atsign", "lineStr$ebnf$2"]},
    {"name": "digit", "symbols": [/[0-9]/]},
    {"name": "nonzero", "symbols": [/[1-9]/]},
    {"name": "ucletter", "symbols": [/[A-Z]/]},
    {"name": "underscore", "symbols": [{"literal":"_"}]},
    {"name": "atsign", "symbols": [{"literal":"@"}]},
    {"name": "newLine", "symbols": [{"literal":"\n"}]},
    {"name": "banned", "symbols": [/[\x00-\x08]/]},
    {"name": "banned", "symbols": [/[\x0B-\x0C]/]},
    {"name": "banned", "symbols": [/[\x0E-\x1F]/]},
    {"name": "banned", "symbols": [/[\x7F]/]},
    {"name": "banned", "symbols": [/[\x80-\x9F]/]},
    {"name": "notBanned", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F]/]},
    {"name": "PHRASE$string$1", "symbols": [{"literal":"P"}, {"literal":"H"}, {"literal":"R"}, {"literal":"A"}, {"literal":"S"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PHRASE", "symbols": ["Level", "D", "PHRASE$string$1", "D", "Text"]},
    {"name": "TYPE$string$1", "symbols": [{"literal":"T"}, {"literal":"Y"}, {"literal":"P"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["Level", "D", "TYPE$string$1", "D", "Text"]},
    {"name": "TIME$string$1", "symbols": [{"literal":"T"}, {"literal":"I"}, {"literal":"M"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["Level", "D", "TIME$string$1", "D", "Time"]},
    {"name": "DATE$string$1", "symbols": [{"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["Level", "D", "DATE$string$1", "D", "DateValue"]},
    {"name": "DATE$ebnf$1", "symbols": ["TIME"], "postprocess": id},
    {"name": "DATE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE$ebnf$2", "symbols": ["PHRASE"], "postprocess": id},
    {"name": "DATE$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE", "symbols": ["DATE", "newLine", "DATE$ebnf$1", "DATE$ebnf$2"]},
    {"name": "DATE$ebnf$3", "symbols": ["PHRASE"], "postprocess": id},
    {"name": "DATE$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE$ebnf$4", "symbols": ["TIME"], "postprocess": id},
    {"name": "DATE$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE", "symbols": ["DATE", "newLine", "DATE$ebnf$3", "DATE$ebnf$4"]},
    {"name": "structure", "symbols": ["FAMILY_ATTRIBUTE_STRUCTURE"]},
    {"name": "structure", "symbols": ["FAM_HUSB"]},
    {"name": "structure", "symbols": ["FAM_WIFE"]},
    {"name": "structure", "symbols": ["CHIL"]},
    {"name": "structure", "symbols": ["TEST"]},
    {"name": "FAM_HUSB$string$1", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"S"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAM_HUSB", "symbols": [{"literal":"1"}, "D", "FAM_HUSB$string$1", "D", "Xref"]},
    {"name": "FAM_HUSB", "symbols": ["FAM_HUSB", "newLine", "PHRASE"]},
    {"name": "HUSB$string$1", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"S"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HUSB$string$2", "symbols": [{"literal":"A"}, {"literal":"G"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HUSB", "symbols": ["Level", "D", "HUSB$string$1", "newLine", "Level", "D", "HUSB$string$2", "D", "Age"]},
    {"name": "HUSB", "symbols": ["HUSB", "newLine", "PHRASE"]},
    {"name": "FAM_WIFE$string$1", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"F"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAM_WIFE", "symbols": [{"literal":"1"}, "D", "FAM_WIFE$string$1", "D", "Xref"]},
    {"name": "FAM_WIFE", "symbols": ["FAM_WIFE", "newLine", "PHRASE"]},
    {"name": "WIFE$string$1", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"F"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WIFE$string$2", "symbols": [{"literal":"A"}, {"literal":"G"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WIFE", "symbols": ["Level", "D", "WIFE$string$1", "newLine", "Level", "D", "WIFE$string$2", "D", "Age"]},
    {"name": "WIFE", "symbols": ["WIFE", "newLine", "PHRASE"]},
    {"name": "CHIL$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"I"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHIL", "symbols": [{"literal":"1"}, "D", "CHIL$string$1", "D", "Xref"]},
    {"name": "CHIL", "symbols": ["CHIL", "newLine", "PHRASE"]},
    {"name": "TEST$string$1", "symbols": [{"literal":"T"}, {"literal":"E"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEST", "symbols": ["Level", "D", "TEST$string$1", "D", "DateExact"]},
    {"name": "FAMILY_ATTRIBUTE_STRUCTURE", "symbols": ["NCHI"]},
    {"name": "FAMILY_ATTRIBUTE_STRUCTURE", "symbols": ["RESI"]},
    {"name": "FAMILY_ATTRIBUTE_STRUCTURE", "symbols": ["FACT"]},
    {"name": "NCHI$string$1", "symbols": [{"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NCHI", "symbols": ["Level", "D", "NCHI$string$1", "D", "Integer"]},
    {"name": "NCHI", "symbols": ["NCHI", "newLine", "TYPE"]},
    {"name": "RESI$string$1", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"S"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RESI", "symbols": ["Level", "D", "RESI$string$1", "D", "Text"]},
    {"name": "RESI", "symbols": ["RESI", "newLine", "TYPE"]},
    {"name": "FACT$string$1", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"C"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FACT", "symbols": ["Level", "D", "FACT$string$1", "D", "Text"]},
    {"name": "FACT", "symbols": ["FACT", "newLine", "TYPE"]},
    {"name": "FAMILY_EVENT_DETAIL", "symbols": ["HUSB"]},
    {"name": "FAMILY_EVENT_DETAIL", "symbols": ["WIFE"]},
    {"name": "FAMILY_EVENT_DETAIL", "symbols": ["EVENT_DETAIL"]},
    {"name": "EVENT_DETAIL", "symbols": ["DATE"]}
]
  , ParserStart: "structure"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
