// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

    // required modules
    const postprocessor = require('../Postprocessors.js');
    const {lineTypes} = require('../../Constants.js')
    const moo = require("moo");

    // moo-lexer to pre-compile input
    const lexer = moo.compile({
        D           : /[ ]/,
        digit       : /[0-9]/,
        underscore  : /[_]/,
        Xref        : /\@[A-Z0-9\_]+\@/,
        atsign      : /\@/,
        comma       : /[\,]/,
        EOL         : {match: /(?:\r\n?|\n)/, lineBreaks: true },

        // not Banned, no EOL, no Space, no @, no _, no ,
        notBannedNoEOLNoSpace:  /[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x0A\x0D\x20\x40\x5F\x2C]+/
    });
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "Level", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "Level$ebnf$1", "symbols": []},
    {"name": "Level$ebnf$1", "symbols": ["Level$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Level", "symbols": ["nonzero", "Level$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "D", "symbols": [/[\x20]/], "postprocess": id},
    {"name": "Xref", "symbols": [(lexer.has("Xref") ? {type: "Xref"} : Xref)], "postprocess": id},
    {"name": "Tag", "symbols": ["stdTag"], "postprocess": id},
    {"name": "Tag", "symbols": ["extTag"], "postprocess": id},
    {"name": "LineVal", "symbols": ["pointer"], "postprocess": id},
    {"name": "LineVal", "symbols": ["lineStr"], "postprocess": id},
    {"name": "EOL", "symbols": [(lexer.has("EOL") ? {type: "EOL"} : EOL)], "postprocess": id},
    {"name": "stdTag$ebnf$1", "symbols": []},
    {"name": "stdTag$ebnf$1", "symbols": ["stdTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "stdTag", "symbols": ["ucletter", "stdTag$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "extTag$ebnf$1", "symbols": ["tagChar"]},
    {"name": "extTag$ebnf$1", "symbols": ["extTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extTag", "symbols": ["underscore", "extTag$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "tagChar", "symbols": ["ucletter"], "postprocess": id},
    {"name": "tagChar", "symbols": ["digit"], "postprocess": id},
    {"name": "tagChar", "symbols": ["underscore"], "postprocess": id},
    {"name": "pointer", "symbols": ["voidPrt"], "postprocess": id},
    {"name": "pointer", "symbols": ["Xref"], "postprocess": id},
    {"name": "voidPrt", "symbols": [{"literal":"@VOID@"}], "postprocess": id},
    {"name": "nonAt", "symbols": [/[^\x00-\x08\x0A-\x1F\x40]/], "postprocess": id},
    {"name": "nonEOL", "symbols": [/[^\x00-\x08\x0A-\x1F]/], "postprocess": id},
    {"name": "lineStr$ebnf$1", "symbols": []},
    {"name": "lineStr$ebnf$1", "symbols": ["lineStr$ebnf$1", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["nonAt", "lineStr$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "lineStr$ebnf$2", "symbols": []},
    {"name": "lineStr$ebnf$2", "symbols": ["lineStr$ebnf$2", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["atsign", "atsign", "lineStr$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "digit", "symbols": [(lexer.has("digit") ? {type: "digit"} : digit)], "postprocess": id},
    {"name": "nonzero", "symbols": [/[1-9]/], "postprocess": id},
    {"name": "ucletter", "symbols": [/[A-Z]/], "postprocess": id},
    {"name": "underscore", "symbols": [(lexer.has("underscore") ? {type: "underscore"} : underscore)], "postprocess": id},
    {"name": "atsign", "symbols": [(lexer.has("atsign") ? {type: "atsign"} : atsign)], "postprocess": id},
    {"name": "banned", "symbols": [/[\x00-\x08]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x0B-\x0C]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x0E-\x1F]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x7F]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x80-\x9F]/], "postprocess": id},
    {"name": "notBanned", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F]/], "postprocess": id},
    {"name": "notBannedNoEOL", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x0A\x0D]/], "postprocess": id},
    {"name": "notBannedNoEOLNoAt", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x0A\x0D\x40]/], "postprocess": id},
    {"name": "anychar", "symbols": ["notBannedNoEOL"], "postprocess": id},
    {"name": "Text$ebnf$1", "symbols": []},
    {"name": "Text$ebnf$1", "symbols": ["Text$ebnf$1", "anychar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Text", "symbols": ["notBannedNoEOLNoAt", "Text$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Text$ebnf$2", "symbols": []},
    {"name": "Text$ebnf$2", "symbols": ["Text$ebnf$2", "anychar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Text", "symbols": ["atsign", "atsign", "Text$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Integer$ebnf$1", "symbols": ["digit"]},
    {"name": "Integer$ebnf$1", "symbols": ["Integer$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Integer", "symbols": ["Integer$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "stdEnum", "symbols": ["stdTag"], "postprocess": id},
    {"name": "stdEnum", "symbols": ["Integer"], "postprocess": id},
    {"name": "Enum", "symbols": ["stdEnum"], "postprocess": id},
    {"name": "Enum", "symbols": ["extTag"], "postprocess": id},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["date"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["DatePeriod"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateRange"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateApprox"]},
    {"name": "DateValue$ebnf$1", "symbols": ["DateValue$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DateValue$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DateValue", "symbols": ["DateValue$ebnf$1"], "postprocess": id},
    {"name": "DateExact", "symbols": ["day", "D", "month", "D", "year"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "DatePeriod$ebnf$1$subexpression$1", "symbols": [{"literal":"TO"}, "D", "date"]},
    {"name": "DatePeriod$ebnf$1", "symbols": ["DatePeriod$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": ["DatePeriod$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "DatePeriod$ebnf$2$subexpression$1", "symbols": ["D", {"literal":"TO"}, "D", "date"]},
    {"name": "DatePeriod$ebnf$2", "symbols": ["DatePeriod$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": [{"literal":"FROM"}, "D", "date", "DatePeriod$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "date$ebnf$1$subexpression$1", "symbols": ["calendar", "D"]},
    {"name": "date$ebnf$1", "symbols": ["date$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1$subexpression$1", "symbols": ["day", "D"]},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1", "month", "D"]},
    {"name": "date$ebnf$2", "symbols": ["date$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$3$subexpression$1", "symbols": ["D", "epoch"]},
    {"name": "date$ebnf$3", "symbols": ["date$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date", "symbols": ["date$ebnf$1", "date$ebnf$2", "year", "date$ebnf$3"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateRange", "symbols": [{"literal":"BET"}, "D", "date", "D", {"literal":"AND"}, "D", "date"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateRange", "symbols": [{"literal":"AFT"}, "D", "date"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateRange", "symbols": [{"literal":"BEF"}, "D", "date"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateApprox$subexpression$1", "symbols": [{"literal":"ABT"}]},
    {"name": "dateApprox$subexpression$1", "symbols": [{"literal":"CAL"}]},
    {"name": "dateApprox$subexpression$1", "symbols": [{"literal":"EST"}]},
    {"name": "dateApprox", "symbols": ["dateApprox$subexpression$1", "D", "date"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateRestrict", "symbols": [{"literal":"FROM"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"TO"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"BET"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"AND"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"BEF"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"AFT"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"ABT"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"CAL"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"EST"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"BCE"}], "postprocess": id},
    {"name": "calendar", "symbols": [{"literal":"GREGORIAN"}], "postprocess": id},
    {"name": "calendar", "symbols": [{"literal":"JULIAN"}], "postprocess": id},
    {"name": "calendar", "symbols": [{"literal":"FRENCH_R"}], "postprocess": id},
    {"name": "calendar", "symbols": [{"literal":"HEBREW"}], "postprocess": id},
    {"name": "calendar", "symbols": ["extTag"]},
    {"name": "day", "symbols": ["Integer"], "postprocess": id},
    {"name": "year", "symbols": ["Integer"], "postprocess": id},
    {"name": "month", "symbols": ["stdTag"], "postprocess": id},
    {"name": "month", "symbols": ["extTag"], "postprocess": id},
    {"name": "epoch", "symbols": [{"literal":"BCE"}], "postprocess": id},
    {"name": "epoch", "symbols": ["extTag"], "postprocess": id},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [{"literal":"."}, "fraction"]},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$1$subexpression$1", "symbols": [{"literal":":"}, "second", "Time$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "Time$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$2$subexpression$1", "symbols": [{"literal":"Z"}]},
    {"name": "Time$ebnf$2", "symbols": ["Time$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time", "symbols": ["hour", {"literal":":"}, "minute", "Time$ebnf$1", "Time$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "hour", "symbols": ["digit"], "postprocess": id},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "hour", "symbols": ["hour$subexpression$1", "digit"]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"1"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"2"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"3"}]},
    {"name": "hour", "symbols": [{"literal":"2"}, "hour$subexpression$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "minute", "symbols": ["minute$subexpression$1", "digit"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "second$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "second", "symbols": ["second$subexpression$1", "digit"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "fraction$ebnf$1", "symbols": ["digit"]},
    {"name": "fraction$ebnf$1", "symbols": ["fraction$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "fraction", "symbols": ["fraction$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Age$ebnf$1$subexpression$1", "symbols": ["ageBound", "D"]},
    {"name": "Age$ebnf$1", "symbols": ["Age$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Age$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Age", "symbols": ["Age$ebnf$1", "ageDuration"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageBound", "symbols": [{"literal":"<"}], "postprocess": id},
    {"name": "ageBound", "symbols": [{"literal":">"}], "postprocess": id},
    {"name": "years", "symbols": ["Integer", {"literal":"y"}], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "months", "symbols": ["Integer", {"literal":"m"}], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "weeks", "symbols": ["Integer", {"literal":"w"}], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "days", "symbols": ["Integer", {"literal":"d"}], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$1$subexpression$1", "symbols": ["D", "months"]},
    {"name": "ageDuration$ebnf$1", "symbols": ["ageDuration$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$2$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$2", "symbols": ["ageDuration$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$3$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$3", "symbols": ["ageDuration$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["years", "ageDuration$ebnf$1", "ageDuration$ebnf$2", "ageDuration$ebnf$3"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$4$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$4", "symbols": ["ageDuration$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$5$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$5", "symbols": ["ageDuration$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["months", "ageDuration$ebnf$4", "ageDuration$ebnf$5"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$6$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$6", "symbols": ["ageDuration$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["weeks", "ageDuration$ebnf$6"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageDuration", "symbols": ["days"], "postprocess": id},
    {"name": "list", "symbols": ["Text"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ListText", "symbols": ["list"], "postprocess": id},
    {"name": "ListEnum", "symbols": ["list"], "postprocess": id},
    {"name": "PersonalName", "symbols": ["nameStr"]},
    {"name": "PersonalName$ebnf$1", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$2", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$3", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName", "symbols": ["PersonalName$ebnf$1", {"literal":"/"}, "PersonalName$ebnf$2", {"literal":"/"}, "PersonalName$ebnf$3"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "nameChar", "symbols": [/[^\x00-\x19\x2F]/], "postprocess": id},
    {"name": "nameStr$ebnf$1", "symbols": ["nameChar"]},
    {"name": "nameStr$ebnf$1", "symbols": ["nameStr$ebnf$1", "nameChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "nameStr", "symbols": ["nameStr$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Language$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "script"]},
    {"name": "Language$ebnf$1", "symbols": ["Language$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Language$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Language$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "region"]},
    {"name": "Language$ebnf$2", "symbols": ["Language$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Language$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Language$ebnf$3", "symbols": []},
    {"name": "Language$ebnf$3$subexpression$1", "symbols": [{"literal":"-"}, "variant"]},
    {"name": "Language$ebnf$3", "symbols": ["Language$ebnf$3", "Language$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Language$ebnf$4", "symbols": []},
    {"name": "Language$ebnf$4$subexpression$1", "symbols": [{"literal":"-"}, "extension"]},
    {"name": "Language$ebnf$4", "symbols": ["Language$ebnf$4", "Language$ebnf$4$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Language$ebnf$5$subexpression$1", "symbols": [{"literal":"-"}, "privateuse"]},
    {"name": "Language$ebnf$5", "symbols": ["Language$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "Language$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Language", "symbols": ["lang", "Language$ebnf$1", "Language$ebnf$2", "Language$ebnf$3", "Language$ebnf$4", "Language$ebnf$5"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "lang$ebnf$1", "symbols": ["alpha"], "postprocess": id},
    {"name": "lang$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "extlang"]},
    {"name": "lang$ebnf$2", "symbols": ["lang$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "lang$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang", "symbols": ["alpha", "alpha", "lang$ebnf$1", "lang$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "lang", "symbols": ["alpha", "alpha", "alpha", "alpha"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "lang$ebnf$3$subexpression$1", "symbols": ["alpha"]},
    {"name": "lang$ebnf$3", "symbols": ["lang$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "lang$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang$ebnf$4$subexpression$1", "symbols": ["alpha"]},
    {"name": "lang$ebnf$4", "symbols": ["lang$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "lang$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang$ebnf$5$subexpression$1", "symbols": ["alpha"]},
    {"name": "lang$ebnf$5", "symbols": ["lang$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "lang$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang", "symbols": ["alpha", "alpha", "alpha", "alpha", "alpha", "lang$ebnf$3", "lang$ebnf$4", "lang$ebnf$5"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "extlang$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$1", "symbols": ["extlang$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$2", "symbols": ["extlang$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang", "symbols": ["alpha", "alpha", "alpha", "extlang$ebnf$1", "extlang$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "script", "symbols": ["alpha", "alpha", "alpha", "alpha"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "region", "symbols": ["alpha", "alpha"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "region", "symbols": ["digit", "digit", "digit"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "variant", "symbols": ["digit", "alphanum", "alphanum", "alphanum"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "variant$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$1", "symbols": ["variant$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$2", "symbols": ["variant$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$3", "symbols": ["variant$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant", "symbols": ["alphanum", "alphanum", "alphanum", "alphanum", "alphanum", "variant$ebnf$1", "variant$ebnf$2", "variant$ebnf$3"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$1$ebnf$1", "extension$ebnf$1$subexpression$1$ebnf$2", "extension$ebnf$1$subexpression$1$ebnf$3", "extension$ebnf$1$subexpression$1$ebnf$4", "extension$ebnf$1$subexpression$1$ebnf$5", "extension$ebnf$1$subexpression$1$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$2$ebnf$1", "extension$ebnf$1$subexpression$2$ebnf$2", "extension$ebnf$1$subexpression$2$ebnf$3", "extension$ebnf$1$subexpression$2$ebnf$4", "extension$ebnf$1$subexpression$2$ebnf$5", "extension$ebnf$1$subexpression$2$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1", "extension$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extension", "symbols": ["singleton", "extension$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "singleton", "symbols": ["digit"], "postprocess": id},
    {"name": "singleton", "symbols": [/[\x41-\x57\x59-\x5A\x61-\x77\x79-\x7A]/], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$1$ebnf$1", "privateuse$ebnf$1$subexpression$1$ebnf$2", "privateuse$ebnf$1$subexpression$1$ebnf$3", "privateuse$ebnf$1$subexpression$1$ebnf$4", "privateuse$ebnf$1$subexpression$1$ebnf$5", "privateuse$ebnf$1$subexpression$1$ebnf$6", "privateuse$ebnf$1$subexpression$1$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$2$ebnf$1", "privateuse$ebnf$1$subexpression$2$ebnf$2", "privateuse$ebnf$1$subexpression$2$ebnf$3", "privateuse$ebnf$1$subexpression$2$ebnf$4", "privateuse$ebnf$1$subexpression$2$ebnf$5", "privateuse$ebnf$1$subexpression$2$ebnf$6", "privateuse$ebnf$1$subexpression$2$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1", "privateuse$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "privateuse", "symbols": [{"literal":"x"}, "privateuse$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "alpha", "symbols": [/[a-zA-z]/], "postprocess": id},
    {"name": "alphanum", "symbols": ["alpha"], "postprocess": id},
    {"name": "alphanum", "symbols": ["digit"], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"en-GB-oed"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-ami"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-bnn"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-default"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-enochian"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-hak"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-klingon"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-lux"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-mingo"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-navajo"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-pwn"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-tao"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-tay"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-tsu"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"sgn-BE-FR"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"sgn-BE-NL"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"sgn-CH-DE"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"art-lojban"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"cel-gaulish"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"no-bok"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"no-nyn"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-guoyu"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-hakka"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-min"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-min-nan"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-xiang"}], "postprocess": id},
    {"name": "grandfathered", "symbols": ["irregular"], "postprocess": id},
    {"name": "grandfathered", "symbols": ["regular"], "postprocess": id},
    {"name": "MediaType$ebnf$1", "symbols": []},
    {"name": "MediaType$ebnf$1$subexpression$1", "symbols": [{"literal":";"}, "mt_parameter"]},
    {"name": "MediaType$ebnf$1", "symbols": ["MediaType$ebnf$1", "MediaType$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "MediaType", "symbols": ["mt_type", {"literal":"/"}, "mt_subtype", "MediaType$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "mt_type", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_subtype", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_parameter", "symbols": ["mt_attribute", {"literal":"="}, "mt_value"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "mt_token$ebnf$1$subexpression$1", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1$subexpression$1"]},
    {"name": "mt_token$ebnf$1$subexpression$2", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1", "mt_token$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_token", "symbols": ["mt_token$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "mt_attribute", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_value", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_value", "symbols": ["mt_qstring"], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x20-\x21]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x23-\x27]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x2A-\x2B]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x2D-\x2E]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x30-\x39]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x41-\x5A]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x5E-\x7E]/], "postprocess": id},
    {"name": "mt_qstring$ebnf$1", "symbols": []},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qtext"]},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qpair"]},
    {"name": "mt_qstring$ebnf$1", "symbols": ["mt_qstring$ebnf$1", "mt_qstring$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_qstring", "symbols": [/[\x22]/, "mt_qstring$ebnf$1", /[\x22]/], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "mt_qtext", "symbols": [/[\x09-\x0A]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x20-\x21]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x23-\x5B]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x5D-\x7E]/], "postprocess": id},
    {"name": "mt_qpair", "symbols": [{"literal":"\\"}, /[\x09-7E]/], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Special", "symbols": ["Text"], "postprocess": id},
    {"name": "NullOrY$ebnf$1", "symbols": [{"literal":"Y"}], "postprocess": id},
    {"name": "NullOrY$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "NullOrY", "symbols": ["NullOrY$ebnf$1"], "postprocess": id},
    {"name": "TEXT_CONTINUATION$ebnf$1$subexpression$1", "symbols": ["D", "Text"]},
    {"name": "TEXT_CONTINUATION$ebnf$1", "symbols": ["TEXT_CONTINUATION$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "TEXT_CONTINUATION$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "TEXT_CONTINUATION", "symbols": ["Level", "D", {"literal":"CONT"}, "TEXT_CONTINUATION$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "CONT", type: "NO_XREF", lineValType: "Text"})},
    {"name": "INTEGER_CONTINUATION$ebnf$1$subexpression$1", "symbols": ["D", "Integer"]},
    {"name": "INTEGER_CONTINUATION$ebnf$1", "symbols": ["INTEGER_CONTINUATION$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "INTEGER_CONTINUATION$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "INTEGER_CONTINUATION", "symbols": ["Level", "D", {"literal":"CONT"}, "INTEGER_CONTINUATION$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "CONT", type: "NO_XREF", lineValType: "Integer"})},
    {"name": "g7_ADDR", "symbols": ["ADDR"], "postprocess": id},
    {"name": "g7_ADDR$ebnf$1", "symbols": ["ADDRSubstructs"]},
    {"name": "g7_ADDR$ebnf$1", "symbols": ["g7_ADDR$ebnf$1", "ADDRSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_ADDR", "symbols": ["ADDR", "g7_ADDR$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "ADDR$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "ADDR$ebnf$1", "symbols": ["ADDR$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "ADDR$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ADDR", "symbols": ["Level", "D", {"literal":"ADDR"}, "ADDR$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_ADDR", type: "NO_XREF", lineValType: "Special", checkCardinalityOf: {"g7_ADR1":"0:1", "g7_ADR2":"0:1", "g7_ADR3":"0:1", "g7_CITY":"0:1", "g7_STAE":"0:1", "g7_POST":"0:1", "g7_CTRY":"0:1"}})},
    {"name": "ADDRSubstructs", "symbols": ["g7_ADR1"], "postprocess": id},
    {"name": "ADDRSubstructs", "symbols": ["g7_ADR2"], "postprocess": id},
    {"name": "ADDRSubstructs", "symbols": ["g7_ADR3"], "postprocess": id},
    {"name": "ADDRSubstructs", "symbols": ["g7_CITY"], "postprocess": id},
    {"name": "ADDRSubstructs", "symbols": ["g7_STAE"], "postprocess": id},
    {"name": "ADDRSubstructs", "symbols": ["g7_POST"], "postprocess": id},
    {"name": "ADDRSubstructs", "symbols": ["g7_CTRY"], "postprocess": id},
    {"name": "ADDRSubstructs", "symbols": ["TEXT_CONTINUATION"], "postprocess": id},
    {"name": "g7_ADR1$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_ADR1$ebnf$1", "symbols": ["g7_ADR1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_ADR1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_ADR1", "symbols": ["Level", "D", {"literal":"ADR1"}, "g7_ADR1$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_ADR1", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_ADR1", "symbols": ["g7_ADR1", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_ADR2$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_ADR2$ebnf$1", "symbols": ["g7_ADR2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_ADR2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_ADR2", "symbols": ["Level", "D", {"literal":"ADR2"}, "g7_ADR2$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_ADR2", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_ADR2", "symbols": ["g7_ADR2", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_ADR3$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_ADR3$ebnf$1", "symbols": ["g7_ADR3$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_ADR3$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_ADR3", "symbols": ["Level", "D", {"literal":"ADR3"}, "g7_ADR3$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_ADR3", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_ADR3", "symbols": ["g7_ADR3", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_CITY$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_CITY$ebnf$1", "symbols": ["g7_CITY$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_CITY$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_CITY", "symbols": ["Level", "D", {"literal":"CITY"}, "g7_CITY$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_CITY", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_CITY", "symbols": ["g7_CITY", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_COPR$ebnf$1$subexpression$1", "symbols": ["D", "Text"]},
    {"name": "g7_COPR$ebnf$1", "symbols": ["g7_COPR$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_COPR$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_COPR", "symbols": ["Level", "D", {"literal":"COPR"}, "g7_COPR$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_COPR", type: "NO_XREF", lineValType: "Text"})},
    {"name": "g7_COPR", "symbols": ["g7_COPR", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_CORP", "symbols": ["CORP"], "postprocess": id},
    {"name": "g7_CORP$ebnf$1", "symbols": ["CORPSubstructs"]},
    {"name": "g7_CORP$ebnf$1", "symbols": ["g7_CORP$ebnf$1", "CORPSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_CORP", "symbols": ["CORP", "g7_CORP$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "CORP$ebnf$1$subexpression$1", "symbols": ["D", "Text"]},
    {"name": "CORP$ebnf$1", "symbols": ["CORP$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "CORP$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "CORP", "symbols": ["Level", "D", {"literal":"CORP"}, "CORP$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_CORP", type: "NO_XREF", lineValType: "Text", checkCardinalityOf: {"ADDRESS_STRUCTURE":"0:1"}})},
    {"name": "CORPSubstructs", "symbols": ["ADDRESS_STRUCTURE"], "postprocess": id},
    {"name": "CORPSubstructs", "symbols": ["g7_PHON"], "postprocess": id},
    {"name": "CORPSubstructs", "symbols": ["g7_EMAIL"], "postprocess": id},
    {"name": "CORPSubstructs", "symbols": ["g7_FAX"], "postprocess": id},
    {"name": "CORPSubstructs", "symbols": ["g7_WWW"], "postprocess": id},
    {"name": "CORPSubstructs", "symbols": ["TEXT_CONTINUATION"], "postprocess": id},
    {"name": "g7_CTRY$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_CTRY$ebnf$1", "symbols": ["g7_CTRY$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_CTRY$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_CTRY", "symbols": ["Level", "D", {"literal":"CTRY"}, "g7_CTRY$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_CTRY", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_CTRY", "symbols": ["g7_CTRY", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_HEAD_SOUR_DATA", "symbols": ["HEADSOURDATA"], "postprocess": id},
    {"name": "g7_HEAD_SOUR_DATA$ebnf$1", "symbols": ["HEADSOURDATASubstructs"]},
    {"name": "g7_HEAD_SOUR_DATA$ebnf$1", "symbols": ["g7_HEAD_SOUR_DATA$ebnf$1", "HEADSOURDATASubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_HEAD_SOUR_DATA", "symbols": ["HEADSOURDATA", "g7_HEAD_SOUR_DATA$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "HEADSOURDATA$ebnf$1$subexpression$1", "symbols": ["D", "Text"]},
    {"name": "HEADSOURDATA$ebnf$1", "symbols": ["HEADSOURDATA$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "HEADSOURDATA$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "HEADSOURDATA", "symbols": ["Level", "D", {"literal":"DATA"}, "HEADSOURDATA$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_HEAD_SOUR_DATA", type: "NO_XREF", lineValType: "Text", checkCardinalityOf: {"g7_DATE_exact":"0:1", "g7_COPR":"0:1"}})},
    {"name": "HEADSOURDATASubstructs", "symbols": ["g7_DATE_exact"], "postprocess": id},
    {"name": "HEADSOURDATASubstructs", "symbols": ["g7_COPR"], "postprocess": id},
    {"name": "HEADSOURDATASubstructs", "symbols": ["TEXT_CONTINUATION"], "postprocess": id},
    {"name": "g7_DATE_exact", "symbols": ["DATEexact"], "postprocess": id},
    {"name": "g7_DATE_exact$ebnf$1", "symbols": ["DATEexactSubstructs"]},
    {"name": "g7_DATE_exact$ebnf$1", "symbols": ["g7_DATE_exact$ebnf$1", "DATEexactSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_DATE_exact", "symbols": ["DATEexact", "g7_DATE_exact$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "DATEexact$ebnf$1$subexpression$1", "symbols": ["D", "DateExact"]},
    {"name": "DATEexact$ebnf$1", "symbols": ["DATEexact$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DATEexact$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATEexact", "symbols": ["Level", "D", {"literal":"DATE"}, "DATEexact$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_DATE_exact", type: "NO_XREF", lineValType: "DateExact", checkCardinalityOf: {"g7_TIME":"0:1"}})},
    {"name": "DATEexactSubstructs", "symbols": ["g7_TIME"], "postprocess": id},
    {"name": "DATEexactSubstructs", "symbols": ["TEXT_CONTINUATION"], "postprocess": id},
    {"name": "g7_HEAD_DATE", "symbols": ["HEADDATE"], "postprocess": id},
    {"name": "g7_HEAD_DATE$ebnf$1", "symbols": ["HEADDATESubstructs"]},
    {"name": "g7_HEAD_DATE$ebnf$1", "symbols": ["g7_HEAD_DATE$ebnf$1", "HEADDATESubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_HEAD_DATE", "symbols": ["HEADDATE", "g7_HEAD_DATE$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "HEADDATE$ebnf$1$subexpression$1", "symbols": ["D", "DateExact"]},
    {"name": "HEADDATE$ebnf$1", "symbols": ["HEADDATE$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "HEADDATE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "HEADDATE", "symbols": ["Level", "D", {"literal":"DATE"}, "HEADDATE$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_HEAD_DATE", type: "NO_XREF", lineValType: "DateExact", checkCardinalityOf: {"g7_TIME":"0:1"}})},
    {"name": "HEADDATESubstructs", "symbols": ["g7_TIME"], "postprocess": id},
    {"name": "HEADDATESubstructs", "symbols": ["TEXT_CONTINUATION"], "postprocess": id},
    {"name": "g7_DEST$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_DEST$ebnf$1", "symbols": ["g7_DEST$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_DEST$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_DEST", "symbols": ["Level", "D", {"literal":"DEST"}, "g7_DEST$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_DEST", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_DEST", "symbols": ["g7_DEST", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_EMAIL$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_EMAIL$ebnf$1", "symbols": ["g7_EMAIL$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_EMAIL$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_EMAIL", "symbols": ["Level", "D", {"literal":"EMAIL"}, "g7_EMAIL$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_EMAIL", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_EMAIL", "symbols": ["g7_EMAIL", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_FAX$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_FAX$ebnf$1", "symbols": ["g7_FAX$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_FAX$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_FAX", "symbols": ["Level", "D", {"literal":"FAX"}, "g7_FAX$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_FAX", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_FAX", "symbols": ["g7_FAX", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_HEAD_PLAC_FORM$ebnf$1$subexpression$1", "symbols": ["D", "ListText"]},
    {"name": "g7_HEAD_PLAC_FORM$ebnf$1", "symbols": ["g7_HEAD_PLAC_FORM$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_HEAD_PLAC_FORM$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_HEAD_PLAC_FORM", "symbols": ["Level", "D", {"literal":"FORM"}, "g7_HEAD_PLAC_FORM$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_HEAD_PLAC_FORM", type: "NO_XREF", lineValType: "ListText"})},
    {"name": "g7_HEAD_PLAC_FORM", "symbols": ["g7_HEAD_PLAC_FORM", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_GEDC", "symbols": ["GEDC"], "postprocess": id},
    {"name": "g7_GEDC$ebnf$1", "symbols": ["GEDCSubstructs"]},
    {"name": "g7_GEDC$ebnf$1", "symbols": ["g7_GEDC$ebnf$1", "GEDCSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_GEDC", "symbols": ["GEDC", "g7_GEDC$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "GEDC", "symbols": ["Level", "D", {"literal":"GEDC"}, "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_GEDC", type: "NO_XREF_NO_LINEVAL", checkCardinalityOf: {"g7_GEDC_VERS":"1:1"}})},
    {"name": "GEDC", "symbols": ["g7_GEDC", "g7_GEDC_VERS"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_FAM_HUSB", "symbols": ["FAMHUSB"], "postprocess": id},
    {"name": "g7_FAM_HUSB$ebnf$1", "symbols": ["FAMHUSBSubstructs"]},
    {"name": "g7_FAM_HUSB$ebnf$1", "symbols": ["g7_FAM_HUSB$ebnf$1", "FAMHUSBSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_FAM_HUSB", "symbols": ["FAMHUSB", "g7_FAM_HUSB$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "FAMHUSB$ebnf$1$subexpression$1", "symbols": ["D", "Xref"]},
    {"name": "FAMHUSB$ebnf$1", "symbols": ["FAMHUSB$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "FAMHUSB$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "FAMHUSB", "symbols": ["Level", "D", {"literal":"HUSB"}, "FAMHUSB$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_FAM_HUSB", type: "NO_XREF", lineValType: "Xref", checkCardinalityOf: {"g7_PHRASE":"0:1"}})},
    {"name": "FAMHUSBSubstructs", "symbols": ["g7_PHRASE"], "postprocess": id},
    {"name": "FAMHUSBSubstructs", "symbols": ["TEXT_CONTINUATION"], "postprocess": id},
    {"name": "g7_HEAD_LANG$ebnf$1$subexpression$1", "symbols": ["D", "Language"]},
    {"name": "g7_HEAD_LANG$ebnf$1", "symbols": ["g7_HEAD_LANG$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_HEAD_LANG$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_HEAD_LANG", "symbols": ["Level", "D", {"literal":"LANG"}, "g7_HEAD_LANG$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_HEAD_LANG", type: "NO_XREF", lineValType: "Language"})},
    {"name": "g7_HEAD_LANG", "symbols": ["g7_HEAD_LANG", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_NAME$ebnf$1$subexpression$1", "symbols": ["D", "Text"]},
    {"name": "g7_NAME$ebnf$1", "symbols": ["g7_NAME$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_NAME$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_NAME", "symbols": ["Level", "D", {"literal":"NAME"}, "g7_NAME$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_NAME", type: "NO_XREF", lineValType: "Text"})},
    {"name": "g7_NAME", "symbols": ["g7_NAME", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_PHON$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_PHON$ebnf$1", "symbols": ["g7_PHON$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_PHON$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_PHON", "symbols": ["Level", "D", {"literal":"PHON"}, "g7_PHON$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_PHON", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_PHON", "symbols": ["g7_PHON", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_PHRASE$ebnf$1$subexpression$1", "symbols": ["D", "Text"]},
    {"name": "g7_PHRASE$ebnf$1", "symbols": ["g7_PHRASE$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_PHRASE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_PHRASE", "symbols": ["Level", "D", {"literal":"PHRASE"}, "g7_PHRASE$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_PHRASE", type: "NO_XREF", lineValType: "Text"})},
    {"name": "g7_PHRASE", "symbols": ["g7_PHRASE", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_HEAD_PLAC", "symbols": ["HEADPLAC"], "postprocess": id},
    {"name": "g7_HEAD_PLAC$ebnf$1", "symbols": ["HEADPLACSubstructs"]},
    {"name": "g7_HEAD_PLAC$ebnf$1", "symbols": ["g7_HEAD_PLAC$ebnf$1", "HEADPLACSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_HEAD_PLAC", "symbols": ["HEADPLAC", "g7_HEAD_PLAC$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "HEADPLAC", "symbols": ["Level", "D", {"literal":"PLAC"}, "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_HEAD_PLAC", type: "NO_XREF_NO_LINEVAL", checkCardinalityOf: {"g7_HEAD_PLAC_FORM":"1:1"}})},
    {"name": "HEADPLAC", "symbols": ["g7_HEAD_PLAC", "g7_HEAD_PLAC_FORM"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_POST$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_POST$ebnf$1", "symbols": ["g7_POST$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_POST$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_POST", "symbols": ["Level", "D", {"literal":"POST"}, "g7_POST$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_POST", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_POST", "symbols": ["g7_POST", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_RESN$ebnf$1$subexpression$1", "symbols": ["D", "ListEnum"]},
    {"name": "g7_RESN$ebnf$1", "symbols": ["g7_RESN$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_RESN$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_RESN", "symbols": ["Level", "D", {"literal":"RESN"}, "g7_RESN$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_RESN", type: "NO_XREF", lineValType: "ListEnum", enumType: "g7_enumset_RESN"})},
    {"name": "g7_RESN", "symbols": ["g7_RESN", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_SCHMA", "symbols": ["SCHMA"], "postprocess": id},
    {"name": "g7_SCHMA$ebnf$1", "symbols": ["SCHMASubstructs"]},
    {"name": "g7_SCHMA$ebnf$1", "symbols": ["g7_SCHMA$ebnf$1", "SCHMASubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_SCHMA", "symbols": ["SCHMA", "g7_SCHMA$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "SCHMA", "symbols": ["Level", "D", {"literal":"SCHMA"}, "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_SCHMA", type: "NO_XREF_NO_LINEVAL"})},
    {"name": "SCHMA", "symbols": ["g7_SCHMA", "g7_TAG"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_HEAD_SOUR", "symbols": ["HEADSOUR"], "postprocess": id},
    {"name": "g7_HEAD_SOUR$ebnf$1", "symbols": ["HEADSOURSubstructs"]},
    {"name": "g7_HEAD_SOUR$ebnf$1", "symbols": ["g7_HEAD_SOUR$ebnf$1", "HEADSOURSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_HEAD_SOUR", "symbols": ["HEADSOUR", "g7_HEAD_SOUR$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "HEADSOUR$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "HEADSOUR$ebnf$1", "symbols": ["HEADSOUR$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "HEADSOUR$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "HEADSOUR", "symbols": ["Level", "D", {"literal":"SOUR"}, "HEADSOUR$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_HEAD_SOUR", type: "NO_XREF", lineValType: "Special", checkCardinalityOf: {"g7_VERS":"0:1", "g7_NAME":"0:1", "g7_CORP":"0:1", "g7_HEAD_SOUR_DATA":"0:1"}})},
    {"name": "HEADSOURSubstructs", "symbols": ["g7_VERS"], "postprocess": id},
    {"name": "HEADSOURSubstructs", "symbols": ["g7_NAME"], "postprocess": id},
    {"name": "HEADSOURSubstructs", "symbols": ["g7_CORP"], "postprocess": id},
    {"name": "HEADSOURSubstructs", "symbols": ["g7_HEAD_SOUR_DATA"], "postprocess": id},
    {"name": "HEADSOURSubstructs", "symbols": ["TEXT_CONTINUATION"], "postprocess": id},
    {"name": "g7_STAE$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_STAE$ebnf$1", "symbols": ["g7_STAE$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_STAE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_STAE", "symbols": ["Level", "D", {"literal":"STAE"}, "g7_STAE$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_STAE", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_STAE", "symbols": ["g7_STAE", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_SUBM$ebnf$1$subexpression$1", "symbols": ["D", "Xref"]},
    {"name": "g7_SUBM$ebnf$1", "symbols": ["g7_SUBM$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_SUBM$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_SUBM", "symbols": ["Level", "D", {"literal":"SUBM"}, "g7_SUBM$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_SUBM", type: "NO_XREF", lineValType: "Xref"})},
    {"name": "g7_SUBM", "symbols": ["g7_SUBM", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_TAG$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_TAG$ebnf$1", "symbols": ["g7_TAG$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_TAG$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_TAG", "symbols": ["Level", "D", {"literal":"TAG"}, "g7_TAG$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_TAG", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_TAG", "symbols": ["g7_TAG", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_TIME$ebnf$1$subexpression$1", "symbols": ["D", "Time"]},
    {"name": "g7_TIME$ebnf$1", "symbols": ["g7_TIME$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_TIME$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_TIME", "symbols": ["Level", "D", {"literal":"TIME"}, "g7_TIME$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_TIME", type: "NO_XREF", lineValType: "Time"})},
    {"name": "g7_TIME", "symbols": ["g7_TIME", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_VERS$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_VERS$ebnf$1", "symbols": ["g7_VERS$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_VERS$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_VERS", "symbols": ["Level", "D", {"literal":"VERS"}, "g7_VERS$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_VERS", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_VERS", "symbols": ["g7_VERS", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_GEDC_VERS$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_GEDC_VERS$ebnf$1", "symbols": ["g7_GEDC_VERS$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_GEDC_VERS$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_GEDC_VERS", "symbols": ["Level", "D", {"literal":"VERS"}, "g7_GEDC_VERS$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_GEDC_VERS", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_GEDC_VERS", "symbols": ["g7_GEDC_VERS", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_FAM_WIFE", "symbols": ["FAMWIFE"], "postprocess": id},
    {"name": "g7_FAM_WIFE$ebnf$1", "symbols": ["FAMWIFESubstructs"]},
    {"name": "g7_FAM_WIFE$ebnf$1", "symbols": ["g7_FAM_WIFE$ebnf$1", "FAMWIFESubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_FAM_WIFE", "symbols": ["FAMWIFE", "g7_FAM_WIFE$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "FAMWIFE$ebnf$1$subexpression$1", "symbols": ["D", "Xref"]},
    {"name": "FAMWIFE$ebnf$1", "symbols": ["FAMWIFE$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "FAMWIFE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "FAMWIFE", "symbols": ["Level", "D", {"literal":"WIFE"}, "FAMWIFE$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_FAM_WIFE", type: "NO_XREF", lineValType: "Xref", checkCardinalityOf: {"g7_PHRASE":"0:1"}})},
    {"name": "FAMWIFESubstructs", "symbols": ["g7_PHRASE"], "postprocess": id},
    {"name": "FAMWIFESubstructs", "symbols": ["TEXT_CONTINUATION"], "postprocess": id},
    {"name": "g7_WWW$ebnf$1$subexpression$1", "symbols": ["D", "Special"]},
    {"name": "g7_WWW$ebnf$1", "symbols": ["g7_WWW$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "g7_WWW$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "g7_WWW", "symbols": ["Level", "D", {"literal":"WWW"}, "g7_WWW$ebnf$1", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_WWW", type: "NO_XREF", lineValType: "Special"})},
    {"name": "g7_WWW", "symbols": ["g7_WWW", "TEXT_CONTINUATION"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "ADDRESS_STRUCTURE", "symbols": ["g7_ADDR"], "postprocess": id},
    {"name": "g7_record_FAM", "symbols": ["recordFAM"], "postprocess": id},
    {"name": "g7_record_FAM$ebnf$1", "symbols": ["recordFAMSubstructs"]},
    {"name": "g7_record_FAM$ebnf$1", "symbols": ["g7_record_FAM$ebnf$1", "recordFAMSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_record_FAM", "symbols": ["recordFAM", "g7_record_FAM$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "recordFAM", "symbols": ["Level", "D", "Xref", "D", {"literal":"FAM"}, "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, uri: "g7_record_FAM", type: "FAM_RECORD", checkCardinalityOf: {"g7_RESN":"0:1", "g7_FAM_HUSB":"0:1", "g7_FAM_WIFE":"0:1"}})},
    {"name": "recordFAMSubstructs", "symbols": ["g7_RESN"], "postprocess": id},
    {"name": "recordFAMSubstructs", "symbols": ["g7_FAM_HUSB"], "postprocess": id},
    {"name": "recordFAMSubstructs", "symbols": ["g7_FAM_WIFE"], "postprocess": id}
]
  , ParserStart: "g7_record_FAM"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
