// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

    // required modules
    const postprocessor = require('../generator/Postprocessors.js');
    const {lineTypes} = require('../../Constants.js')
    const moo = require("moo");

    // moo-lexer to pre-compile input
    const lexer = moo.compile({
        D : /[ ]/,
        digit      : /[0-9]/,
        underscore : /[_]/,
        Xref     : /\@[A-Z0-9\_]+\@/,
        EOL: {match: /(?:\r\n?|\n)/, lineBreaks: true },
        // not Banned, no EOL, no Space, no @, no _
        notBannedNoEOLNoSpace:  /[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x0A\x0D\x20\x40\x5F]+/
    });
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "Level", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "Level$ebnf$1", "symbols": []},
    {"name": "Level$ebnf$1", "symbols": ["Level$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Level", "symbols": ["nonzero", "Level$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "D", "symbols": [/[ ]/], "postprocess": id},
    {"name": "Xref$ebnf$1", "symbols": ["tagChar"]},
    {"name": "Xref$ebnf$1", "symbols": ["Xref$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Xref", "symbols": ["atsign", "Xref$ebnf$1", "atsign"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Tag", "symbols": ["stdTag"], "postprocess": id},
    {"name": "Tag", "symbols": ["extTag"], "postprocess": id},
    {"name": "LineVal", "symbols": ["pointer"], "postprocess": id},
    {"name": "LineVal", "symbols": ["lineStr"], "postprocess": id},
    {"name": "EOL", "symbols": [/[\x0A]/], "postprocess": id},
    {"name": "stdTag$ebnf$1", "symbols": []},
    {"name": "stdTag$ebnf$1", "symbols": ["stdTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "stdTag", "symbols": ["ucletter", "stdTag$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "extTag$ebnf$1", "symbols": ["tagChar"]},
    {"name": "extTag$ebnf$1", "symbols": ["extTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extTag", "symbols": ["underscore", "extTag$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "tagChar", "symbols": ["ucletter"], "postprocess": id},
    {"name": "tagChar", "symbols": ["digit"], "postprocess": id},
    {"name": "tagChar", "symbols": ["underscore"], "postprocess": id},
    {"name": "pointer", "symbols": ["voidPrt"], "postprocess": id},
    {"name": "pointer", "symbols": ["Xref"], "postprocess": id},
    {"name": "voidPrt", "symbols": [{"literal":"@VOID@"}], "postprocess": id},
    {"name": "nonAt", "symbols": [/[^@\n]/], "postprocess": id},
    {"name": "nonEOL", "symbols": [/[^\n]/], "postprocess": id},
    {"name": "lineStr$ebnf$1", "symbols": []},
    {"name": "lineStr$ebnf$1", "symbols": ["lineStr$ebnf$1", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["nonAt", "lineStr$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "lineStr$ebnf$2", "symbols": []},
    {"name": "lineStr$ebnf$2", "symbols": ["lineStr$ebnf$2", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["atsign", "atsign", "lineStr$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "digit", "symbols": [/[0-9]/], "postprocess": id},
    {"name": "nonzero", "symbols": [/[1-9]/], "postprocess": id},
    {"name": "ucletter", "symbols": [/[A-Z]/], "postprocess": id},
    {"name": "underscore", "symbols": [{"literal":"_"}], "postprocess": id},
    {"name": "atsign", "symbols": [{"literal":"@"}], "postprocess": id},
    {"name": "banned", "symbols": [/[\x00-\x08]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x0B-\x0C]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x0E-\x1F]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x7F]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x80-\x9F]/], "postprocess": id},
    {"name": "notBanned", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F]/], "postprocess": id},
    {"name": "notBannedNoEOL", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x0A\x0D]/], "postprocess": id},
    {"name": "anychar", "symbols": ["notBannedNoEOL"], "postprocess": id},
    {"name": "Text$ebnf$1", "symbols": []},
    {"name": "Text$ebnf$1", "symbols": ["Text$ebnf$1", "anychar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Text", "symbols": ["Text$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Integer$ebnf$1", "symbols": ["digit"]},
    {"name": "Integer$ebnf$1", "symbols": ["Integer$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Integer", "symbols": ["Integer$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "stdEnum", "symbols": ["stdTag"], "postprocess": id},
    {"name": "stdEnum", "symbols": ["Integer"], "postprocess": id},
    {"name": "Enum", "symbols": ["stdEnum"], "postprocess": id},
    {"name": "Enum", "symbols": ["extTag"], "postprocess": id},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["date"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["DatePeriod"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateRange"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateApprox"]},
    {"name": "DateValue$ebnf$1", "symbols": ["DateValue$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DateValue$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DateValue", "symbols": ["DateValue$ebnf$1"], "postprocess": id},
    {"name": "DateExact", "symbols": ["day", "D", "month", "D", "year"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "DatePeriod$ebnf$1$subexpression$1", "symbols": [{"literal":"TO"}, "D", "date"]},
    {"name": "DatePeriod$ebnf$1", "symbols": ["DatePeriod$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": ["DatePeriod$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "DatePeriod$ebnf$2$subexpression$1", "symbols": ["D", {"literal":"TO"}, "D", "date"]},
    {"name": "DatePeriod$ebnf$2", "symbols": ["DatePeriod$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": [{"literal":"FROM"}, "D", "date", "DatePeriod$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "date$ebnf$1$subexpression$1", "symbols": ["calendar", "D"]},
    {"name": "date$ebnf$1", "symbols": ["date$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1$subexpression$1", "symbols": ["day", "D"]},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1", "month", "D"]},
    {"name": "date$ebnf$2", "symbols": ["date$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$3$subexpression$1", "symbols": ["D", "epoch"]},
    {"name": "date$ebnf$3", "symbols": ["date$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date", "symbols": ["date$ebnf$1", "date$ebnf$2", "year", "date$ebnf$3"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateRange", "symbols": [{"literal":"BET"}, "D", "date", "D", {"literal":"AND"}, "D", "date"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateRange", "symbols": [{"literal":"AFT"}, "D", "date"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateRange", "symbols": [{"literal":"BEF"}, "D", "date"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateApprox$subexpression$1", "symbols": [{"literal":"ABT"}]},
    {"name": "dateApprox$subexpression$1", "symbols": [{"literal":"CAL"}]},
    {"name": "dateApprox$subexpression$1", "symbols": [{"literal":"EST"}]},
    {"name": "dateApprox", "symbols": ["dateApprox$subexpression$1", "D", "date"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "dateRestrict", "symbols": [{"literal":"FROM"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"TO"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"BET"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"AND"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"BEF"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"AFT"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"ABT"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"CAL"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"EST"}], "postprocess": id},
    {"name": "dateRestrict", "symbols": [{"literal":"BCE"}], "postprocess": id},
    {"name": "calendar", "symbols": [{"literal":"GREGORIAN"}], "postprocess": id},
    {"name": "calendar", "symbols": [{"literal":"JULIAN"}], "postprocess": id},
    {"name": "calendar", "symbols": [{"literal":"FRENCH_R"}], "postprocess": id},
    {"name": "calendar", "symbols": [{"literal":"HEBREW"}], "postprocess": id},
    {"name": "calendar", "symbols": ["extTag"]},
    {"name": "day", "symbols": ["Integer"], "postprocess": id},
    {"name": "year", "symbols": ["Integer"], "postprocess": id},
    {"name": "month", "symbols": ["stdTag"], "postprocess": id},
    {"name": "month", "symbols": ["extTag"], "postprocess": id},
    {"name": "epoch", "symbols": [{"literal":"BCE"}], "postprocess": id},
    {"name": "epoch", "symbols": ["extTag"], "postprocess": id},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [{"literal":"."}, "fraction"]},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$1$subexpression$1", "symbols": [{"literal":":"}, "second", "Time$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "Time$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$2$subexpression$1", "symbols": [{"literal":"Z"}]},
    {"name": "Time$ebnf$2", "symbols": ["Time$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time", "symbols": ["hour", {"literal":":"}, "minute", "Time$ebnf$1", "Time$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "hour", "symbols": ["digit"], "postprocess": id},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "hour", "symbols": ["hour$subexpression$1", "digit"]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"1"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"2"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"3"}]},
    {"name": "hour", "symbols": [{"literal":"2"}, "hour$subexpression$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "minute", "symbols": ["minute$subexpression$1", "digit"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "second$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "second", "symbols": ["second$subexpression$1", "digit"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "fraction$ebnf$1", "symbols": ["digit"]},
    {"name": "fraction$ebnf$1", "symbols": ["fraction$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "fraction", "symbols": ["fraction$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Age$ebnf$1$subexpression$1", "symbols": ["ageBound", "D"]},
    {"name": "Age$ebnf$1", "symbols": ["Age$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Age$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Age", "symbols": ["Age$ebnf$1", "ageDuration"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageBound", "symbols": [{"literal":"<"}], "postprocess": id},
    {"name": "ageBound", "symbols": [{"literal":">"}], "postprocess": id},
    {"name": "years", "symbols": ["Integer", {"literal":"y"}], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "months", "symbols": ["Integer", {"literal":"m"}], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "weeks", "symbols": ["Integer", {"literal":"w"}], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "days", "symbols": ["Integer", {"literal":"d"}], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$1$subexpression$1", "symbols": ["D", "months"]},
    {"name": "ageDuration$ebnf$1", "symbols": ["ageDuration$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$2$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$2", "symbols": ["ageDuration$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$3$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$3", "symbols": ["ageDuration$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["years", "ageDuration$ebnf$1", "ageDuration$ebnf$2", "ageDuration$ebnf$3"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$4$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$4", "symbols": ["ageDuration$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$5$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$5", "symbols": ["ageDuration$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["months", "ageDuration$ebnf$4", "ageDuration$ebnf$5"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$6$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$6", "symbols": ["ageDuration$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["weeks", "ageDuration$ebnf$6"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "ageDuration", "symbols": ["days"], "postprocess": id},
    {"name": "list$ebnf$1", "symbols": []},
    {"name": "list$ebnf$1$subexpression$1", "symbols": ["listDelim", "listItem"]},
    {"name": "list$ebnf$1", "symbols": ["list$ebnf$1", "list$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "list", "symbols": ["listItem", "list$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "listItem$ebnf$1$subexpression$1", "symbols": ["nocommasp"]},
    {"name": "listItem$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "listItem$ebnf$1$subexpression$1$ebnf$1", "symbols": ["listItem$ebnf$1$subexpression$1$ebnf$1", "nocomma"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listItem$ebnf$1$subexpression$1", "symbols": ["nocommasp", "listItem$ebnf$1$subexpression$1$ebnf$1", "nocommasp"]},
    {"name": "listItem$ebnf$1", "symbols": ["listItem$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "listItem$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "listItem", "symbols": ["listItem$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "listDelim$ebnf$1", "symbols": []},
    {"name": "listDelim$ebnf$1", "symbols": ["listDelim$ebnf$1", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listDelim$ebnf$2", "symbols": []},
    {"name": "listDelim$ebnf$2", "symbols": ["listDelim$ebnf$2", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listDelim", "symbols": ["listDelim$ebnf$1", {"literal":","}, "listDelim$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "nocomma", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x2C]/], "postprocess": id},
    {"name": "nocommasp", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x2C\x1E-\x20]/], "postprocess": id},
    {"name": "ListText", "symbols": ["list"], "postprocess": id},
    {"name": "ListEnum$ebnf$1", "symbols": []},
    {"name": "ListEnum$ebnf$1$subexpression$1", "symbols": ["listDelim", "Enum"]},
    {"name": "ListEnum$ebnf$1", "symbols": ["ListEnum$ebnf$1", "ListEnum$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "ListEnum", "symbols": ["Enum", "ListEnum$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "PersonalName", "symbols": ["nameStr"]},
    {"name": "PersonalName$ebnf$1", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$2", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$3", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName", "symbols": ["PersonalName$ebnf$1", {"literal":"/"}, "PersonalName$ebnf$2", {"literal":"/"}, "PersonalName$ebnf$3"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "nameChar", "symbols": [/[^\x00-\x19\x2F]/], "postprocess": id},
    {"name": "nameStr$ebnf$1", "symbols": ["nameChar"]},
    {"name": "nameStr$ebnf$1", "symbols": ["nameStr$ebnf$1", "nameChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "nameStr", "symbols": ["nameStr$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Language$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "script"]},
    {"name": "Language$ebnf$1", "symbols": ["Language$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Language$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Language$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "region"]},
    {"name": "Language$ebnf$2", "symbols": ["Language$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Language$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Language$ebnf$3", "symbols": []},
    {"name": "Language$ebnf$3$subexpression$1", "symbols": [{"literal":"-"}, "variant"]},
    {"name": "Language$ebnf$3", "symbols": ["Language$ebnf$3", "Language$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Language$ebnf$4", "symbols": []},
    {"name": "Language$ebnf$4$subexpression$1", "symbols": [{"literal":"-"}, "extension"]},
    {"name": "Language$ebnf$4", "symbols": ["Language$ebnf$4", "Language$ebnf$4$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Language$ebnf$5$subexpression$1", "symbols": [{"literal":"-"}, "privateuse"]},
    {"name": "Language$ebnf$5", "symbols": ["Language$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "Language$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Language", "symbols": ["lang", "Language$ebnf$1", "Language$ebnf$2", "Language$ebnf$3", "Language$ebnf$4", "Language$ebnf$5"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "lang$ebnf$1", "symbols": ["alpha"], "postprocess": id},
    {"name": "lang$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "extlang"]},
    {"name": "lang$ebnf$2", "symbols": ["lang$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "lang$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang", "symbols": ["alpha", "alpha", "lang$ebnf$1", "lang$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "lang", "symbols": ["alpha", "alpha", "alpha", "alpha"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "lang$ebnf$3$subexpression$1", "symbols": ["alpha"]},
    {"name": "lang$ebnf$3", "symbols": ["lang$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "lang$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang$ebnf$4$subexpression$1", "symbols": ["alpha"]},
    {"name": "lang$ebnf$4", "symbols": ["lang$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "lang$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang$ebnf$5$subexpression$1", "symbols": ["alpha"]},
    {"name": "lang$ebnf$5", "symbols": ["lang$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "lang$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "lang", "symbols": ["alpha", "alpha", "alpha", "alpha", "alpha", "lang$ebnf$3", "lang$ebnf$4", "lang$ebnf$5"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "extlang$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$1", "symbols": ["extlang$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$2", "symbols": ["extlang$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang", "symbols": ["alpha", "alpha", "alpha", "extlang$ebnf$1", "extlang$ebnf$2"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "script", "symbols": ["alpha", "alpha", "alpha", "alpha"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "region", "symbols": ["alpha", "alpha"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "region", "symbols": ["digit", "digit", "digit"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "variant", "symbols": ["digit", "alphanum", "alphanum", "alphanum"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "variant$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$1", "symbols": ["variant$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$2", "symbols": ["variant$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$3", "symbols": ["variant$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant", "symbols": ["alphanum", "alphanum", "alphanum", "alphanum", "alphanum", "variant$ebnf$1", "variant$ebnf$2", "variant$ebnf$3"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$1$ebnf$1", "extension$ebnf$1$subexpression$1$ebnf$2", "extension$ebnf$1$subexpression$1$ebnf$3", "extension$ebnf$1$subexpression$1$ebnf$4", "extension$ebnf$1$subexpression$1$ebnf$5", "extension$ebnf$1$subexpression$1$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$2$ebnf$1", "extension$ebnf$1$subexpression$2$ebnf$2", "extension$ebnf$1$subexpression$2$ebnf$3", "extension$ebnf$1$subexpression$2$ebnf$4", "extension$ebnf$1$subexpression$2$ebnf$5", "extension$ebnf$1$subexpression$2$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1", "extension$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extension", "symbols": ["singleton", "extension$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "singleton", "symbols": ["digit"], "postprocess": id},
    {"name": "singleton", "symbols": [/[\x41-\x57\x59-\x5A\x61-\x77\x79-\x7A]/], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$1$ebnf$1", "privateuse$ebnf$1$subexpression$1$ebnf$2", "privateuse$ebnf$1$subexpression$1$ebnf$3", "privateuse$ebnf$1$subexpression$1$ebnf$4", "privateuse$ebnf$1$subexpression$1$ebnf$5", "privateuse$ebnf$1$subexpression$1$ebnf$6", "privateuse$ebnf$1$subexpression$1$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$2$ebnf$1", "privateuse$ebnf$1$subexpression$2$ebnf$2", "privateuse$ebnf$1$subexpression$2$ebnf$3", "privateuse$ebnf$1$subexpression$2$ebnf$4", "privateuse$ebnf$1$subexpression$2$ebnf$5", "privateuse$ebnf$1$subexpression$2$ebnf$6", "privateuse$ebnf$1$subexpression$2$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1", "privateuse$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "privateuse", "symbols": [{"literal":"x"}, "privateuse$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "alpha", "symbols": [/[a-zA-z]/], "postprocess": id},
    {"name": "alphanum", "symbols": ["alpha"], "postprocess": id},
    {"name": "alphanum", "symbols": ["digit"], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"en-GB-oed"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-ami"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-bnn"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-default"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-enochian"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-hak"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-klingon"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-lux"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-mingo"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-navajo"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-pwn"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-tao"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-tay"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"i-tsu"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"sgn-BE-FR"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"sgn-BE-NL"}], "postprocess": id},
    {"name": "irregular", "symbols": [{"literal":"sgn-CH-DE"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"art-lojban"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"cel-gaulish"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"no-bok"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"no-nyn"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-guoyu"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-hakka"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-min"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-min-nan"}], "postprocess": id},
    {"name": "regular", "symbols": [{"literal":"zh-xiang"}], "postprocess": id},
    {"name": "grandfathered", "symbols": ["irregular"], "postprocess": id},
    {"name": "grandfathered", "symbols": ["regular"], "postprocess": id},
    {"name": "MediaType$ebnf$1", "symbols": []},
    {"name": "MediaType$ebnf$1$subexpression$1", "symbols": [{"literal":";"}, "mt_parameter"]},
    {"name": "MediaType$ebnf$1", "symbols": ["MediaType$ebnf$1", "MediaType$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "MediaType", "symbols": ["mt_type", {"literal":"/"}, "mt_subtype", "MediaType$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "mt_type", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_subtype", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_parameter", "symbols": ["mt_attribute", {"literal":"="}, "mt_value"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "mt_token$ebnf$1$subexpression$1", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1$subexpression$1"]},
    {"name": "mt_token$ebnf$1$subexpression$2", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1", "mt_token$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_token", "symbols": ["mt_token$ebnf$1"], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "mt_attribute", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_value", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_value", "symbols": ["mt_qstring"], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x20-\x21]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x23-\x27]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x2A-\x2B]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x2D-\x2E]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x30-\x39]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x41-\x5A]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x5E-\x7E]/], "postprocess": id},
    {"name": "mt_qstring$ebnf$1", "symbols": []},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qtext"]},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qpair"]},
    {"name": "mt_qstring$ebnf$1", "symbols": ["mt_qstring$ebnf$1", "mt_qstring$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_qstring", "symbols": [/[\x22]/, "mt_qstring$ebnf$1", /[\x22]/], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "mt_qtext", "symbols": [/[\x09-\x0A]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x20-\x21]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x23-\x5B]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x5D-\x7E]/], "postprocess": id},
    {"name": "mt_qpair", "symbols": [{"literal":"\\"}, /[\x09-7E]/], "postprocess": postprocessor.joinAndUnpackAll},
    {"name": "Special", "symbols": ["Text"], "postprocess": id},
    {"name": "NullOrY$ebnf$1", "symbols": [{"literal":"Y"}], "postprocess": id},
    {"name": "NullOrY$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "NullOrY", "symbols": ["NullOrY$ebnf$1"], "postprocess": id},
    {"name": "RESN_ENUM", "symbols": [{"literal":"CONFIDENTIAL"}], "postprocess": id},
    {"name": "RESN_ENUM", "symbols": [{"literal":"LOCKED"}], "postprocess": id},
    {"name": "RESN_ENUM", "symbols": [{"literal":"PRIVACY"}], "postprocess": id},
    {"name": "NAME_PIECES_ENUM", "symbols": [{"literal":"NPFX"}], "postprocess": id},
    {"name": "NAME_PIECES_ENUM", "symbols": [{"literal":"GIVN"}], "postprocess": id},
    {"name": "NAME_PIECES_ENUM", "symbols": [{"literal":"NICK"}], "postprocess": id},
    {"name": "NAME_PIECES_ENUM", "symbols": [{"literal":"SPFX"}], "postprocess": id},
    {"name": "NAME_PIECES_ENUM", "symbols": [{"literal":"SURN"}], "postprocess": id},
    {"name": "NAME_PIECES_ENUM", "symbols": [{"literal":"NSFX"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"CHIL"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"CLERGY"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"FATH"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"FRIEND"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"GODP"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"HUSB"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"MOTH"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"MULTIPLE"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"NGHBR"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"OFFICIATOR"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"SPOU"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"WIFE"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"WITN"}], "postprocess": id},
    {"name": "ROLE", "symbols": [{"literal":"OTHER"}], "postprocess": id},
    {"name": "SEX_ENUM", "symbols": [{"literal":"M"}], "postprocess": id},
    {"name": "SEX_ENUM", "symbols": [{"literal":"F"}], "postprocess": id},
    {"name": "SEX_ENUM", "symbols": [{"literal":"X"}], "postprocess": id},
    {"name": "SEX_ENUM", "symbols": [{"literal":"U"}], "postprocess": id},
    {"name": "ADOP_ENUM", "symbols": [{"literal":"HUSB"}], "postprocess": id},
    {"name": "ADOP_ENUM", "symbols": [{"literal":"WIFE"}], "postprocess": id},
    {"name": "ADOP_ENUM", "symbols": [{"literal":"BOTH"}], "postprocess": id},
    {"name": "EVENTS", "symbols": ["INDIVIDUAL_EVENTS"]},
    {"name": "EVENTS", "symbols": ["FAMILY_EVENTS"]},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"ADOP"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"BAPM"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"BARM"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"BASM"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"BIRT"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"BLES"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"BURI"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"CENS"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"CHR"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"CHRA"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"CONF"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"CREM"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"DEAT"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"EMIG"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"FCOM"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"GRAD"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"IMMI"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"NATU"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"ORDN"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"PROB"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"RETI"}], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS", "symbols": [{"literal":"WILL"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"ANUL"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"CENS"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"DIV"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"DIVFG"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"ENGA"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"MARB"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"MARC"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"MARR"}], "postprocess": id},
    {"name": "FAMILY_EVENTS", "symbols": [{"literal":"MARS"}], "postprocess": id},
    {"name": "ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES"], "postprocess": id},
    {"name": "ATTRIBUTES", "symbols": ["FAMILY_ATTRIBUTES"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"CAST"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"DSCR"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"EDUC"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"IDNO"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"NATI"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"NCHI"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"NMR"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"OCCU"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"PROP"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"RELI"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"RESI"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"SSN"}], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": [{"literal":"TITL"}], "postprocess": id},
    {"name": "FAMILY_ATTRIBUTES", "symbols": [{"literal":"NCHI"}], "postprocess": id},
    {"name": "FAMILY_ATTRIBUTES", "symbols": [{"literal":"RESI"}], "postprocess": id},
    {"name": "FAMC_STAT_ENUM", "symbols": [{"literal":"CHALLENGED"}], "postprocess": id},
    {"name": "FAMC_STAT_ENUM", "symbols": [{"literal":"DISPROVEN"}], "postprocess": id},
    {"name": "FAMC_STAT_ENUM", "symbols": [{"literal":"PROVEN"}], "postprocess": id},
    {"name": "PEDI_ENUM", "symbols": [{"literal":"ADOPTED"}], "postprocess": id},
    {"name": "PEDI_ENUM", "symbols": [{"literal":"BIRTH"}], "postprocess": id},
    {"name": "PEDI_ENUM", "symbols": [{"literal":"FOSTER"}], "postprocess": id},
    {"name": "PEDI_ENUM", "symbols": [{"literal":"SEALING"}], "postprocess": id},
    {"name": "PEDI_ENUM", "symbols": [{"literal":"OTHER"}], "postprocess": id},
    {"name": "g7_FAM_HUSB", "symbols": ["Level", "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "D", {"literal":"HUSB"}, "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, type: "NO_LINEVAL", checkCardinalityOf: {PHRASE:"0:1"}})},
    {"name": "g7_FAM_HUSB", "symbols": ["g7_FAM_HUSB", "g7_PHRASE"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_FAM_WIFE", "symbols": ["Level", "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "D", {"literal":"WIFE"}, "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, type: "NO_LINEVAL", checkCardinalityOf: {PHRASE:"0:1"}})},
    {"name": "g7_FAM_WIFE", "symbols": ["g7_FAM_WIFE", "g7_PHRASE"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "g7_PHRASE", "symbols": ["Level", "D", {"literal":"PHRASE"}, "D", "Text", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, type: "NO_XREF"})},
    {"name": "g7_TEST", "symbols": ["Level", "D", {"literal":"TEST"}, "D", "Text", "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, type: "NO_XREF"})},
    {"name": "g7_record_FAM", "symbols": ["recordFAM"], "postprocess": id},
    {"name": "g7_record_FAM$ebnf$1", "symbols": ["recordFAMSubstructs"]},
    {"name": "g7_record_FAM$ebnf$1", "symbols": ["g7_record_FAM$ebnf$1", "recordFAMSubstructs"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "g7_record_FAM", "symbols": ["recordFAM", "g7_record_FAM$ebnf$1"], "postprocess": (d) => postprocessor.addSubstructure({superstruct: d[0], substructs: d[1]})},
    {"name": "recordFAM", "symbols": ["Level", "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "D", {"literal":"FAM"}, "EOL"], "postprocess": (d) => postprocessor.createStructure({line: d, type: "FAM_RECORD", checkCardinalityOf: {HUSB:"0:1"}})},
    {"name": "recordFAMSubstructs", "symbols": ["g7_FAM_HUSB"], "postprocess": id},
    {"name": "recordFAMSubstructs", "symbols": ["g7_FAM_WIFE"], "postprocess": id}
]
  , ParserStart: "g7_record_FAM"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
