// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "RESN_ENUM$string$1", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"F"}, {"literal":"I"}, {"literal":"D"}, {"literal":"E"}, {"literal":"N"}, {"literal":"T"}, {"literal":"I"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RESN_ENUM", "symbols": ["RESN_ENUM$string$1"]},
    {"name": "RESN_ENUM$string$2", "symbols": [{"literal":"L"}, {"literal":"O"}, {"literal":"C"}, {"literal":"K"}, {"literal":"E"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RESN_ENUM", "symbols": ["RESN_ENUM$string$2"]},
    {"name": "RESN_ENUM$string$3", "symbols": [{"literal":"P"}, {"literal":"R"}, {"literal":"I"}, {"literal":"V"}, {"literal":"A"}, {"literal":"C"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RESN_ENUM", "symbols": ["RESN_ENUM$string$3"]},
    {"name": "NAME_PIECES_ENUM$string$1", "symbols": [{"literal":"N"}, {"literal":"P"}, {"literal":"F"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$1"]},
    {"name": "NAME_PIECES_ENUM$string$2", "symbols": [{"literal":"G"}, {"literal":"I"}, {"literal":"V"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$2"]},
    {"name": "NAME_PIECES_ENUM$string$3", "symbols": [{"literal":"N"}, {"literal":"I"}, {"literal":"C"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$3"]},
    {"name": "NAME_PIECES_ENUM$string$4", "symbols": [{"literal":"S"}, {"literal":"P"}, {"literal":"F"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$4"]},
    {"name": "NAME_PIECES_ENUM$string$5", "symbols": [{"literal":"S"}, {"literal":"U"}, {"literal":"R"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$5"]},
    {"name": "NAME_PIECES_ENUM$string$6", "symbols": [{"literal":"N"}, {"literal":"S"}, {"literal":"F"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$6"]},
    {"name": "ROLE$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"I"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$1"]},
    {"name": "ROLE$string$2", "symbols": [{"literal":"C"}, {"literal":"L"}, {"literal":"E"}, {"literal":"R"}, {"literal":"G"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$2"]},
    {"name": "ROLE$string$3", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$3"]},
    {"name": "ROLE$string$4", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"I"}, {"literal":"E"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$4"]},
    {"name": "ROLE$string$5", "symbols": [{"literal":"G"}, {"literal":"O"}, {"literal":"D"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$5"]},
    {"name": "ROLE$string$6", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"S"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$6"]},
    {"name": "ROLE$string$7", "symbols": [{"literal":"M"}, {"literal":"O"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$7"]},
    {"name": "ROLE$string$8", "symbols": [{"literal":"M"}, {"literal":"U"}, {"literal":"L"}, {"literal":"T"}, {"literal":"I"}, {"literal":"P"}, {"literal":"L"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$8"]},
    {"name": "ROLE$string$9", "symbols": [{"literal":"N"}, {"literal":"G"}, {"literal":"H"}, {"literal":"B"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$9"]},
    {"name": "ROLE$string$10", "symbols": [{"literal":"O"}, {"literal":"F"}, {"literal":"F"}, {"literal":"I"}, {"literal":"C"}, {"literal":"I"}, {"literal":"A"}, {"literal":"T"}, {"literal":"O"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$10"]},
    {"name": "ROLE$string$11", "symbols": [{"literal":"S"}, {"literal":"P"}, {"literal":"O"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$11"]},
    {"name": "ROLE$string$12", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"F"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$12"]},
    {"name": "ROLE$string$13", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"T"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$13"]},
    {"name": "ROLE$string$14", "symbols": [{"literal":"O"}, {"literal":"T"}, {"literal":"H"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$14"]},
    {"name": "SEX_ENUM", "symbols": [{"literal":"M"}]},
    {"name": "SEX_ENUM", "symbols": [{"literal":"F"}]},
    {"name": "SEX_ENUM", "symbols": [{"literal":"X"}]},
    {"name": "SEX_ENUM", "symbols": [{"literal":"U"}]},
    {"name": "ADOP_ENUM$string$1", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"S"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADOP_ENUM", "symbols": ["ADOP_ENUM$string$1"]},
    {"name": "ADOP_ENUM$string$2", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"F"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADOP_ENUM", "symbols": ["ADOP_ENUM$string$2"]},
    {"name": "ADOP_ENUM$string$3", "symbols": [{"literal":"B"}, {"literal":"O"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADOP_ENUM", "symbols": ["ADOP_ENUM$string$3"]},
    {"name": "EVENTS", "symbols": ["INDIVIDUAL_EVENTS"]},
    {"name": "EVENTS", "symbols": ["FAMILY_EVENTS"]},
    {"name": "INDIVIDUAL_EVENTS$string$1", "symbols": [{"literal":"A"}, {"literal":"D"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$1"]},
    {"name": "INDIVIDUAL_EVENTS$string$2", "symbols": [{"literal":"B"}, {"literal":"A"}, {"literal":"P"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$2"]},
    {"name": "INDIVIDUAL_EVENTS$string$3", "symbols": [{"literal":"B"}, {"literal":"A"}, {"literal":"R"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$3"]},
    {"name": "INDIVIDUAL_EVENTS$string$4", "symbols": [{"literal":"B"}, {"literal":"A"}, {"literal":"S"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$4"]},
    {"name": "INDIVIDUAL_EVENTS$string$5", "symbols": [{"literal":"B"}, {"literal":"I"}, {"literal":"R"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$5"]},
    {"name": "INDIVIDUAL_EVENTS$string$6", "symbols": [{"literal":"B"}, {"literal":"L"}, {"literal":"E"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$6"]},
    {"name": "INDIVIDUAL_EVENTS$string$7", "symbols": [{"literal":"B"}, {"literal":"U"}, {"literal":"R"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$7"]},
    {"name": "INDIVIDUAL_EVENTS$string$8", "symbols": [{"literal":"C"}, {"literal":"E"}, {"literal":"N"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$8"]},
    {"name": "INDIVIDUAL_EVENTS$string$9", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$9"]},
    {"name": "INDIVIDUAL_EVENTS$string$10", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"R"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$10"]},
    {"name": "INDIVIDUAL_EVENTS$string$11", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$11"]},
    {"name": "INDIVIDUAL_EVENTS$string$12", "symbols": [{"literal":"C"}, {"literal":"R"}, {"literal":"E"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$12"]},
    {"name": "INDIVIDUAL_EVENTS$string$13", "symbols": [{"literal":"D"}, {"literal":"E"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$13"]},
    {"name": "INDIVIDUAL_EVENTS$string$14", "symbols": [{"literal":"E"}, {"literal":"M"}, {"literal":"I"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$14"]},
    {"name": "INDIVIDUAL_EVENTS$string$15", "symbols": [{"literal":"F"}, {"literal":"C"}, {"literal":"O"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$15"]},
    {"name": "INDIVIDUAL_EVENTS$string$16", "symbols": [{"literal":"G"}, {"literal":"R"}, {"literal":"A"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$16"]},
    {"name": "INDIVIDUAL_EVENTS$string$17", "symbols": [{"literal":"I"}, {"literal":"M"}, {"literal":"M"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$17"]},
    {"name": "INDIVIDUAL_EVENTS$string$18", "symbols": [{"literal":"N"}, {"literal":"A"}, {"literal":"T"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$18"]},
    {"name": "INDIVIDUAL_EVENTS$string$19", "symbols": [{"literal":"O"}, {"literal":"R"}, {"literal":"D"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$19"]},
    {"name": "INDIVIDUAL_EVENTS$string$20", "symbols": [{"literal":"P"}, {"literal":"R"}, {"literal":"O"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$20"]},
    {"name": "INDIVIDUAL_EVENTS$string$21", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"T"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$21"]},
    {"name": "INDIVIDUAL_EVENTS$string$22", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"L"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$22"]},
    {"name": "FAMILY_EVENTS$string$1", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"U"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$1"]},
    {"name": "FAMILY_EVENTS$string$2", "symbols": [{"literal":"C"}, {"literal":"E"}, {"literal":"N"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$2"]},
    {"name": "FAMILY_EVENTS$string$3", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"V"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$3"]},
    {"name": "FAMILY_EVENTS$string$4", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"V"}, {"literal":"F"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$4"]},
    {"name": "FAMILY_EVENTS$string$5", "symbols": [{"literal":"E"}, {"literal":"N"}, {"literal":"G"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$5"]},
    {"name": "FAMILY_EVENTS$string$6", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"R"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$6"]},
    {"name": "FAMILY_EVENTS$string$7", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"R"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$7"]},
    {"name": "FAMILY_EVENTS$string$8", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"R"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$8"]},
    {"name": "FAMILY_EVENTS$string$9", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"R"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$9"]},
    {"name": "ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES"]},
    {"name": "ATTRIBUTES", "symbols": ["FAMILY_ATTRIBUTES"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$1", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$1"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$2", "symbols": [{"literal":"D"}, {"literal":"S"}, {"literal":"C"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$2"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$3", "symbols": [{"literal":"E"}, {"literal":"D"}, {"literal":"U"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$3"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$4", "symbols": [{"literal":"I"}, {"literal":"D"}, {"literal":"N"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$4"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$5", "symbols": [{"literal":"N"}, {"literal":"A"}, {"literal":"T"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$5"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$6", "symbols": [{"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$6"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$7", "symbols": [{"literal":"N"}, {"literal":"M"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$7"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$8", "symbols": [{"literal":"O"}, {"literal":"C"}, {"literal":"C"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$8"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$9", "symbols": [{"literal":"P"}, {"literal":"R"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$9"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$10", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"L"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$10"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$11", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"S"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$11"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$12", "symbols": [{"literal":"S"}, {"literal":"S"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$12"]},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$13", "symbols": [{"literal":"T"}, {"literal":"I"}, {"literal":"T"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$13"]},
    {"name": "FAMILY_ATTRIBUTES$string$1", "symbols": [{"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_ATTRIBUTES", "symbols": ["FAMILY_ATTRIBUTES$string$1"]},
    {"name": "FAMILY_ATTRIBUTES$string$2", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"S"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_ATTRIBUTES", "symbols": ["FAMILY_ATTRIBUTES$string$2"]},
    {"name": "FAMC_STAT_ENUM$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"A"}, {"literal":"L"}, {"literal":"L"}, {"literal":"E"}, {"literal":"N"}, {"literal":"G"}, {"literal":"E"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMC_STAT_ENUM", "symbols": ["FAMC_STAT_ENUM$string$1"]},
    {"name": "FAMC_STAT_ENUM$string$2", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"S"}, {"literal":"P"}, {"literal":"R"}, {"literal":"O"}, {"literal":"V"}, {"literal":"E"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMC_STAT_ENUM", "symbols": ["FAMC_STAT_ENUM$string$2"]},
    {"name": "FAMC_STAT_ENUM$string$3", "symbols": [{"literal":"P"}, {"literal":"R"}, {"literal":"O"}, {"literal":"V"}, {"literal":"E"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMC_STAT_ENUM", "symbols": ["FAMC_STAT_ENUM$string$3"]},
    {"name": "PEDI_ENUM$string$1", "symbols": [{"literal":"A"}, {"literal":"D"}, {"literal":"O"}, {"literal":"P"}, {"literal":"T"}, {"literal":"E"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$1"]},
    {"name": "PEDI_ENUM$string$2", "symbols": [{"literal":"B"}, {"literal":"I"}, {"literal":"R"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$2"]},
    {"name": "PEDI_ENUM$string$3", "symbols": [{"literal":"F"}, {"literal":"O"}, {"literal":"S"}, {"literal":"T"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$3"]},
    {"name": "PEDI_ENUM$string$4", "symbols": [{"literal":"S"}, {"literal":"E"}, {"literal":"A"}, {"literal":"L"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$4"]},
    {"name": "PEDI_ENUM$string$5", "symbols": [{"literal":"O"}, {"literal":"T"}, {"literal":"H"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$5"]},
    {"name": "Level", "symbols": [{"literal":"0"}]},
    {"name": "Level$ebnf$1", "symbols": []},
    {"name": "Level$ebnf$1", "symbols": ["Level$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Level", "symbols": ["nonzero", "Level$ebnf$1"], "postprocess": id},
    {"name": "D", "symbols": [/[ ]/]},
    {"name": "Xref$ebnf$1", "symbols": ["tagChar"]},
    {"name": "Xref$ebnf$1", "symbols": ["Xref$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Xref", "symbols": ["atsign", "Xref$ebnf$1", "atsign"], "postprocess": (data) => {return [data[0], ...data[1], data[2]].join('')}},
    {"name": "Tag", "symbols": ["stdTag"]},
    {"name": "Tag", "symbols": ["extTag"], "postprocess": id},
    {"name": "LineVal", "symbols": ["pointer"]},
    {"name": "LineVal", "symbols": ["lineStr"]},
    {"name": "EOL$ebnf$1", "symbols": [/[\x0A]/], "postprocess": id},
    {"name": "EOL$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "EOL", "symbols": [/[\x0D]/, "EOL$ebnf$1"]},
    {"name": "EOL", "symbols": [/[\x0A]/]},
    {"name": "stdTag$ebnf$1", "symbols": []},
    {"name": "stdTag$ebnf$1", "symbols": ["stdTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "stdTag", "symbols": ["ucletter", "stdTag$ebnf$1"]},
    {"name": "extTag$ebnf$1", "symbols": ["tagChar"]},
    {"name": "extTag$ebnf$1", "symbols": ["extTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extTag", "symbols": ["underscore", "extTag$ebnf$1"]},
    {"name": "tagChar", "symbols": ["ucletter"]},
    {"name": "tagChar", "symbols": ["digit"]},
    {"name": "tagChar", "symbols": ["underscore"]},
    {"name": "pointer", "symbols": ["voidPrt"]},
    {"name": "pointer", "symbols": ["Xref"]},
    {"name": "voidPrt$string$1", "symbols": [{"literal":"@"}, {"literal":"V"}, {"literal":"O"}, {"literal":"I"}, {"literal":"D"}, {"literal":"@"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "voidPrt", "symbols": ["voidPrt$string$1"]},
    {"name": "nonAt", "symbols": [/[^@\n]/]},
    {"name": "nonEOL", "symbols": [/[^\n]/]},
    {"name": "lineStr$ebnf$1", "symbols": []},
    {"name": "lineStr$ebnf$1", "symbols": ["lineStr$ebnf$1", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["nonAt", "lineStr$ebnf$1"]},
    {"name": "lineStr$ebnf$2", "symbols": []},
    {"name": "lineStr$ebnf$2", "symbols": ["lineStr$ebnf$2", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["atsign", "atsign", "lineStr$ebnf$2"]},
    {"name": "digit", "symbols": [/[0-9]/], "postprocess": id},
    {"name": "nonzero", "symbols": [/[1-9]/], "postprocess": id},
    {"name": "ucletter", "symbols": [/[A-Z]/], "postprocess": id},
    {"name": "underscore", "symbols": [{"literal":"_"}], "postprocess": id},
    {"name": "atsign", "symbols": [{"literal":"@"}], "postprocess": id},
    {"name": "newLine", "symbols": [{"literal":"\n"}]},
    {"name": "newLine$string$1", "symbols": [{"literal":"\n"}, {"literal":"\r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "newLine", "symbols": ["newLine$string$1"]},
    {"name": "newLine", "symbols": [{"literal":"\r"}]},
    {"name": "newLine$string$2", "symbols": [{"literal":"\r"}, {"literal":"\n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "newLine", "symbols": ["newLine$string$2"], "postprocess": id},
    {"name": "banned", "symbols": [/[\x00-\x08]/]},
    {"name": "banned", "symbols": [/[\x0B-\x0C]/]},
    {"name": "banned", "symbols": [/[\x0E-\x1F]/]},
    {"name": "banned", "symbols": [/[\x7F]/]},
    {"name": "banned", "symbols": [/[\x80-\x9F]/]},
    {"name": "notBanned", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F]/]},
    {"name": "anychar", "symbols": ["notBanned"]},
    {"name": "Text$ebnf$1", "symbols": []},
    {"name": "Text$ebnf$1", "symbols": ["Text$ebnf$1", "anychar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Text", "symbols": ["Text$ebnf$1"]},
    {"name": "Integer$ebnf$1", "symbols": ["digit"]},
    {"name": "Integer$ebnf$1", "symbols": ["Integer$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Integer", "symbols": ["Integer$ebnf$1"]},
    {"name": "stdEnum", "symbols": ["stdTag"]},
    {"name": "stdEnum", "symbols": ["Integer"]},
    {"name": "Enum", "symbols": ["stdEnum"]},
    {"name": "Enum", "symbols": ["extTag"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["date"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["DatePeriod"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateRange"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateApprox"]},
    {"name": "DateValue$ebnf$1", "symbols": ["DateValue$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DateValue$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DateValue", "symbols": ["DateValue$ebnf$1"]},
    {"name": "DateExact", "symbols": ["day", "D", "month", "D", "year"]},
    {"name": "DatePeriod$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$1$subexpression$1", "symbols": ["DatePeriod$ebnf$1$subexpression$1$string$1", "D", "date"]},
    {"name": "DatePeriod$ebnf$1", "symbols": ["DatePeriod$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": ["DatePeriod$ebnf$1"]},
    {"name": "DatePeriod$string$1", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"O"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$2$subexpression$1$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$2$subexpression$1", "symbols": ["D", "DatePeriod$ebnf$2$subexpression$1$string$1", "D", "date"]},
    {"name": "DatePeriod$ebnf$2", "symbols": ["DatePeriod$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": ["DatePeriod$string$1", "D", "date", "DatePeriod$ebnf$2"]},
    {"name": "date$ebnf$1$subexpression$1", "symbols": ["calendar", "D"]},
    {"name": "date$ebnf$1", "symbols": ["date$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1$subexpression$1", "symbols": ["day", "D"]},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1", "month", "D"]},
    {"name": "date$ebnf$2", "symbols": ["date$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$3$subexpression$1", "symbols": ["D", "epoch"]},
    {"name": "date$ebnf$3", "symbols": ["date$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date", "symbols": ["date$ebnf$1", "date$ebnf$2", "year", "date$ebnf$3"]},
    {"name": "dateRange$string$1", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange$string$2", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$1", "D", "date", "D", "dateRange$string$2", "D", "date"]},
    {"name": "dateRange$string$3", "symbols": [{"literal":"A"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$3", "D", "date"]},
    {"name": "dateRange$string$4", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$4", "D", "date"]},
    {"name": "dateApprox$subexpression$1$string$1", "symbols": [{"literal":"A"}, {"literal":"B"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$1"]},
    {"name": "dateApprox$subexpression$1$string$2", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$2"]},
    {"name": "dateApprox$subexpression$1$string$3", "symbols": [{"literal":"E"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$3"]},
    {"name": "dateApprox", "symbols": ["dateApprox$subexpression$1", "D", "date"]},
    {"name": "dateRestrict$string$1", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"O"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$1"]},
    {"name": "dateRestrict$string$2", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$2"]},
    {"name": "dateRestrict$string$3", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$3"]},
    {"name": "dateRestrict$string$4", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$4"]},
    {"name": "dateRestrict$string$5", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$5"]},
    {"name": "dateRestrict$string$6", "symbols": [{"literal":"A"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$6"]},
    {"name": "dateRestrict$string$7", "symbols": [{"literal":"A"}, {"literal":"B"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$7"]},
    {"name": "dateRestrict$string$8", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$8"]},
    {"name": "dateRestrict$string$9", "symbols": [{"literal":"E"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$9"]},
    {"name": "dateRestrict$string$10", "symbols": [{"literal":"B"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$10"]},
    {"name": "calendar$string$1", "symbols": [{"literal":"G"}, {"literal":"R"}, {"literal":"E"}, {"literal":"G"}, {"literal":"O"}, {"literal":"R"}, {"literal":"I"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$1"]},
    {"name": "calendar$string$2", "symbols": [{"literal":"J"}, {"literal":"U"}, {"literal":"L"}, {"literal":"I"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$2"]},
    {"name": "calendar$string$3", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"E"}, {"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"_"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$3"]},
    {"name": "calendar$string$4", "symbols": [{"literal":"H"}, {"literal":"E"}, {"literal":"B"}, {"literal":"R"}, {"literal":"E"}, {"literal":"W"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$4"]},
    {"name": "calendar", "symbols": ["extTag"]},
    {"name": "day", "symbols": ["Integer"]},
    {"name": "year", "symbols": ["Integer"]},
    {"name": "month", "symbols": ["stdTag"]},
    {"name": "month", "symbols": ["extTag"]},
    {"name": "epoch$string$1", "symbols": [{"literal":"B"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "epoch", "symbols": ["epoch$string$1"]},
    {"name": "epoch", "symbols": ["extTag"]},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [{"literal":"."}, "fraction"]},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$1$subexpression$1", "symbols": [{"literal":":"}, "second", "Time$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "Time$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$2$subexpression$1", "symbols": [{"literal":"Z"}]},
    {"name": "Time$ebnf$2", "symbols": ["Time$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time", "symbols": ["hour", {"literal":":"}, "minute", "Time$ebnf$1", "Time$ebnf$2"]},
    {"name": "hour", "symbols": ["digit"]},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "hour", "symbols": ["hour$subexpression$1", "digit"]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"1"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"2"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"3"}]},
    {"name": "hour", "symbols": [{"literal":"2"}, "hour$subexpression$2"]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "minute", "symbols": ["minute$subexpression$1", "digit"]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "second", "symbols": ["second$subexpression$1", "digit"]},
    {"name": "fraction$ebnf$1", "symbols": ["digit"]},
    {"name": "fraction$ebnf$1", "symbols": ["fraction$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "fraction", "symbols": ["fraction$ebnf$1"]},
    {"name": "Age$ebnf$1$subexpression$1", "symbols": ["ageBound", "D"]},
    {"name": "Age$ebnf$1", "symbols": ["Age$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Age$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Age", "symbols": ["Age$ebnf$1", "ageDuration"]},
    {"name": "ageBound", "symbols": [{"literal":"<"}]},
    {"name": "ageBound", "symbols": [{"literal":">"}]},
    {"name": "years", "symbols": ["Integer", {"literal":"y"}]},
    {"name": "months", "symbols": ["Integer", {"literal":"m"}]},
    {"name": "weeks", "symbols": ["Integer", {"literal":"w"}]},
    {"name": "days", "symbols": ["Integer", {"literal":"d"}]},
    {"name": "ageDuration$ebnf$1$subexpression$1", "symbols": ["D", "months"]},
    {"name": "ageDuration$ebnf$1", "symbols": ["ageDuration$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$2$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$2", "symbols": ["ageDuration$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$3$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$3", "symbols": ["ageDuration$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["years", "ageDuration$ebnf$1", "ageDuration$ebnf$2", "ageDuration$ebnf$3"]},
    {"name": "ageDuration$ebnf$4$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$4", "symbols": ["ageDuration$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$5$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$5", "symbols": ["ageDuration$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["months", "ageDuration$ebnf$4", "ageDuration$ebnf$5"]},
    {"name": "ageDuration$ebnf$6$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$6", "symbols": ["ageDuration$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["weeks", "ageDuration$ebnf$6"]},
    {"name": "ageDuration", "symbols": ["days"]},
    {"name": "list$ebnf$1", "symbols": []},
    {"name": "list$ebnf$1$subexpression$1", "symbols": ["listDelim", "listItem"]},
    {"name": "list$ebnf$1", "symbols": ["list$ebnf$1", "list$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "list", "symbols": ["listItem", "list$ebnf$1"]},
    {"name": "listItem$ebnf$1$subexpression$1", "symbols": ["nocommasp"]},
    {"name": "listItem$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "listItem$ebnf$1$subexpression$1$ebnf$1", "symbols": ["listItem$ebnf$1$subexpression$1$ebnf$1", "nocomma"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listItem$ebnf$1$subexpression$1", "symbols": ["nocommasp", "listItem$ebnf$1$subexpression$1$ebnf$1", "nocommasp"]},
    {"name": "listItem$ebnf$1", "symbols": ["listItem$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "listItem$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "listItem", "symbols": ["listItem$ebnf$1"]},
    {"name": "listDelim$ebnf$1", "symbols": []},
    {"name": "listDelim$ebnf$1", "symbols": ["listDelim$ebnf$1", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listDelim$ebnf$2", "symbols": []},
    {"name": "listDelim$ebnf$2", "symbols": ["listDelim$ebnf$2", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listDelim", "symbols": ["listDelim$ebnf$1", {"literal":","}, "listDelim$ebnf$2"]},
    {"name": "nocomma", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x2C]/]},
    {"name": "nocommasp", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x2C\x1E-\x20]/]},
    {"name": "List_Text", "symbols": ["list"]},
    {"name": "List_Enum$ebnf$1", "symbols": []},
    {"name": "List_Enum$ebnf$1$subexpression$1", "symbols": ["listDelim", "Enum"]},
    {"name": "List_Enum$ebnf$1", "symbols": ["List_Enum$ebnf$1", "List_Enum$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "List_Enum", "symbols": ["Enum", "List_Enum$ebnf$1"]},
    {"name": "PersonalName", "symbols": ["nameStr"]},
    {"name": "PersonalName$ebnf$1", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$2", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$3", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName", "symbols": ["PersonalName$ebnf$1", {"literal":"/"}, "PersonalName$ebnf$2", {"literal":"/"}, "PersonalName$ebnf$3"]},
    {"name": "nameChar", "symbols": [/[^\x00-\x19\x2F]/]},
    {"name": "nameStr$ebnf$1", "symbols": ["nameChar"]},
    {"name": "nameStr$ebnf$1", "symbols": ["nameStr$ebnf$1", "nameChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "nameStr", "symbols": ["nameStr$ebnf$1"]},
    {"name": "LangTag$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "script"]},
    {"name": "LangTag$ebnf$1", "symbols": ["LangTag$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "region"]},
    {"name": "LangTag$ebnf$2", "symbols": ["LangTag$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag$ebnf$3", "symbols": []},
    {"name": "LangTag$ebnf$3$subexpression$1", "symbols": [{"literal":"-"}, "variant"]},
    {"name": "LangTag$ebnf$3", "symbols": ["LangTag$ebnf$3", "LangTag$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "LangTag$ebnf$4", "symbols": []},
    {"name": "LangTag$ebnf$4$subexpression$1", "symbols": [{"literal":"-"}, "extension"]},
    {"name": "LangTag$ebnf$4", "symbols": ["LangTag$ebnf$4", "LangTag$ebnf$4$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "LangTag$ebnf$5$subexpression$1", "symbols": [{"literal":"-"}, "privateuse"]},
    {"name": "LangTag$ebnf$5", "symbols": ["LangTag$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag", "symbols": ["language", "LangTag$ebnf$1", "LangTag$ebnf$2", "LangTag$ebnf$3", "LangTag$ebnf$4", "LangTag$ebnf$5"]},
    {"name": "language$ebnf$1", "symbols": ["alpha"], "postprocess": id},
    {"name": "language$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "extlang"]},
    {"name": "language$ebnf$2", "symbols": ["language$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language", "symbols": ["alpha", "alpha", "language$ebnf$1", "language$ebnf$2"]},
    {"name": "language", "symbols": ["alpha", "alpha", "alpha", "alpha"]},
    {"name": "language$ebnf$3$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$3", "symbols": ["language$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$4$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$4", "symbols": ["language$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$5$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$5", "symbols": ["language$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language", "symbols": ["alpha", "alpha", "alpha", "alpha", "alpha", "language$ebnf$3", "language$ebnf$4", "language$ebnf$5"]},
    {"name": "extlang$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$1", "symbols": ["extlang$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$2", "symbols": ["extlang$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang", "symbols": ["alpha", "alpha", "alpha", "extlang$ebnf$1", "extlang$ebnf$2"]},
    {"name": "script", "symbols": ["alpha", "alpha", "alpha", "alpha"]},
    {"name": "region", "symbols": ["alpha", "alpha"]},
    {"name": "region", "symbols": ["digit", "digit", "digit"]},
    {"name": "variant", "symbols": ["digit", "alphanum", "alphanum", "alphanum"]},
    {"name": "variant$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$1", "symbols": ["variant$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$2", "symbols": ["variant$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$3", "symbols": ["variant$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant", "symbols": ["alphanum", "alphanum", "alphanum", "alphanum", "alphanum", "variant$ebnf$1", "variant$ebnf$2", "variant$ebnf$3"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$1$ebnf$1", "extension$ebnf$1$subexpression$1$ebnf$2", "extension$ebnf$1$subexpression$1$ebnf$3", "extension$ebnf$1$subexpression$1$ebnf$4", "extension$ebnf$1$subexpression$1$ebnf$5", "extension$ebnf$1$subexpression$1$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$2$ebnf$1", "extension$ebnf$1$subexpression$2$ebnf$2", "extension$ebnf$1$subexpression$2$ebnf$3", "extension$ebnf$1$subexpression$2$ebnf$4", "extension$ebnf$1$subexpression$2$ebnf$5", "extension$ebnf$1$subexpression$2$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1", "extension$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extension", "symbols": ["singleton", "extension$ebnf$1"]},
    {"name": "singleton", "symbols": ["digit"]},
    {"name": "singleton", "symbols": [/[\x41-\x57\x59-\x5A\x61-\x77\x79-\x7A]/]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$1$ebnf$1", "privateuse$ebnf$1$subexpression$1$ebnf$2", "privateuse$ebnf$1$subexpression$1$ebnf$3", "privateuse$ebnf$1$subexpression$1$ebnf$4", "privateuse$ebnf$1$subexpression$1$ebnf$5", "privateuse$ebnf$1$subexpression$1$ebnf$6", "privateuse$ebnf$1$subexpression$1$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$2$ebnf$1", "privateuse$ebnf$1$subexpression$2$ebnf$2", "privateuse$ebnf$1$subexpression$2$ebnf$3", "privateuse$ebnf$1$subexpression$2$ebnf$4", "privateuse$ebnf$1$subexpression$2$ebnf$5", "privateuse$ebnf$1$subexpression$2$ebnf$6", "privateuse$ebnf$1$subexpression$2$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1", "privateuse$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "privateuse", "symbols": [{"literal":"x"}, "privateuse$ebnf$1"]},
    {"name": "alpha", "symbols": [/[a-zA-z]/]},
    {"name": "alphanum", "symbols": ["alpha"]},
    {"name": "alphanum", "symbols": ["digit"]},
    {"name": "irregular$string$1", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"-"}, {"literal":"G"}, {"literal":"B"}, {"literal":"-"}, {"literal":"o"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$1"]},
    {"name": "irregular$string$2", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"a"}, {"literal":"m"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$2"]},
    {"name": "irregular$string$3", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"b"}, {"literal":"n"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$3"]},
    {"name": "irregular$string$4", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$4"]},
    {"name": "irregular$string$5", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"e"}, {"literal":"n"}, {"literal":"o"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$5"]},
    {"name": "irregular$string$6", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"h"}, {"literal":"a"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$6"]},
    {"name": "irregular$string$7", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"k"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$7"]},
    {"name": "irregular$string$8", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"l"}, {"literal":"u"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$8"]},
    {"name": "irregular$string$9", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$9"]},
    {"name": "irregular$string$10", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"n"}, {"literal":"a"}, {"literal":"v"}, {"literal":"a"}, {"literal":"j"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$10"]},
    {"name": "irregular$string$11", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"p"}, {"literal":"w"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$11"]},
    {"name": "irregular$string$12", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"a"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$12"]},
    {"name": "irregular$string$13", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$13"]},
    {"name": "irregular$string$14", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"s"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$14"]},
    {"name": "irregular$string$15", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"B"}, {"literal":"E"}, {"literal":"-"}, {"literal":"F"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$15"]},
    {"name": "irregular$string$16", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"B"}, {"literal":"E"}, {"literal":"-"}, {"literal":"N"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$16"]},
    {"name": "irregular$string$17", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"C"}, {"literal":"H"}, {"literal":"-"}, {"literal":"D"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$17"]},
    {"name": "regular$string$1", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"-"}, {"literal":"l"}, {"literal":"o"}, {"literal":"j"}, {"literal":"b"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$1"]},
    {"name": "regular$string$2", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"l"}, {"literal":"-"}, {"literal":"g"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$2"]},
    {"name": "regular$string$3", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"-"}, {"literal":"b"}, {"literal":"o"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$3"]},
    {"name": "regular$string$4", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"-"}, {"literal":"n"}, {"literal":"y"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$4"]},
    {"name": "regular$string$5", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"g"}, {"literal":"u"}, {"literal":"o"}, {"literal":"y"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$5"]},
    {"name": "regular$string$6", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"h"}, {"literal":"a"}, {"literal":"k"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$6"]},
    {"name": "regular$string$7", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$7"]},
    {"name": "regular$string$8", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"-"}, {"literal":"n"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$8"]},
    {"name": "regular$string$9", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"x"}, {"literal":"i"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$9"]},
    {"name": "grandfathered", "symbols": ["irregular"]},
    {"name": "grandfathered", "symbols": ["regular"]},
    {"name": "MediaType$ebnf$1", "symbols": []},
    {"name": "MediaType$ebnf$1$subexpression$1", "symbols": [{"literal":";"}, "mt_parameter"]},
    {"name": "MediaType$ebnf$1", "symbols": ["MediaType$ebnf$1", "MediaType$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "MediaType", "symbols": ["mt_type", {"literal":"/"}, "mt_subtype", "MediaType$ebnf$1"]},
    {"name": "mt_type", "symbols": ["mt_token"]},
    {"name": "mt_subtype", "symbols": ["mt_token"]},
    {"name": "mt_parameter", "symbols": ["mt_attribute", {"literal":"="}, "mt_value"]},
    {"name": "mt_token$ebnf$1$subexpression$1", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1$subexpression$1"]},
    {"name": "mt_token$ebnf$1$subexpression$2", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1", "mt_token$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_token", "symbols": ["mt_token$ebnf$1"]},
    {"name": "mt_attribute", "symbols": ["mt_token"]},
    {"name": "mt_value", "symbols": ["mt_token"]},
    {"name": "mt_value", "symbols": ["mt_qstring"]},
    {"name": "mt_char", "symbols": [/[\x20-\x21]/]},
    {"name": "mt_char", "symbols": [/[\x23-\x27]/]},
    {"name": "mt_char", "symbols": [/[\x2A-\x2B]/]},
    {"name": "mt_char", "symbols": [/[\x2D-\x2E]/]},
    {"name": "mt_char", "symbols": [/[\x30-\x39]/]},
    {"name": "mt_char", "symbols": [/[\x41-\x5A]/]},
    {"name": "mt_char", "symbols": [/[\x5E-\x7E]/]},
    {"name": "mt_qstring$ebnf$1", "symbols": []},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qtext"]},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qpair"]},
    {"name": "mt_qstring$ebnf$1", "symbols": ["mt_qstring$ebnf$1", "mt_qstring$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_qstring", "symbols": [/[\x22]/, "mt_qstring$ebnf$1", /[\x22]/]},
    {"name": "mt_qtext", "symbols": [/[\x09-\x0A]/]},
    {"name": "mt_qtext", "symbols": [/[\x20-\x21]/]},
    {"name": "mt_qtext", "symbols": [/[\x23-\x5B]/]},
    {"name": "mt_qtext", "symbols": [/[\x5D-\x7E]/]},
    {"name": "mt_qpair", "symbols": [{"literal":"\\"}, /[\x09-7E]/]},
    {"name": "Special", "symbols": ["Text"]},
    {"name": "NullOrY$ebnf$1", "symbols": [{"literal":"Y"}], "postprocess": id},
    {"name": "NullOrY$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "NullOrY", "symbols": ["NullOrY$ebnf$1"]},
    {"name": "AGE$string$1", "symbols": [{"literal":"A"}, {"literal":"G"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGE", "symbols": ["Level", "D", "AGE$string$1", "D", "Age"]},
    {"name": "AGE", "symbols": ["AGE", "newLine", "PHRASE"]},
    {"name": "PHRASE$string$1", "symbols": [{"literal":"P"}, {"literal":"H"}, {"literal":"R"}, {"literal":"A"}, {"literal":"S"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PHRASE", "symbols": ["Level", "D", "PHRASE$string$1", "D", "Text"]},
    {"name": "TYPE$string$1", "symbols": [{"literal":"T"}, {"literal":"Y"}, {"literal":"P"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["Level", "D", "TYPE$string$1", "D", "Text"]},
    {"name": "TIME$string$1", "symbols": [{"literal":"T"}, {"literal":"I"}, {"literal":"M"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["Level", "D", "TIME$string$1", "D", "Time"]},
    {"name": "DATE$string$1", "symbols": [{"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE", "symbols": ["Level", "D", "DATE$string$1", "D", "DateValue"]},
    {"name": "DATE$ebnf$1", "symbols": ["TIME"], "postprocess": id},
    {"name": "DATE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE$ebnf$2", "symbols": ["PHRASE"], "postprocess": id},
    {"name": "DATE$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE", "symbols": ["DATE", "newLine", "DATE$ebnf$1", "DATE$ebnf$2"]},
    {"name": "DATE$ebnf$3", "symbols": ["PHRASE"], "postprocess": id},
    {"name": "DATE$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE$ebnf$4", "symbols": ["TIME"], "postprocess": id},
    {"name": "DATE$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE", "symbols": ["DATE", "newLine", "DATE$ebnf$3", "DATE$ebnf$4"]},
    {"name": "DATE_EXACT$string$1", "symbols": [{"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATE_EXACT", "symbols": ["Level", "D", "DATE_EXACT$string$1", "D", "DateExact"]},
    {"name": "DATE_EXACT", "symbols": ["DATE", "newLine", "TIME"]},
    {"name": "DATEPERIOD$string$1", "symbols": [{"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATEPERIOD", "symbols": ["Level", "D", "DATEPERIOD$string$1", "D", "DatePeriod"]},
    {"name": "DATEPERIOD", "symbols": ["DATEPERIOD", "newLine", "PHRASE"]},
    {"name": "TEXT$string$1", "symbols": [{"literal":"T"}, {"literal":"E"}, {"literal":"X"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEXT", "symbols": ["Level", "D", "TEXT$string$1", "D", "Text"]},
    {"name": "TEXT$string$2", "symbols": [{"literal":"M"}, {"literal":"I"}, {"literal":"M"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEXT", "symbols": ["TEXT", "newLine", "Level", "D", "TEXT$string$2", "MediaType"]},
    {"name": "TEXT$string$3", "symbols": [{"literal":"L"}, {"literal":"A"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEXT", "symbols": ["TEXT", "newLine", "Level", "D", "TEXT$string$3", "language"]},
    {"name": "QUAY$string$1", "symbols": [{"literal":"Q"}, {"literal":"U"}, {"literal":"A"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUAY$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "QUAY$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "QUAY$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "QUAY$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "QUAY", "symbols": ["Level", "D", "QUAY$string$1", "D", "QUAY$subexpression$1"]},
    {"name": "CROP$string$1", "symbols": [{"literal":"C"}, {"literal":"R"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CROP", "symbols": ["Level", "D", "CROP$string$1", "D"]},
    {"name": "CROP$string$2", "symbols": [{"literal":"T"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CROP", "symbols": ["CROP", "newLine", "Level", "D", "CROP$string$2", "D", "Integer"]},
    {"name": "CROP$string$3", "symbols": [{"literal":"L"}, {"literal":"E"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CROP", "symbols": ["CROP", "newLine", "Level", "D", "CROP$string$3", "D", "Integer"]},
    {"name": "CROP$string$4", "symbols": [{"literal":"H"}, {"literal":"E"}, {"literal":"I"}, {"literal":"G"}, {"literal":"H"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CROP", "symbols": ["CROP", "newLine", "Level", "D", "CROP$string$4", "D", "Integer"]},
    {"name": "CROP$string$5", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"D"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CROP", "symbols": ["CROP", "newLine", "Level", "D", "CROP$string$5", "D", "Integer"]},
    {"name": "EVENT_DETAIL", "symbols": ["DATE"]},
    {"name": "NAME_PIECES", "symbols": ["Level", "D", "NAME_PIECES_ENUM", "D", "Text"]},
    {"name": "NON_EVENT_STRUCTURE$string$1", "symbols": [{"literal":"N"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NON_EVENT_STRUCTURE", "symbols": ["Level", "D", "NON_EVENT_STRUCTURE$string$1", "D", "EVENTS"]},
    {"name": "NON_EVENT_STRUCTURE", "symbols": ["NON_EVENT_STRUCTURE", "newLine", "DATEPERIOD"]},
    {"name": "NON_EVENT_STRUCTURE", "symbols": ["NON_EVENT_STRUCTURE", "newLine", "NOTE_STRUCTURE"]},
    {"name": "NON_EVENT_STRUCTURE", "symbols": ["NON_EVENT_STRUCTURE", "newLine", "SOURCE_CITATION"]},
    {"name": "NOTE_STRUCTURE$subexpression$1$string$1", "symbols": [{"literal":"N"}, {"literal":"O"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["Level", "D", "NOTE_STRUCTURE$subexpression$1$string$1", "D", "Text"]},
    {"name": "NOTE_STRUCTURE$subexpression$1$string$2", "symbols": [{"literal":"M"}, {"literal":"I"}, {"literal":"M"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["NOTE_STRUCTURE", "newLine", "Level", "D", "NOTE_STRUCTURE$subexpression$1$string$2", "D", "MediaType"]},
    {"name": "NOTE_STRUCTURE$subexpression$1$string$3", "symbols": [{"literal":"L"}, {"literal":"A"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["NOTE_STRUCTURE", "newLine", "Level", "D", "NOTE_STRUCTURE$subexpression$1$string$3", "D", "language"]},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["NOTE_STRUCTURE", "newLine", "NOTE_TRAN"]},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["NOTE_STRUCTURE", "newLine", "SOURCE_CITATION"]},
    {"name": "NOTE_STRUCTURE", "symbols": ["NOTE_STRUCTURE$subexpression$1"]},
    {"name": "NOTE_STRUCTURE$string$1", "symbols": [{"literal":"S"}, {"literal":"N"}, {"literal":"O"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTE_STRUCTURE", "symbols": ["Level", "D", "NOTE_STRUCTURE$string$1", "D", "Xref"]},
    {"name": "NOTE_TRAN$string$1", "symbols": [{"literal":"T"}, {"literal":"R"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTE_TRAN", "symbols": ["Level", "D", "NOTE_TRAN$string$1", "D", "Text"]},
    {"name": "NOTE_TRAN$string$2", "symbols": [{"literal":"M"}, {"literal":"I"}, {"literal":"M"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTE_TRAN", "symbols": ["NOTE_TRAN", "newLine", "Level", "D", "NOTE_TRAN$string$2", "D", "MediaType"]},
    {"name": "NOTE_TRAN$string$3", "symbols": [{"literal":"L"}, {"literal":"A"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTE_TRAN", "symbols": ["NOTE_TRAN", "newLine", "Level", "D", "NOTE_TRAN$string$3", "D", "language"]},
    {"name": "SOURCE_CITATION$string$1", "symbols": [{"literal":"S"}, {"literal":"O"}, {"literal":"U"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SOURCE_CITATION", "symbols": ["Level", "D", "SOURCE_CITATION$string$1", "D", "Xref"]},
    {"name": "SOURCE_CITATION$string$2", "symbols": [{"literal":"P"}, {"literal":"A"}, {"literal":"G"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "newLine", "Level", "D", "SOURCE_CITATION$string$2", "D", "Text"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "newLine", "SOUR_DATA"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "newLine", "SOUR_EVEN"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "newLine", "QUAY"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "newLine", "MULTIMEDIA_LINK"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "newLine", "NOTE_STRUCTURE"]},
    {"name": "SOUR_DATA$string$1", "symbols": [{"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SOUR_DATA", "symbols": ["Level", "D", "SOUR_DATA$string$1"]},
    {"name": "SOUR_DATA", "symbols": ["SOUR_DATA", "newLine", "DATE"]},
    {"name": "SOUR_DATA", "symbols": ["SOUR_DATA", "newLine", "TEXT"]},
    {"name": "SOUR_EVEN$string$1", "symbols": [{"literal":"E"}, {"literal":"V"}, {"literal":"E"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SOUR_EVEN$subexpression$1", "symbols": ["ATTRIBUTES"]},
    {"name": "SOUR_EVEN$subexpression$1", "symbols": ["EVENTS"]},
    {"name": "SOUR_EVEN", "symbols": ["Level", "D", "SOUR_EVEN$string$1", "SOUR_EVEN$subexpression$1"]},
    {"name": "SOUR_EVEN", "symbols": ["SOUR_EVEN", "newLine", "PHRASE"]},
    {"name": "SOUR_EVEN", "symbols": ["SOUR_EVEN", "newLine", "ROLE"]},
    {"name": "SOUR_EVEN", "symbols": ["SOUR_EVEN", "newLine", "ROLE", "newLine", "PHRASE"]},
    {"name": "MULTIMEDIA_LINK$string$1", "symbols": [{"literal":"O"}, {"literal":"B"}, {"literal":"J"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MULTIMEDIA_LINK", "symbols": ["Level", "D", "MULTIMEDIA_LINK$string$1", "D", "Xref"]},
    {"name": "MULTIMEDIA_LINK", "symbols": ["MULTIMEDIA_LINK", "newLine", "CROP"]},
    {"name": "MULTIMEDIA_LINK$string$2", "symbols": [{"literal":"T"}, {"literal":"I"}, {"literal":"T"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MULTIMEDIA_LINK", "symbols": ["MULTIMEDIA_LINK", "newLine", "Level", "D", "MULTIMEDIA_LINK$string$2", "D", "Text"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["DATE"]},
    {"name": "LDS_ORDINANCE_DETAIL$string$1", "symbols": [{"literal":"T"}, {"literal":"E"}, {"literal":"M"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["Level", "D", "LDS_ORDINANCE_DETAIL$string$1", "D", "Text"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["PLACE_STRUCTURE"]},
    {"name": "LDS_ORDINANCE_DETAIL$string$2", "symbols": [{"literal":"S"}, {"literal":"T"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["Level", "D", "LDS_ORDINANCE_DETAIL$string$2", "D", "FAMC_STAT_ENUM", "newLine", "DATE_EXACT"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["NOTE_STRUCTURE"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["SOURCE_CITATION"]},
    {"name": "PLACE_STRUCTURE$string$1", "symbols": [{"literal":"P"}, {"literal":"L"}, {"literal":"A"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE_STRUCTURE", "symbols": ["Level", "D", "PLACE_STRUCTURE$string$1", "D", "List_Text"]},
    {"name": "PLACE_STRUCTURE$string$2", "symbols": [{"literal":"F"}, {"literal":"O"}, {"literal":"R"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "newLine", "Level", "D", "PLACE_STRUCTURE$string$2", "D", "List_Text"]},
    {"name": "PLACE_STRUCTURE$string$3", "symbols": [{"literal":"L"}, {"literal":"A"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "newLine", "Level", "D", "PLACE_STRUCTURE$string$3", "D", "language"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "newLine", "PLAC_TRAN"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "newLine", "MAP"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "newLine", "EXID"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "newLine", "NOTE_STRUCTURE"]},
    {"name": "MAP$string$1", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAP", "symbols": ["Level", "D", "MAP$string$1"]},
    {"name": "MAP$string$2", "symbols": [{"literal":"L"}, {"literal":"A"}, {"literal":"T"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAP", "symbols": ["MAP", "newLine", "Level", "D", "MAP$string$2", "D", "Special"]},
    {"name": "MAP$string$3", "symbols": [{"literal":"L"}, {"literal":"O"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAP", "symbols": ["MAP", "newLine", "Level", "D", "MAP$string$3", "D", "Special"]},
    {"name": "EXID$string$1", "symbols": [{"literal":"E"}, {"literal":"X"}, {"literal":"I"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXID", "symbols": ["Level", "D", "EXID$string$1", "D", "Special"]},
    {"name": "EXID$string$2", "symbols": [{"literal":"T"}, {"literal":"Y"}, {"literal":"P"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXID", "symbols": ["EXID", "newLine", "Level", "D", "EXID$string$2", "D", "Special"]},
    {"name": "PLAC_TRAN$string$1", "symbols": [{"literal":"T"}, {"literal":"R"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLAC_TRAN", "symbols": ["Level", "D", "PLAC_TRAN$string$1", "D", "Text"]},
    {"name": "PLAC_TRAN$string$2", "symbols": [{"literal":"L"}, {"literal":"A"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLAC_TRAN", "symbols": ["PLAC_TRAN", "newLine", "Level", "D", "PLAC_TRAN$string$2", "D", "language"]},
    {"name": "FAMC_STAT$string$1", "symbols": [{"literal":"S"}, {"literal":"T"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMC_STAT", "symbols": ["Level", "D", "FAMC_STAT$string$1", "FAMC_STAT_ENUM"]},
    {"name": "PEDI$string$1", "symbols": [{"literal":"P"}, {"literal":"E"}, {"literal":"D"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI", "symbols": ["Level", "D", "PEDI$string$1", "D", "PEDI_ENUM"]},
    {"name": "PEDI", "symbols": ["PEDI", "newLine", "PHRASE"]},
    {"name": "FAMS$string$1", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"M"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMS", "symbols": ["Level", "D", "FAMS$string$1", "D", "Xref"]},
    {"name": "FAMS", "symbols": ["FAMS", "newLine", "NOTE_STRUCTURE"]},
    {"name": "ASSOCIATION_STRUCTURE$string$1", "symbols": [{"literal":"A"}, {"literal":"S"}, {"literal":"S"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["Level", "D", "ASSOCIATION_STRUCTURE$string$1", "D", "Xref"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["ASSOCIATION_STRUCTURE", "newLine", "PHRASE"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["ASSOCIATION_STRUCTURE", "newLine", "ROLE"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["ASSOCIATION_STRUCTURE", "newLine", "NOTE_STRUCTURE"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["ASSOCIATION_STRUCTURE", "newLine", "SOURCE_CITATION"]},
    {"name": "REFN$string$1", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"F"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REFN", "symbols": ["Level", "D", "REFN$string$1", "D", "Special"]},
    {"name": "REFN$string$2", "symbols": [{"literal":"T"}, {"literal":"Y"}, {"literal":"P"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REFN", "symbols": ["REFN", "newLine", "Level", "D", "REFN$string$2", "D", "Text"]},
    {"name": "UID$string$1", "symbols": [{"literal":"U"}, {"literal":"I"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UID", "symbols": ["Level", "D", "UID$string$1", "D", "Special"]},
    {"name": "IDENTIFIER_STRUCTURE", "symbols": ["REFN"]},
    {"name": "IDENTIFIER_STRUCTURE", "symbols": ["UID"]},
    {"name": "IDENTIFIER_STRUCTURE", "symbols": ["EXID"]},
    {"name": "CHANGE_DATE$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHANGE_DATE", "symbols": ["Level", "D", "CHANGE_DATE$string$1"]},
    {"name": "CHANGE_DATE", "symbols": ["CHANGE_DATE", "newLine", "DATE_EXACT"]},
    {"name": "CHANGE_DATE", "symbols": ["CHANGE_DATE", "newLine", "NOTE_STRUCTURE"]},
    {"name": "CREATION_DATE$string$1", "symbols": [{"literal":"C"}, {"literal":"R"}, {"literal":"E"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CREATION_DATE", "symbols": ["Level", "D", "CREATION_DATE$string$1"]},
    {"name": "CREATION_DATE", "symbols": ["CREATION_DATE", "newLine", "DATE_EXACT"]},
    {"name": "input$ebnf$1", "symbols": []},
    {"name": "input$ebnf$1", "symbols": ["input$ebnf$1", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input", "symbols": ["FAM", "input$ebnf$1"]},
    {"name": "input$ebnf$2", "symbols": []},
    {"name": "input$ebnf$2", "symbols": ["input$ebnf$2", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$3", "symbols": []},
    {"name": "input$ebnf$3$subexpression$1$ebnf$1", "symbols": []},
    {"name": "input$ebnf$3$subexpression$1$ebnf$1", "symbols": ["input$ebnf$3$subexpression$1$ebnf$1", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$3$subexpression$1", "symbols": ["newLine", "structure", "input$ebnf$3$subexpression$1$ebnf$1"]},
    {"name": "input$ebnf$3", "symbols": ["input$ebnf$3", "input$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input", "symbols": ["FAM", "input$ebnf$2", "input$ebnf$3"], "postprocess":  (d, l, reject) => {
        
            const subs = d[2].map((arr) => arr[1][0]);
            let husb_counter = 0;
            for(sub of subs) {
                if(sub.tag === 'HUSB') husb_counter += 1
            }
            if(husb_counter > 1) return reject;
            return {
                line: d[0],
                substructures: subs
            }
        }
        },
    {"name": "structure", "symbols": ["FAMILY_ATTRIBUTE_STRUCTURE"]},
    {"name": "structure", "symbols": ["FAM_HUSB"]},
    {"name": "structure", "symbols": ["FAM_WIFE"]},
    {"name": "structure", "symbols": ["CHIL"]},
    {"name": "structure", "symbols": ["TEST"]},
    {"name": "FAM$string$1", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAM", "symbols": [{"literal":"0"}, "D", "Xref", "D", "FAM$string$1"], "postprocess":  (data) => {
            return {
                level: data[0],
                Xref: data[2],
                tag: data[4]
            }
        }},
    {"name": "FAM_HUSB$string$1", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"S"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAM_HUSB", "symbols": [{"literal":"1"}, "D", "FAM_HUSB$string$1", "D", "Xref"], "postprocess":  (data) => {
            return {
                level: data[0],
                tag: data[2],
                xref: data[4]
            }
        }},
    {"name": "FAM_HUSB", "symbols": ["FAM_HUSB", "newLine", "PHRASE"]},
    {"name": "HUSB$string$1", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"S"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HUSB$string$2", "symbols": [{"literal":"A"}, {"literal":"G"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HUSB", "symbols": ["Level", "D", "HUSB$string$1", "newLine", "Level", "D", "HUSB$string$2", "D", "Age"]},
    {"name": "HUSB", "symbols": ["HUSB", "newLine", "PHRASE"]},
    {"name": "FAM_WIFE$string$1", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"F"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAM_WIFE", "symbols": [{"literal":"1"}, "D", "FAM_WIFE$string$1", "D", "Xref"]},
    {"name": "FAM_WIFE", "symbols": ["FAM_WIFE", "newLine", "PHRASE"]},
    {"name": "WIFE$string$1", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"F"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WIFE$string$2", "symbols": [{"literal":"A"}, {"literal":"G"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WIFE", "symbols": ["Level", "D", "WIFE$string$1", "newLine", "Level", "D", "WIFE$string$2", "D", "Age"]},
    {"name": "WIFE", "symbols": ["WIFE", "newLine", "PHRASE"]},
    {"name": "CHIL$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"I"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHIL", "symbols": [{"literal":"1"}, "D", "CHIL$string$1", "D", "Xref"]},
    {"name": "CHIL", "symbols": ["CHIL", "newLine", "PHRASE"]},
    {"name": "TEST$string$1", "symbols": [{"literal":"T"}, {"literal":"E"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEST", "symbols": ["Level", "D", "TEST$string$1", "D", "DateExact"]},
    {"name": "FAMILY_ATTRIBUTE_STRUCTURE", "symbols": ["NCHI"]},
    {"name": "FAMILY_ATTRIBUTE_STRUCTURE", "symbols": ["RESI"]},
    {"name": "FAMILY_ATTRIBUTE_STRUCTURE", "symbols": ["FACT"]},
    {"name": "NCHI$string$1", "symbols": [{"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NCHI", "symbols": ["Level", "D", "NCHI$string$1", "D", "Integer"]},
    {"name": "NCHI", "symbols": ["NCHI", "newLine", "TYPE"]},
    {"name": "RESI$string$1", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"S"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RESI", "symbols": ["Level", "D", "RESI$string$1", "D", "Text"]},
    {"name": "RESI", "symbols": ["RESI", "newLine", "TYPE"]},
    {"name": "FACT$string$1", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"C"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FACT", "symbols": ["Level", "D", "FACT$string$1", "D", "Text"]},
    {"name": "FACT", "symbols": ["FACT", "newLine", "TYPE"]},
    {"name": "FAMILY_EVENT_DETAIL", "symbols": ["HUSB"]},
    {"name": "FAMILY_EVENT_DETAIL", "symbols": ["WIFE"]},
    {"name": "FAMILY_EVENT_DETAIL", "symbols": ["EVENT_DETAIL"]}
]
  , ParserStart: "input"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
