// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

    // required modules

    // moo-lexer to pre-compile input
    const lexer = moo.compile({
        D : /[ ]/,
        digit      : /[0-9]/,
        underscore : /[_]/,
        Xref     : /\@[A-Z0-9\_]+\@/,
        EOL: {match: /(?:\r\n?|\n)/, lineBreaks: true },
        // not Banned, no EOL, no Space, no @, no _
        notBannedNoEOLNoSpace:  /[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x0A\x0D\x20\x40\x5F]+/
    });
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "RESN_ENUM$string$1", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"F"}, {"literal":"I"}, {"literal":"D"}, {"literal":"E"}, {"literal":"N"}, {"literal":"T"}, {"literal":"I"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RESN_ENUM", "symbols": ["RESN_ENUM$string$1"], "postprocess": id},
    {"name": "RESN_ENUM$string$2", "symbols": [{"literal":"L"}, {"literal":"O"}, {"literal":"C"}, {"literal":"K"}, {"literal":"E"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RESN_ENUM", "symbols": ["RESN_ENUM$string$2"], "postprocess": id},
    {"name": "RESN_ENUM$string$3", "symbols": [{"literal":"P"}, {"literal":"R"}, {"literal":"I"}, {"literal":"V"}, {"literal":"A"}, {"literal":"C"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RESN_ENUM", "symbols": ["RESN_ENUM$string$3"], "postprocess": id},
    {"name": "NAME_PIECES_ENUM$string$1", "symbols": [{"literal":"N"}, {"literal":"P"}, {"literal":"F"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$1"], "postprocess": id},
    {"name": "NAME_PIECES_ENUM$string$2", "symbols": [{"literal":"G"}, {"literal":"I"}, {"literal":"V"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$2"], "postprocess": id},
    {"name": "NAME_PIECES_ENUM$string$3", "symbols": [{"literal":"N"}, {"literal":"I"}, {"literal":"C"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$3"], "postprocess": id},
    {"name": "NAME_PIECES_ENUM$string$4", "symbols": [{"literal":"S"}, {"literal":"P"}, {"literal":"F"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$4"], "postprocess": id},
    {"name": "NAME_PIECES_ENUM$string$5", "symbols": [{"literal":"S"}, {"literal":"U"}, {"literal":"R"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$5"], "postprocess": id},
    {"name": "NAME_PIECES_ENUM$string$6", "symbols": [{"literal":"N"}, {"literal":"S"}, {"literal":"F"}, {"literal":"X"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME_PIECES_ENUM", "symbols": ["NAME_PIECES_ENUM$string$6"], "postprocess": id},
    {"name": "ROLE$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"I"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$1"], "postprocess": id},
    {"name": "ROLE$string$2", "symbols": [{"literal":"C"}, {"literal":"L"}, {"literal":"E"}, {"literal":"R"}, {"literal":"G"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$2"], "postprocess": id},
    {"name": "ROLE$string$3", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$3"], "postprocess": id},
    {"name": "ROLE$string$4", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"I"}, {"literal":"E"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$4"], "postprocess": id},
    {"name": "ROLE$string$5", "symbols": [{"literal":"G"}, {"literal":"O"}, {"literal":"D"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$5"], "postprocess": id},
    {"name": "ROLE$string$6", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"S"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$6"], "postprocess": id},
    {"name": "ROLE$string$7", "symbols": [{"literal":"M"}, {"literal":"O"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$7"], "postprocess": id},
    {"name": "ROLE$string$8", "symbols": [{"literal":"M"}, {"literal":"U"}, {"literal":"L"}, {"literal":"T"}, {"literal":"I"}, {"literal":"P"}, {"literal":"L"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$8"], "postprocess": id},
    {"name": "ROLE$string$9", "symbols": [{"literal":"N"}, {"literal":"G"}, {"literal":"H"}, {"literal":"B"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$9"], "postprocess": id},
    {"name": "ROLE$string$10", "symbols": [{"literal":"O"}, {"literal":"F"}, {"literal":"F"}, {"literal":"I"}, {"literal":"C"}, {"literal":"I"}, {"literal":"A"}, {"literal":"T"}, {"literal":"O"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$10"], "postprocess": id},
    {"name": "ROLE$string$11", "symbols": [{"literal":"S"}, {"literal":"P"}, {"literal":"O"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$11"], "postprocess": id},
    {"name": "ROLE$string$12", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"F"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$12"], "postprocess": id},
    {"name": "ROLE$string$13", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"T"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$13"], "postprocess": id},
    {"name": "ROLE$string$14", "symbols": [{"literal":"O"}, {"literal":"T"}, {"literal":"H"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ROLE", "symbols": ["ROLE$string$14"], "postprocess": id},
    {"name": "SEX_ENUM", "symbols": [{"literal":"M"}], "postprocess": id},
    {"name": "SEX_ENUM", "symbols": [{"literal":"F"}], "postprocess": id},
    {"name": "SEX_ENUM", "symbols": [{"literal":"X"}], "postprocess": id},
    {"name": "SEX_ENUM", "symbols": [{"literal":"U"}], "postprocess": id},
    {"name": "ADOP_ENUM$string$1", "symbols": [{"literal":"H"}, {"literal":"U"}, {"literal":"S"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADOP_ENUM", "symbols": ["ADOP_ENUM$string$1"], "postprocess": id},
    {"name": "ADOP_ENUM$string$2", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"F"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADOP_ENUM", "symbols": ["ADOP_ENUM$string$2"], "postprocess": id},
    {"name": "ADOP_ENUM$string$3", "symbols": [{"literal":"B"}, {"literal":"O"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADOP_ENUM", "symbols": ["ADOP_ENUM$string$3"], "postprocess": id},
    {"name": "EVENTS", "symbols": ["INDIVIDUAL_EVENTS"]},
    {"name": "EVENTS", "symbols": ["FAMILY_EVENTS"]},
    {"name": "INDIVIDUAL_EVENTS$string$1", "symbols": [{"literal":"A"}, {"literal":"D"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$1"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$2", "symbols": [{"literal":"B"}, {"literal":"A"}, {"literal":"P"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$2"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$3", "symbols": [{"literal":"B"}, {"literal":"A"}, {"literal":"R"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$3"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$4", "symbols": [{"literal":"B"}, {"literal":"A"}, {"literal":"S"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$4"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$5", "symbols": [{"literal":"B"}, {"literal":"I"}, {"literal":"R"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$5"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$6", "symbols": [{"literal":"B"}, {"literal":"L"}, {"literal":"E"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$6"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$7", "symbols": [{"literal":"B"}, {"literal":"U"}, {"literal":"R"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$7"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$8", "symbols": [{"literal":"C"}, {"literal":"E"}, {"literal":"N"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$8"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$9", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$9"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$10", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"R"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$10"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$11", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$11"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$12", "symbols": [{"literal":"C"}, {"literal":"R"}, {"literal":"E"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$12"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$13", "symbols": [{"literal":"D"}, {"literal":"E"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$13"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$14", "symbols": [{"literal":"E"}, {"literal":"M"}, {"literal":"I"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$14"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$15", "symbols": [{"literal":"F"}, {"literal":"C"}, {"literal":"O"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$15"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$16", "symbols": [{"literal":"G"}, {"literal":"R"}, {"literal":"A"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$16"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$17", "symbols": [{"literal":"I"}, {"literal":"M"}, {"literal":"M"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$17"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$18", "symbols": [{"literal":"N"}, {"literal":"A"}, {"literal":"T"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$18"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$19", "symbols": [{"literal":"O"}, {"literal":"R"}, {"literal":"D"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$19"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$20", "symbols": [{"literal":"P"}, {"literal":"R"}, {"literal":"O"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$20"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$21", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"T"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$21"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENTS$string$22", "symbols": [{"literal":"W"}, {"literal":"I"}, {"literal":"L"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_EVENTS", "symbols": ["INDIVIDUAL_EVENTS$string$22"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$1", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"U"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$1"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$2", "symbols": [{"literal":"C"}, {"literal":"E"}, {"literal":"N"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$2"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$3", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"V"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$3"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$4", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"V"}, {"literal":"F"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$4"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$5", "symbols": [{"literal":"E"}, {"literal":"N"}, {"literal":"G"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$5"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$6", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"R"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$6"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$7", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"R"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$7"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$8", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"R"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$8"], "postprocess": id},
    {"name": "FAMILY_EVENTS$string$9", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"R"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_EVENTS", "symbols": ["FAMILY_EVENTS$string$9"], "postprocess": id},
    {"name": "ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES"], "postprocess": id},
    {"name": "ATTRIBUTES", "symbols": ["FAMILY_ATTRIBUTES"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$1", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$1"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$2", "symbols": [{"literal":"D"}, {"literal":"S"}, {"literal":"C"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$2"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$3", "symbols": [{"literal":"E"}, {"literal":"D"}, {"literal":"U"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$3"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$4", "symbols": [{"literal":"I"}, {"literal":"D"}, {"literal":"N"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$4"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$5", "symbols": [{"literal":"N"}, {"literal":"A"}, {"literal":"T"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$5"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$6", "symbols": [{"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$6"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$7", "symbols": [{"literal":"N"}, {"literal":"M"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$7"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$8", "symbols": [{"literal":"O"}, {"literal":"C"}, {"literal":"C"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$8"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$9", "symbols": [{"literal":"P"}, {"literal":"R"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$9"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$10", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"L"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$10"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$11", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"S"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$11"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$12", "symbols": [{"literal":"S"}, {"literal":"S"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$12"], "postprocess": id},
    {"name": "INDIVIDUAL_ATTRIBUTES$string$13", "symbols": [{"literal":"T"}, {"literal":"I"}, {"literal":"T"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INDIVIDUAL_ATTRIBUTES", "symbols": ["INDIVIDUAL_ATTRIBUTES$string$13"], "postprocess": id},
    {"name": "FAMILY_ATTRIBUTES$string$1", "symbols": [{"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_ATTRIBUTES", "symbols": ["FAMILY_ATTRIBUTES$string$1"], "postprocess": id},
    {"name": "FAMILY_ATTRIBUTES$string$2", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"S"}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY_ATTRIBUTES", "symbols": ["FAMILY_ATTRIBUTES$string$2"], "postprocess": id},
    {"name": "FAMC_STAT_ENUM$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"A"}, {"literal":"L"}, {"literal":"L"}, {"literal":"E"}, {"literal":"N"}, {"literal":"G"}, {"literal":"E"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMC_STAT_ENUM", "symbols": ["FAMC_STAT_ENUM$string$1"], "postprocess": id},
    {"name": "FAMC_STAT_ENUM$string$2", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"S"}, {"literal":"P"}, {"literal":"R"}, {"literal":"O"}, {"literal":"V"}, {"literal":"E"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMC_STAT_ENUM", "symbols": ["FAMC_STAT_ENUM$string$2"], "postprocess": id},
    {"name": "FAMC_STAT_ENUM$string$3", "symbols": [{"literal":"P"}, {"literal":"R"}, {"literal":"O"}, {"literal":"V"}, {"literal":"E"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMC_STAT_ENUM", "symbols": ["FAMC_STAT_ENUM$string$3"], "postprocess": id},
    {"name": "PEDI_ENUM$string$1", "symbols": [{"literal":"A"}, {"literal":"D"}, {"literal":"O"}, {"literal":"P"}, {"literal":"T"}, {"literal":"E"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$1"], "postprocess": id},
    {"name": "PEDI_ENUM$string$2", "symbols": [{"literal":"B"}, {"literal":"I"}, {"literal":"R"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$2"], "postprocess": id},
    {"name": "PEDI_ENUM$string$3", "symbols": [{"literal":"F"}, {"literal":"O"}, {"literal":"S"}, {"literal":"T"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$3"], "postprocess": id},
    {"name": "PEDI_ENUM$string$4", "symbols": [{"literal":"S"}, {"literal":"E"}, {"literal":"A"}, {"literal":"L"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$4"], "postprocess": id},
    {"name": "PEDI_ENUM$string$5", "symbols": [{"literal":"O"}, {"literal":"T"}, {"literal":"H"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PEDI_ENUM", "symbols": ["PEDI_ENUM$string$5"], "postprocess": id},
    {"name": "Level", "symbols": [{"literal":"0"}], "postprocess": id},
    {"name": "Level$ebnf$1", "symbols": []},
    {"name": "Level$ebnf$1", "symbols": ["Level$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Level", "symbols": ["nonzero", "Level$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "D", "symbols": [/[ ]/], "postprocess": id},
    {"name": "Xref$ebnf$1", "symbols": ["tagChar"]},
    {"name": "Xref$ebnf$1", "symbols": ["Xref$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Xref", "symbols": ["atsign", "Xref$ebnf$1", "atsign"], "postprocess": functions.joinAndUnpackAll},
    {"name": "Tag", "symbols": ["stdTag"], "postprocess": id},
    {"name": "Tag", "symbols": ["extTag"], "postprocess": id},
    {"name": "LineVal", "symbols": ["pointer"], "postprocess": id},
    {"name": "LineVal", "symbols": ["lineStr"], "postprocess": id},
    {"name": "EOL", "symbols": [/[\x0A]/], "postprocess": id},
    {"name": "stdTag$ebnf$1", "symbols": []},
    {"name": "stdTag$ebnf$1", "symbols": ["stdTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "stdTag", "symbols": ["ucletter", "stdTag$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "extTag$ebnf$1", "symbols": ["tagChar"]},
    {"name": "extTag$ebnf$1", "symbols": ["extTag$ebnf$1", "tagChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extTag", "symbols": ["underscore", "extTag$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "tagChar", "symbols": ["ucletter"], "postprocess": id},
    {"name": "tagChar", "symbols": ["digit"], "postprocess": id},
    {"name": "tagChar", "symbols": ["underscore"], "postprocess": id},
    {"name": "pointer", "symbols": ["voidPrt"], "postprocess": id},
    {"name": "pointer", "symbols": ["Xref"], "postprocess": id},
    {"name": "voidPrt$string$1", "symbols": [{"literal":"@"}, {"literal":"V"}, {"literal":"O"}, {"literal":"I"}, {"literal":"D"}, {"literal":"@"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "voidPrt", "symbols": ["voidPrt$string$1"], "postprocess": id},
    {"name": "nonAt", "symbols": [/[^@\n]/], "postprocess": id},
    {"name": "nonEOL", "symbols": [/[^\n]/], "postprocess": id},
    {"name": "lineStr$ebnf$1", "symbols": []},
    {"name": "lineStr$ebnf$1", "symbols": ["lineStr$ebnf$1", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["nonAt", "lineStr$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "lineStr$ebnf$2", "symbols": []},
    {"name": "lineStr$ebnf$2", "symbols": ["lineStr$ebnf$2", "nonEOL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lineStr", "symbols": ["atsign", "atsign", "lineStr$ebnf$2"], "postprocess": functions.joinAndUnpackAll},
    {"name": "digit", "symbols": [/[0-9]/], "postprocess": id},
    {"name": "nonzero", "symbols": [/[1-9]/], "postprocess": id},
    {"name": "ucletter", "symbols": [/[A-Z]/], "postprocess": id},
    {"name": "underscore", "symbols": [{"literal":"_"}], "postprocess": id},
    {"name": "atsign", "symbols": [{"literal":"@"}], "postprocess": id},
    {"name": "banned", "symbols": [/[\x00-\x08]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x0B-\x0C]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x0E-\x1F]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x7F]/], "postprocess": id},
    {"name": "banned", "symbols": [/[\x80-\x9F]/], "postprocess": id},
    {"name": "notBanned", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F]/], "postprocess": id},
    {"name": "notBannedNoEOL", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x0A\x0D]/], "postprocess": id},
    {"name": "anychar", "symbols": ["notBannedNoEOL"], "postprocess": id},
    {"name": "Text$ebnf$1", "symbols": []},
    {"name": "Text$ebnf$1", "symbols": ["Text$ebnf$1", "anychar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Text", "symbols": ["Text$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "Integer$ebnf$1", "symbols": ["digit"]},
    {"name": "Integer$ebnf$1", "symbols": ["Integer$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "Integer", "symbols": ["Integer$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "stdEnum", "symbols": ["stdTag"], "postprocess": id},
    {"name": "stdEnum", "symbols": ["Integer"], "postprocess": id},
    {"name": "Enum", "symbols": ["stdEnum"], "postprocess": id},
    {"name": "Enum", "symbols": ["extTag"], "postprocess": id},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["date"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["DatePeriod"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateRange"]},
    {"name": "DateValue$ebnf$1$subexpression$1", "symbols": ["dateApprox"]},
    {"name": "DateValue$ebnf$1", "symbols": ["DateValue$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DateValue$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DateValue", "symbols": ["DateValue$ebnf$1"], "postprocess": id},
    {"name": "DateExact", "symbols": ["day", "D", "month", "D", "year"], "postprocess": functions.joinAndUnpackAll},
    {"name": "DatePeriod$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$1$subexpression$1", "symbols": ["DatePeriod$ebnf$1$subexpression$1$string$1", "D", "date"]},
    {"name": "DatePeriod$ebnf$1", "symbols": ["DatePeriod$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": ["DatePeriod$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "DatePeriod$string$1", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"O"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$2$subexpression$1$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DatePeriod$ebnf$2$subexpression$1", "symbols": ["D", "DatePeriod$ebnf$2$subexpression$1$string$1", "D", "date"]},
    {"name": "DatePeriod$ebnf$2", "symbols": ["DatePeriod$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "DatePeriod$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DatePeriod", "symbols": ["DatePeriod$string$1", "D", "date", "DatePeriod$ebnf$2"], "postprocess": functions.joinAndUnpackAll},
    {"name": "date$ebnf$1$subexpression$1", "symbols": ["calendar", "D"]},
    {"name": "date$ebnf$1", "symbols": ["date$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1$subexpression$1", "symbols": ["day", "D"]},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$2$subexpression$1", "symbols": ["date$ebnf$2$subexpression$1$ebnf$1", "month", "D"]},
    {"name": "date$ebnf$2", "symbols": ["date$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date$ebnf$3$subexpression$1", "symbols": ["D", "epoch"]},
    {"name": "date$ebnf$3", "symbols": ["date$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "date$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "date", "symbols": ["date$ebnf$1", "date$ebnf$2", "year", "date$ebnf$3"], "postprocess": functions.joinAndUnpackAll},
    {"name": "dateRange$string$1", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange$string$2", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$1", "D", "date", "D", "dateRange$string$2", "D", "date"], "postprocess": functions.joinAndUnpackAll},
    {"name": "dateRange$string$3", "symbols": [{"literal":"A"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$3", "D", "date"], "postprocess": functions.joinAndUnpackAll},
    {"name": "dateRange$string$4", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRange", "symbols": ["dateRange$string$4", "D", "date"], "postprocess": functions.joinAndUnpackAll},
    {"name": "dateApprox$subexpression$1$string$1", "symbols": [{"literal":"A"}, {"literal":"B"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$1"]},
    {"name": "dateApprox$subexpression$1$string$2", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$2"]},
    {"name": "dateApprox$subexpression$1$string$3", "symbols": [{"literal":"E"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateApprox$subexpression$1", "symbols": ["dateApprox$subexpression$1$string$3"]},
    {"name": "dateApprox", "symbols": ["dateApprox$subexpression$1", "D", "date"], "postprocess": functions.joinAndUnpackAll},
    {"name": "dateRestrict$string$1", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"O"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$1"], "postprocess": id},
    {"name": "dateRestrict$string$2", "symbols": [{"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$2"], "postprocess": id},
    {"name": "dateRestrict$string$3", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$3"], "postprocess": id},
    {"name": "dateRestrict$string$4", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$4"], "postprocess": id},
    {"name": "dateRestrict$string$5", "symbols": [{"literal":"B"}, {"literal":"E"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$5"], "postprocess": id},
    {"name": "dateRestrict$string$6", "symbols": [{"literal":"A"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$6"], "postprocess": id},
    {"name": "dateRestrict$string$7", "symbols": [{"literal":"A"}, {"literal":"B"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$7"], "postprocess": id},
    {"name": "dateRestrict$string$8", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$8"], "postprocess": id},
    {"name": "dateRestrict$string$9", "symbols": [{"literal":"E"}, {"literal":"S"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$9"], "postprocess": id},
    {"name": "dateRestrict$string$10", "symbols": [{"literal":"B"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "dateRestrict", "symbols": ["dateRestrict$string$10"], "postprocess": id},
    {"name": "calendar$string$1", "symbols": [{"literal":"G"}, {"literal":"R"}, {"literal":"E"}, {"literal":"G"}, {"literal":"O"}, {"literal":"R"}, {"literal":"I"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$1"], "postprocess": id},
    {"name": "calendar$string$2", "symbols": [{"literal":"J"}, {"literal":"U"}, {"literal":"L"}, {"literal":"I"}, {"literal":"A"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$2"], "postprocess": id},
    {"name": "calendar$string$3", "symbols": [{"literal":"F"}, {"literal":"R"}, {"literal":"E"}, {"literal":"N"}, {"literal":"C"}, {"literal":"H"}, {"literal":"_"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$3"], "postprocess": id},
    {"name": "calendar$string$4", "symbols": [{"literal":"H"}, {"literal":"E"}, {"literal":"B"}, {"literal":"R"}, {"literal":"E"}, {"literal":"W"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "calendar", "symbols": ["calendar$string$4"], "postprocess": id},
    {"name": "calendar", "symbols": ["extTag"]},
    {"name": "day", "symbols": ["Integer"], "postprocess": id},
    {"name": "year", "symbols": ["Integer"], "postprocess": id},
    {"name": "month", "symbols": ["stdTag"], "postprocess": id},
    {"name": "month", "symbols": ["extTag"], "postprocess": id},
    {"name": "epoch$string$1", "symbols": [{"literal":"B"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "epoch", "symbols": ["epoch$string$1"], "postprocess": id},
    {"name": "epoch", "symbols": ["extTag"], "postprocess": id},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [{"literal":"."}, "fraction"]},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$1$subexpression$1", "symbols": [{"literal":":"}, "second", "Time$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "Time$ebnf$1", "symbols": ["Time$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time$ebnf$2$subexpression$1", "symbols": [{"literal":"Z"}]},
    {"name": "Time$ebnf$2", "symbols": ["Time$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Time$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time", "symbols": ["hour", {"literal":":"}, "minute", "Time$ebnf$1", "Time$ebnf$2"], "postprocess": functions.joinAndUnpackAll},
    {"name": "hour", "symbols": ["digit"], "postprocess": id},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "hour", "symbols": ["hour$subexpression$1", "digit"]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"0"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"1"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"2"}]},
    {"name": "hour$subexpression$2", "symbols": [{"literal":"3"}]},
    {"name": "hour", "symbols": [{"literal":"2"}, "hour$subexpression$2"], "postprocess": functions.joinAndUnpackAll},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "minute$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "minute", "symbols": ["minute$subexpression$1", "digit"], "postprocess": functions.joinAndUnpackAll},
    {"name": "second$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"4"}]},
    {"name": "second$subexpression$1", "symbols": [{"literal":"5"}]},
    {"name": "second", "symbols": ["second$subexpression$1", "digit"], "postprocess": functions.joinAndUnpackAll},
    {"name": "fraction$ebnf$1", "symbols": ["digit"]},
    {"name": "fraction$ebnf$1", "symbols": ["fraction$ebnf$1", "digit"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "fraction", "symbols": ["fraction$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "Age$ebnf$1$subexpression$1", "symbols": ["ageBound", "D"]},
    {"name": "Age$ebnf$1", "symbols": ["Age$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Age$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Age", "symbols": ["Age$ebnf$1", "ageDuration"], "postprocess": functions.joinAndUnpackAll},
    {"name": "ageBound", "symbols": [{"literal":"<"}], "postprocess": id},
    {"name": "ageBound", "symbols": [{"literal":">"}], "postprocess": id},
    {"name": "years", "symbols": ["Integer", {"literal":"y"}], "postprocess": functions.joinAndUnpackAll},
    {"name": "months", "symbols": ["Integer", {"literal":"m"}], "postprocess": functions.joinAndUnpackAll},
    {"name": "weeks", "symbols": ["Integer", {"literal":"w"}], "postprocess": functions.joinAndUnpackAll},
    {"name": "days", "symbols": ["Integer", {"literal":"d"}], "postprocess": functions.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$1$subexpression$1", "symbols": ["D", "months"]},
    {"name": "ageDuration$ebnf$1", "symbols": ["ageDuration$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$2$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$2", "symbols": ["ageDuration$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$3$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$3", "symbols": ["ageDuration$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["years", "ageDuration$ebnf$1", "ageDuration$ebnf$2", "ageDuration$ebnf$3"], "postprocess": functions.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$4$subexpression$1", "symbols": ["D", "weeks"]},
    {"name": "ageDuration$ebnf$4", "symbols": ["ageDuration$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration$ebnf$5$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$5", "symbols": ["ageDuration$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["months", "ageDuration$ebnf$4", "ageDuration$ebnf$5"], "postprocess": functions.joinAndUnpackAll},
    {"name": "ageDuration$ebnf$6$subexpression$1", "symbols": ["D", "days"]},
    {"name": "ageDuration$ebnf$6", "symbols": ["ageDuration$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "ageDuration$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "ageDuration", "symbols": ["weeks", "ageDuration$ebnf$6"], "postprocess": functions.joinAndUnpackAll},
    {"name": "ageDuration", "symbols": ["days"], "postprocess": id},
    {"name": "list$ebnf$1", "symbols": []},
    {"name": "list$ebnf$1$subexpression$1", "symbols": ["listDelim", "listItem"]},
    {"name": "list$ebnf$1", "symbols": ["list$ebnf$1", "list$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "list", "symbols": ["listItem", "list$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "listItem$ebnf$1$subexpression$1", "symbols": ["nocommasp"]},
    {"name": "listItem$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "listItem$ebnf$1$subexpression$1$ebnf$1", "symbols": ["listItem$ebnf$1$subexpression$1$ebnf$1", "nocomma"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listItem$ebnf$1$subexpression$1", "symbols": ["nocommasp", "listItem$ebnf$1$subexpression$1$ebnf$1", "nocommasp"]},
    {"name": "listItem$ebnf$1", "symbols": ["listItem$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "listItem$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "listItem", "symbols": ["listItem$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "listDelim$ebnf$1", "symbols": []},
    {"name": "listDelim$ebnf$1", "symbols": ["listDelim$ebnf$1", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listDelim$ebnf$2", "symbols": []},
    {"name": "listDelim$ebnf$2", "symbols": ["listDelim$ebnf$2", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "listDelim", "symbols": ["listDelim$ebnf$1", {"literal":","}, "listDelim$ebnf$2"], "postprocess": functions.joinAndUnpackAll},
    {"name": "nocomma", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x2C]/], "postprocess": id},
    {"name": "nocommasp", "symbols": [/[^\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F\x2C\x1E-\x20]/], "postprocess": id},
    {"name": "List_Text", "symbols": ["list"], "postprocess": id},
    {"name": "List_Enum$ebnf$1", "symbols": []},
    {"name": "List_Enum$ebnf$1$subexpression$1", "symbols": ["listDelim", "Enum"]},
    {"name": "List_Enum$ebnf$1", "symbols": ["List_Enum$ebnf$1", "List_Enum$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "List_Enum", "symbols": ["Enum", "List_Enum$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "PersonalName", "symbols": ["nameStr"]},
    {"name": "PersonalName$ebnf$1", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$2", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName$ebnf$3", "symbols": ["nameStr"], "postprocess": id},
    {"name": "PersonalName$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "PersonalName", "symbols": ["PersonalName$ebnf$1", {"literal":"/"}, "PersonalName$ebnf$2", {"literal":"/"}, "PersonalName$ebnf$3"], "postprocess": functions.joinAndUnpackAll},
    {"name": "nameChar", "symbols": [/[^\x00-\x19\x2F]/], "postprocess": id},
    {"name": "nameStr$ebnf$1", "symbols": ["nameChar"]},
    {"name": "nameStr$ebnf$1", "symbols": ["nameStr$ebnf$1", "nameChar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "nameStr", "symbols": ["nameStr$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "LangTag$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "script"]},
    {"name": "LangTag$ebnf$1", "symbols": ["LangTag$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "region"]},
    {"name": "LangTag$ebnf$2", "symbols": ["LangTag$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag$ebnf$3", "symbols": []},
    {"name": "LangTag$ebnf$3$subexpression$1", "symbols": [{"literal":"-"}, "variant"]},
    {"name": "LangTag$ebnf$3", "symbols": ["LangTag$ebnf$3", "LangTag$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "LangTag$ebnf$4", "symbols": []},
    {"name": "LangTag$ebnf$4$subexpression$1", "symbols": [{"literal":"-"}, "extension"]},
    {"name": "LangTag$ebnf$4", "symbols": ["LangTag$ebnf$4", "LangTag$ebnf$4$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "LangTag$ebnf$5$subexpression$1", "symbols": [{"literal":"-"}, "privateuse"]},
    {"name": "LangTag$ebnf$5", "symbols": ["LangTag$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "LangTag$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "LangTag", "symbols": ["language", "LangTag$ebnf$1", "LangTag$ebnf$2", "LangTag$ebnf$3", "LangTag$ebnf$4", "LangTag$ebnf$5"], "postprocess": functions.joinAndUnpackAll},
    {"name": "language$ebnf$1", "symbols": ["alpha"], "postprocess": id},
    {"name": "language$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "extlang"]},
    {"name": "language$ebnf$2", "symbols": ["language$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language", "symbols": ["alpha", "alpha", "language$ebnf$1", "language$ebnf$2"], "postprocess": functions.joinAndUnpackAll},
    {"name": "language", "symbols": ["alpha", "alpha", "alpha", "alpha"], "postprocess": functions.joinAndUnpackAll},
    {"name": "language$ebnf$3$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$3", "symbols": ["language$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$4$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$4", "symbols": ["language$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language$ebnf$5$subexpression$1", "symbols": ["alpha"]},
    {"name": "language$ebnf$5", "symbols": ["language$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "language$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "language", "symbols": ["alpha", "alpha", "alpha", "alpha", "alpha", "language$ebnf$3", "language$ebnf$4", "language$ebnf$5"], "postprocess": functions.joinAndUnpackAll},
    {"name": "extlang$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$1", "symbols": ["extlang$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang$ebnf$2$subexpression$1", "symbols": [{"literal":"-"}, "alpha", "alpha", "alpha"]},
    {"name": "extlang$ebnf$2", "symbols": ["extlang$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extlang$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extlang", "symbols": ["alpha", "alpha", "alpha", "extlang$ebnf$1", "extlang$ebnf$2"], "postprocess": functions.joinAndUnpackAll},
    {"name": "script", "symbols": ["alpha", "alpha", "alpha", "alpha"], "postprocess": functions.joinAndUnpackAll},
    {"name": "region", "symbols": ["alpha", "alpha"], "postprocess": functions.joinAndUnpackAll},
    {"name": "region", "symbols": ["digit", "digit", "digit"], "postprocess": functions.joinAndUnpackAll},
    {"name": "variant", "symbols": ["digit", "alphanum", "alphanum", "alphanum"], "postprocess": functions.joinAndUnpackAll},
    {"name": "variant$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$1", "symbols": ["variant$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$2", "symbols": ["variant$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "variant$ebnf$3", "symbols": ["variant$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "variant$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "variant", "symbols": ["alphanum", "alphanum", "alphanum", "alphanum", "alphanum", "variant$ebnf$1", "variant$ebnf$2", "variant$ebnf$3"], "postprocess": functions.joinAndUnpackAll},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$1$ebnf$1", "extension$ebnf$1$subexpression$1$ebnf$2", "extension$ebnf$1$subexpression$1$ebnf$3", "extension$ebnf$1$subexpression$1$ebnf$4", "extension$ebnf$1$subexpression$1$ebnf$5", "extension$ebnf$1$subexpression$1$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$1"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": ["extension$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "extension$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "extension$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "alphanum", "extension$ebnf$1$subexpression$2$ebnf$1", "extension$ebnf$1$subexpression$2$ebnf$2", "extension$ebnf$1$subexpression$2$ebnf$3", "extension$ebnf$1$subexpression$2$ebnf$4", "extension$ebnf$1$subexpression$2$ebnf$5", "extension$ebnf$1$subexpression$2$ebnf$6"]},
    {"name": "extension$ebnf$1", "symbols": ["extension$ebnf$1", "extension$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "extension", "symbols": ["singleton", "extension$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "singleton", "symbols": ["digit"], "postprocess": id},
    {"name": "singleton", "symbols": [/[\x41-\x57\x59-\x5A\x61-\x77\x79-\x7A]/], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$1$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$1$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$1$ebnf$1", "privateuse$ebnf$1$subexpression$1$ebnf$2", "privateuse$ebnf$1$subexpression$1$ebnf$3", "privateuse$ebnf$1$subexpression$1$ebnf$4", "privateuse$ebnf$1$subexpression$1$ebnf$5", "privateuse$ebnf$1$subexpression$1$ebnf$6", "privateuse$ebnf$1$subexpression$1$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$1"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$6$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1", "symbols": ["alphanum"]},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": ["privateuse$ebnf$1$subexpression$2$ebnf$7$subexpression$1"], "postprocess": id},
    {"name": "privateuse$ebnf$1$subexpression$2$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "privateuse$ebnf$1$subexpression$2", "symbols": [{"literal":"-"}, "alphanum", "privateuse$ebnf$1$subexpression$2$ebnf$1", "privateuse$ebnf$1$subexpression$2$ebnf$2", "privateuse$ebnf$1$subexpression$2$ebnf$3", "privateuse$ebnf$1$subexpression$2$ebnf$4", "privateuse$ebnf$1$subexpression$2$ebnf$5", "privateuse$ebnf$1$subexpression$2$ebnf$6", "privateuse$ebnf$1$subexpression$2$ebnf$7"]},
    {"name": "privateuse$ebnf$1", "symbols": ["privateuse$ebnf$1", "privateuse$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "privateuse", "symbols": [{"literal":"x"}, "privateuse$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "alpha", "symbols": [/[a-zA-z]/], "postprocess": id},
    {"name": "alphanum", "symbols": ["alpha"], "postprocess": id},
    {"name": "alphanum", "symbols": ["digit"], "postprocess": id},
    {"name": "irregular$string$1", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"-"}, {"literal":"G"}, {"literal":"B"}, {"literal":"-"}, {"literal":"o"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$1"], "postprocess": id},
    {"name": "irregular$string$2", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"a"}, {"literal":"m"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$2"], "postprocess": id},
    {"name": "irregular$string$3", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"b"}, {"literal":"n"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$3"], "postprocess": id},
    {"name": "irregular$string$4", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$4"], "postprocess": id},
    {"name": "irregular$string$5", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"e"}, {"literal":"n"}, {"literal":"o"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$5"], "postprocess": id},
    {"name": "irregular$string$6", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"h"}, {"literal":"a"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$6"], "postprocess": id},
    {"name": "irregular$string$7", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"k"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$7"], "postprocess": id},
    {"name": "irregular$string$8", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"l"}, {"literal":"u"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$8"], "postprocess": id},
    {"name": "irregular$string$9", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$9"], "postprocess": id},
    {"name": "irregular$string$10", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"n"}, {"literal":"a"}, {"literal":"v"}, {"literal":"a"}, {"literal":"j"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$10"], "postprocess": id},
    {"name": "irregular$string$11", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"p"}, {"literal":"w"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$11"], "postprocess": id},
    {"name": "irregular$string$12", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"a"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$12"], "postprocess": id},
    {"name": "irregular$string$13", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$13"], "postprocess": id},
    {"name": "irregular$string$14", "symbols": [{"literal":"i"}, {"literal":"-"}, {"literal":"t"}, {"literal":"s"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$14"], "postprocess": id},
    {"name": "irregular$string$15", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"B"}, {"literal":"E"}, {"literal":"-"}, {"literal":"F"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$15"], "postprocess": id},
    {"name": "irregular$string$16", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"B"}, {"literal":"E"}, {"literal":"-"}, {"literal":"N"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$16"], "postprocess": id},
    {"name": "irregular$string$17", "symbols": [{"literal":"s"}, {"literal":"g"}, {"literal":"n"}, {"literal":"-"}, {"literal":"C"}, {"literal":"H"}, {"literal":"-"}, {"literal":"D"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "irregular", "symbols": ["irregular$string$17"], "postprocess": id},
    {"name": "regular$string$1", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"-"}, {"literal":"l"}, {"literal":"o"}, {"literal":"j"}, {"literal":"b"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$1"], "postprocess": id},
    {"name": "regular$string$2", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"l"}, {"literal":"-"}, {"literal":"g"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$2"], "postprocess": id},
    {"name": "regular$string$3", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"-"}, {"literal":"b"}, {"literal":"o"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$3"], "postprocess": id},
    {"name": "regular$string$4", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"-"}, {"literal":"n"}, {"literal":"y"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$4"], "postprocess": id},
    {"name": "regular$string$5", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"g"}, {"literal":"u"}, {"literal":"o"}, {"literal":"y"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$5"], "postprocess": id},
    {"name": "regular$string$6", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"h"}, {"literal":"a"}, {"literal":"k"}, {"literal":"k"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$6"], "postprocess": id},
    {"name": "regular$string$7", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$7"], "postprocess": id},
    {"name": "regular$string$8", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"-"}, {"literal":"n"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$8"], "postprocess": id},
    {"name": "regular$string$9", "symbols": [{"literal":"z"}, {"literal":"h"}, {"literal":"-"}, {"literal":"x"}, {"literal":"i"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "regular", "symbols": ["regular$string$9"], "postprocess": id},
    {"name": "grandfathered", "symbols": ["irregular"], "postprocess": id},
    {"name": "grandfathered", "symbols": ["regular"], "postprocess": id},
    {"name": "MediaType$ebnf$1", "symbols": []},
    {"name": "MediaType$ebnf$1$subexpression$1", "symbols": [{"literal":";"}, "mt_parameter"]},
    {"name": "MediaType$ebnf$1", "symbols": ["MediaType$ebnf$1", "MediaType$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "MediaType", "symbols": ["mt_type", {"literal":"/"}, "mt_subtype", "MediaType$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "mt_type", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_subtype", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_parameter", "symbols": ["mt_attribute", {"literal":"="}, "mt_value"], "postprocess": functions.joinAndUnpackAll},
    {"name": "mt_token$ebnf$1$subexpression$1", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1$subexpression$1"]},
    {"name": "mt_token$ebnf$1$subexpression$2", "symbols": ["mt_char"]},
    {"name": "mt_token$ebnf$1", "symbols": ["mt_token$ebnf$1", "mt_token$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_token", "symbols": ["mt_token$ebnf$1"], "postprocess": functions.joinAndUnpackAll},
    {"name": "mt_attribute", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_value", "symbols": ["mt_token"], "postprocess": id},
    {"name": "mt_value", "symbols": ["mt_qstring"], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x20-\x21]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x23-\x27]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x2A-\x2B]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x2D-\x2E]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x30-\x39]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x41-\x5A]/], "postprocess": id},
    {"name": "mt_char", "symbols": [/[\x5E-\x7E]/], "postprocess": id},
    {"name": "mt_qstring$ebnf$1", "symbols": []},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qtext"]},
    {"name": "mt_qstring$ebnf$1$subexpression$1", "symbols": ["mt_qpair"]},
    {"name": "mt_qstring$ebnf$1", "symbols": ["mt_qstring$ebnf$1", "mt_qstring$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "mt_qstring", "symbols": [/[\x22]/, "mt_qstring$ebnf$1", /[\x22]/], "postprocess": functions.joinAndUnpackAll},
    {"name": "mt_qtext", "symbols": [/[\x09-\x0A]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x20-\x21]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x23-\x5B]/], "postprocess": id},
    {"name": "mt_qtext", "symbols": [/[\x5D-\x7E]/], "postprocess": id},
    {"name": "mt_qpair", "symbols": [{"literal":"\\"}, /[\x09-7E]/], "postprocess": functions.joinAndUnpackAll},
    {"name": "Special", "symbols": ["Text"], "postprocess": id},
    {"name": "NullOrY$ebnf$1", "symbols": [{"literal":"Y"}], "postprocess": id},
    {"name": "NullOrY$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "NullOrY", "symbols": ["NullOrY$ebnf$1"], "postprocess": id},
    {"name": "AGE", "symbols": ["Level", "D", {"literal":"AGE"}, "D", "Age", "EOL"], "postprocess": (data) => functions.createStructure({line: data, type: lineTypes.NO_XREF})},
    {"name": "AGE", "symbols": ["AGE", "PHRASE", "EOL"], "postprocess": (d) => functions.addSubstructure({superstruct: d[0], substructs: d[1], checkCardinalityOf: ["PHRASE"]})},
    {"name": "PHRASE", "symbols": ["Level", "D", {"literal":"PHRASE"}, "D", "Text", "EOL"], "postprocess": (d) => functions.createStructure({line: d, type: lineTypes.NO_XREF})},
    {"name": "TYPE", "symbols": ["Level", "D", {"literal":"TYPE"}, "D", "Text", "EOL"], "postprocess": (d) => functions.createStructure({line: d, type: lineTypes.NO_XREF})},
    {"name": "TIME", "symbols": ["Level", "D", {"literal":"TIME"}, "D", "Time", "EOL"]},
    {"name": "DATE", "symbols": ["Level", "D", {"literal":"DATE"}, "D", "DateValue", "EOL"]},
    {"name": "DATE$ebnf$1", "symbols": ["TIME"], "postprocess": id},
    {"name": "DATE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE$ebnf$2", "symbols": ["PHRASE"], "postprocess": id},
    {"name": "DATE$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE", "symbols": ["DATE", "DATE$ebnf$1", "DATE$ebnf$2", "EOL"]},
    {"name": "DATE$ebnf$3", "symbols": ["PHRASE"], "postprocess": id},
    {"name": "DATE$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE$ebnf$4", "symbols": ["TIME"], "postprocess": id},
    {"name": "DATE$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DATE", "symbols": ["DATE", "DATE$ebnf$3", "DATE$ebnf$4"]},
    {"name": "DATE_EXACT", "symbols": ["Level", "D", {"literal":"DATE"}, "D", "DateExact", "EOL"]},
    {"name": "DATE_EXACT", "symbols": ["DATE", "TIME", "EOL"]},
    {"name": "DATEPERIOD", "symbols": ["Level", "D", {"literal":"DATE"}, "D", "DatePeriod", "EOL"]},
    {"name": "DATEPERIOD", "symbols": ["DATEPERIOD", "PHRASE", "EOL"]},
    {"name": "TEXT", "symbols": ["Level", "D", {"literal":"TEXT"}, "D", "Text", "EOL"]},
    {"name": "TEXT", "symbols": ["TEXT", "Level", "D", {"literal":"MIME"}, "MediaType", "EOL"]},
    {"name": "TEXT", "symbols": ["TEXT", "Level", "D", {"literal":"LANG"}, "language", "EOL"]},
    {"name": "QUAY$subexpression$1", "symbols": [{"literal":"0"}]},
    {"name": "QUAY$subexpression$1", "symbols": [{"literal":"1"}]},
    {"name": "QUAY$subexpression$1", "symbols": [{"literal":"2"}]},
    {"name": "QUAY$subexpression$1", "symbols": [{"literal":"3"}]},
    {"name": "QUAY", "symbols": ["Level", "D", {"literal":"QUAY"}, "D", "QUAY$subexpression$1"]},
    {"name": "CROP", "symbols": ["Level", "D", {"literal":"CROP"}, "D"]},
    {"name": "CROP", "symbols": ["CROP", "Level", "D", {"literal":"TOP"}, "D", "Integer", "EOL"]},
    {"name": "CROP", "symbols": ["CROP", "Level", "D", {"literal":"LEFT"}, "D", "Integer", "EOL"]},
    {"name": "CROP", "symbols": ["CROP", "Level", "D", {"literal":"HEIGHT"}, "D", "Integer", "EOL"]},
    {"name": "CROP", "symbols": ["CROP", "Level", "D", {"literal":"WIDTH"}, "D", "Integer", "EOL"]},
    {"name": "EVENT_DETAIL", "symbols": ["DATE"]},
    {"name": "NAME_PIECES", "symbols": ["Level", "D", "NAME_PIECES_ENUM", "D", "Text", "EOL"]},
    {"name": "NON_EVENT_STRUCTURE", "symbols": ["Level", "D", {"literal":"NO"}, "D", "EVENTS", "EOL"]},
    {"name": "NON_EVENT_STRUCTURE", "symbols": ["NON_EVENT_STRUCTURE", "DATEPERIOD", "EOL"]},
    {"name": "NON_EVENT_STRUCTURE", "symbols": ["NON_EVENT_STRUCTURE", "NOTE_STRUCTURE", "EOL"]},
    {"name": "NON_EVENT_STRUCTURE", "symbols": ["NON_EVENT_STRUCTURE", "SOURCE_CITATION", "EOL"]},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["Level", "D", {"literal":"NOTE"}, "D", "Text", "EOL"]},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["NOTE_STRUCTURE", "Level", "D", {"literal":"MIME"}, "D", "MediaType", "EOL"]},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["NOTE_STRUCTURE", "Level", "D", {"literal":"LANG"}, "D", "language", "EOL"]},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["NOTE_STRUCTURE", "NOTE_TRAN", "EOL"]},
    {"name": "NOTE_STRUCTURE$subexpression$1", "symbols": ["NOTE_STRUCTURE", "SOURCE_CITATION"]},
    {"name": "NOTE_STRUCTURE", "symbols": ["NOTE_STRUCTURE$subexpression$1"]},
    {"name": "NOTE_STRUCTURE", "symbols": ["Level", "D", {"literal":"SNOTE"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "EOL"]},
    {"name": "NOTE_TRAN", "symbols": ["Level", "D", {"literal":"TRAN"}, "D", "Text", "EOL"]},
    {"name": "NOTE_TRAN", "symbols": ["NOTE_TRAN", "Level", "D", {"literal":"MIME"}, "D", "MediaType", "EOL"]},
    {"name": "NOTE_TRAN", "symbols": ["NOTE_TRAN", "Level", "D", {"literal":"LANG"}, "D", "language", "EOL"]},
    {"name": "SOURCE_CITATION", "symbols": ["Level", "D", {"literal":"SOUR"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "EOL"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "Level", "D", {"literal":"PAGE"}, "D", "Text", "EOL"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "SOUR_DATA", "EOL"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "SOUR_EVEN", "EOL"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "QUAY", "EOL"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "MULTIMEDIA_LINK", "EOL"]},
    {"name": "SOURCE_CITATION", "symbols": ["SOURCE_CITATION", "NOTE_STRUCTURE", "EOL"]},
    {"name": "SOUR_DATA", "symbols": ["Level", "D", {"literal":"DATA"}, "EOL"]},
    {"name": "SOUR_DATA", "symbols": ["SOUR_DATA", "DATE", "EOL"]},
    {"name": "SOUR_DATA", "symbols": ["SOUR_DATA", "TEXT", "EOL"]},
    {"name": "SOUR_EVEN$subexpression$1", "symbols": ["ATTRIBUTES"]},
    {"name": "SOUR_EVEN$subexpression$1", "symbols": ["EVENTS"]},
    {"name": "SOUR_EVEN", "symbols": ["Level", "D", {"literal":"EVEN"}, "SOUR_EVEN$subexpression$1", "EOL"]},
    {"name": "SOUR_EVEN", "symbols": ["SOUR_EVEN", "PHRASE", "EOL"]},
    {"name": "SOUR_EVEN", "symbols": ["SOUR_EVEN", "ROLE", "EOL"]},
    {"name": "SOUR_EVEN", "symbols": ["SOUR_EVEN", "ROLE", "EOL", "PHRASE", "EOL"]},
    {"name": "MULTIMEDIA_LINK", "symbols": ["Level", "D", {"literal":"OBJE"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "EOL"]},
    {"name": "MULTIMEDIA_LINK", "symbols": ["MULTIMEDIA_LINK", "CROP", "EOL"]},
    {"name": "MULTIMEDIA_LINK", "symbols": ["MULTIMEDIA_LINK", "Level", "D", {"literal":"TITL"}, "D", "Text", "EOL"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["DATE", "EOL"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["Level", "D", {"literal":"TEMP"}, "D", "Text", "EOL"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["PLACE_STRUCTURE", "EOL"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["Level", "D", {"literal":"STAT"}, "D", "FAMC_STAT_ENUM", "DATE_EXACT", "EOL"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["NOTE_STRUCTURE", "EOL"]},
    {"name": "LDS_ORDINANCE_DETAIL", "symbols": ["SOURCE_CITATION", "EOL"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["Level", "D", {"literal":"PLAC"}, "D", "List_Text", "EOL"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "Level", "D", {"literal":"FORM"}, "D", "List_Text", "EOL"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "Level", "D", {"literal":"LANG"}, "D", "language", "EOL"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "PLAC_TRAN", "EOL"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "MAP", "EOL"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "EXID", "EOL"]},
    {"name": "PLACE_STRUCTURE", "symbols": ["PLACE_STRUCTURE", "NOTE_STRUCTURE", "EOL"]},
    {"name": "MAP", "symbols": ["Level", "D", {"literal":"MAP"}, "EOL"]},
    {"name": "MAP", "symbols": ["MAP", "Level", "D", {"literal":"LATI"}, "D", "Special", "EOL"]},
    {"name": "MAP", "symbols": ["MAP", "Level", "D", {"literal":"LONG"}, "D", "Special", "EOL"]},
    {"name": "EXID", "symbols": ["Level", "D", {"literal":"EXID"}, "D", "Special", "EOL"]},
    {"name": "EXID", "symbols": ["EXID", "Level", "D", {"literal":"TYPE"}, "D", "Special", "EOL"]},
    {"name": "PLAC_TRAN", "symbols": ["Level", "D", {"literal":"TRAN"}, "D", "Text", "EOL"]},
    {"name": "PLAC_TRAN", "symbols": ["PLAC_TRAN", "Level", "D", {"literal":"LANG"}, "D", "language", "EOL"]},
    {"name": "FAMC_STAT", "symbols": ["Level", "D", {"literal":"STAT"}, "FAMC_STAT_ENUM", "EOL"]},
    {"name": "PEDI", "symbols": ["Level", "D", {"literal":"PEDI"}, "D", "PEDI_ENUM", "EOL"]},
    {"name": "PEDI", "symbols": ["PEDI", "PHRASE", "EOL"]},
    {"name": "FAMS", "symbols": ["Level", "D", {"literal":"FAMS"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "EOL"]},
    {"name": "FAMS", "symbols": ["FAMS", "NOTE_STRUCTURE", "EOL"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["Level", "D", {"literal":"ASSO"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "EOL"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["ASSOCIATION_STRUCTURE", "PHRASE", "EOL"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["ASSOCIATION_STRUCTURE", "ROLE", "EOL"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["ASSOCIATION_STRUCTURE", "NOTE_STRUCTURE", "EOL"]},
    {"name": "ASSOCIATION_STRUCTURE", "symbols": ["ASSOCIATION_STRUCTURE", "SOURCE_CITATION", "EOL"]},
    {"name": "REFN", "symbols": ["Level", "D", {"literal":"REFN"}, "D", "Special", "EOL"]},
    {"name": "REFN", "symbols": ["REFN", "Level", "D", {"literal":"TYPE"}, "D", "Text", "EOL"]},
    {"name": "UID", "symbols": ["Level", "D", {"literal":"UID"}, "D", "Special", "EOL"]},
    {"name": "IDENTIFIER_STRUCTURE$subexpression$1", "symbols": ["REFN"]},
    {"name": "IDENTIFIER_STRUCTURE$subexpression$1", "symbols": ["UID"]},
    {"name": "IDENTIFIER_STRUCTURE$subexpression$1", "symbols": ["EXID"]},
    {"name": "IDENTIFIER_STRUCTURE", "symbols": ["IDENTIFIER_STRUCTURE$subexpression$1", "EOL"]},
    {"name": "CHANGE_DATE", "symbols": ["Level", "D", {"literal":"CHAN"}, "EOL"]},
    {"name": "CHANGE_DATE", "symbols": ["CHANGE_DATE", "DATE_EXACT", "EOL"]},
    {"name": "CHANGE_DATE", "symbols": ["CHANGE_DATE", "NOTE_STRUCTURE", "EOL"]},
    {"name": "CREATION_DATE", "symbols": ["Level", "D", {"literal":"CREA"}, "EOL"]},
    {"name": "CREATION_DATE", "symbols": ["CREATION_DATE", "DATE_EXACT", "EOL"]},
    {"name": "input$ebnf$1", "symbols": []},
    {"name": "input$ebnf$1", "symbols": ["input$ebnf$1", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input", "symbols": ["INDI", "input$ebnf$1"]},
    {"name": "input$ebnf$2", "symbols": []},
    {"name": "input$ebnf$2", "symbols": ["input$ebnf$2", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$3", "symbols": []},
    {"name": "input$ebnf$3$subexpression$1$ebnf$1", "symbols": []},
    {"name": "input$ebnf$3$subexpression$1$ebnf$1", "symbols": ["input$ebnf$3$subexpression$1$ebnf$1", "D"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input$ebnf$3$subexpression$1", "symbols": ["newLine", "structure", "input$ebnf$3$subexpression$1$ebnf$1"]},
    {"name": "input$ebnf$3", "symbols": ["input$ebnf$3", "input$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "input", "symbols": ["INDI", "input$ebnf$2", "input$ebnf$3"]},
    {"name": "INDI", "symbols": ["Level", "D", (lexer.has("Xref") ? {type: "Xref"} : Xref), "D", {"literal":"INDI"}]},
    {"name": "structure", "symbols": ["RESN"]},
    {"name": "structure", "symbols": ["PERSONAL_NAME_STRUCTURE"]},
    {"name": "structure", "symbols": ["SEX"]},
    {"name": "structure", "symbols": ["INDIVIDUAL_ATTRIBUTE_STRUCTURE"]},
    {"name": "structure", "symbols": ["INDIVIDUAL_EVENT_STRUCTURE"]},
    {"name": "structure", "symbols": ["NON_EVENT_STRUCTURE"]},
    {"name": "structure", "symbols": ["LDS_INDIVIDUAL_ORDINANCE"]},
    {"name": "structure", "symbols": ["INDI_FAMC"]},
    {"name": "structure", "symbols": ["FAMS"]},
    {"name": "structure", "symbols": ["SUBM"]},
    {"name": "structure", "symbols": ["ASSOCIATION_STRUCTURE"]},
    {"name": "structure", "symbols": ["ALIA"]},
    {"name": "structure", "symbols": ["ANCI"]},
    {"name": "structure", "symbols": ["DESI"]},
    {"name": "structure", "symbols": ["IDENTIFIER_STRUCTURE"]},
    {"name": "structure", "symbols": ["NOTE_STRUCTURE"]},
    {"name": "structure", "symbols": ["SOURCE_CITATION"]},
    {"name": "structure", "symbols": ["MULTIMEDIA_LINK"]},
    {"name": "structure", "symbols": ["CHANGE_DATE"]},
    {"name": "structure", "symbols": ["CREATION_DATE"]},
    {"name": "RESN", "symbols": ["Level", "D", {"literal":"RESN"}, "RESN_ENUM"]},
    {"name": "PERSONAL_NAME_STRUCTURE", "symbols": ["Level", "D", {"literal":"NAME"}, "D", "PersonalName"]},
    {"name": "PERSONAL_NAME_STRUCTURE", "symbols": ["PERSONAL_NAME_STRUCTURE", "newLine", "TYPE"]},
    {"name": "PERSONAL_NAME_STRUCTURE", "symbols": ["PERSONAL_NAME_STRUCTURE", "newLine", "TYPE", "newLine", "PHRASE"]},
    {"name": "PERSONAL_NAME_STRUCTURE", "symbols": ["PERSONAL_NAME_STRUCTURE", "newLine", "NAME_PIECES"]},
    {"name": "PERSONAL_NAME_STRUCTURE", "symbols": ["PERSONAL_NAME_STRUCTURE", "newLine", "NOTE_STRUCTURE"]},
    {"name": "PERSONAL_NAME_STRUCTURE", "symbols": ["PERSONAL_NAME_STRUCTURE", "newLine", {"literal":"TRAN"}, "PersonalName", "newLine", "Level", "D", {"literal":"LANG"}, "D", "language"]},
    {"name": "PERSONAL_NAME_STRUCTURE", "symbols": ["PERSONAL_NAME_STRUCTURE", "newLine", {"literal":"TRAN"}, "PersonalName", "newLine", "Level", "D", {"literal":"LANG"}, "D", "language", "newLine", "NAME_PIECES"]},
    {"name": "SEX", "symbols": ["Level", "D", {"literal":"SEX"}, "D", "SEX_ENUM"]},
    {"name": "INDIVIDUAL_EVENT_STRUCTURE", "symbols": ["INDIVIDUAL_EVENT"]},
    {"name": "INDIVIDUAL_EVENT_STRUCTURE", "symbols": ["INDIVIDUAL_EVENT_BIRT_CHR"]},
    {"name": "INDIVIDUAL_EVENT_STRUCTURE", "symbols": ["INDIVIDUAL_EVENT_ADOP"]},
    {"name": "LDS_INDIVIDUAL_ORDINANCE$subexpression$1", "symbols": [{"literal":"BAPL"}]},
    {"name": "LDS_INDIVIDUAL_ORDINANCE$subexpression$1", "symbols": [{"literal":"CONL"}]},
    {"name": "LDS_INDIVIDUAL_ORDINANCE$subexpression$1", "symbols": [{"literal":"ENDL"}]},
    {"name": "LDS_INDIVIDUAL_ORDINANCE$subexpression$1", "symbols": [{"literal":"INIL"}]},
    {"name": "LDS_INDIVIDUAL_ORDINANCE$subexpression$1", "symbols": [{"literal":"SLGC"}]},
    {"name": "LDS_INDIVIDUAL_ORDINANCE", "symbols": ["Level", "D", "LDS_INDIVIDUAL_ORDINANCE$subexpression$1"]},
    {"name": "LDS_INDIVIDUAL_ORDINANCE", "symbols": ["LDS_INDIVIDUAL_ORDINANCE", "newLine", "LDS_ORDINANCE_DETAIL"]},
    {"name": "LDS_INDIVIDUAL_ORDINANCE", "symbols": ["Level", "D", {"literal":"SLGC"}, "newLine", "Level", "D", {"literal":"FAMC"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref)]},
    {"name": "INDI_FAMC", "symbols": ["Level", "D", {"literal":"FAMC"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref)]},
    {"name": "INDI_FAMC", "symbols": ["INDI_FAMC", "newLine", "PEDI"]},
    {"name": "INDI_FAMC", "symbols": ["INDI_FAMC", "newLine", "FAMC_STAT"]},
    {"name": "INDI_FAMC", "symbols": ["INDI_FAMC", "newLine", "NOTE_STRUCTURE"]},
    {"name": "SUBM", "symbols": ["Level", "D", {"literal":"SUBM"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref)]},
    {"name": "ALIA", "symbols": ["Level", "D", {"literal":"ALIA"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref)]},
    {"name": "ALIA", "symbols": ["ALIA", "newLine", "PHRASE"]},
    {"name": "ANCI", "symbols": ["Level", "D", {"literal":"ANCI"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref)]},
    {"name": "DESI", "symbols": ["Level", "D", {"literal":"DESI"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref)]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE$subexpression$1", "symbols": [{"literal":"CAST"}]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE$subexpression$1", "symbols": [{"literal":"DSCR"}]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE$subexpression$1", "symbols": [{"literal":"EDUC"}]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE", "symbols": ["Level", "D", "INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE$subexpression$1", "D", "Text"]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE", "symbols": ["INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE", "newLine", "Level", "D", {"literal":"TYPE"}, "D", "Text"]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE", "symbols": ["INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE", "newLine", "INDIVIDUAL_EVENT_DETAIL"]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE", "symbols": ["INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE"]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE", "symbols": ["INDIVIDUAL_ATTRIBUTE_STRUCTURE", "newLine", "INDIVIDUAL_ATTRIBUTE_STRUCTURE_NODE"]},
    {"name": "INDIVIDUAL_ATTRIBUTE_STRUCTURE", "symbols": ["INDIVIDUAL_ATTRIBUTE_STRUCTURE", "newLine", "Level", "D", {"literal":"IDNO"}, "D", "Special"]},
    {"name": "INDIVIDUAL_EVENT$ebnf$1", "symbols": ["D"], "postprocess": id},
    {"name": "INDIVIDUAL_EVENT$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "INDIVIDUAL_EVENT", "symbols": ["Level", "D", "INDIVIDUAL_EVENTS", "INDIVIDUAL_EVENT$ebnf$1", "NullOrY"]},
    {"name": "INDIVIDUAL_EVENT", "symbols": ["INDIVIDUAL_EVENT", "newLine", "Level", "D", {"literal":"TYPE"}, "D", "Text"]},
    {"name": "INDIVIDUAL_EVENT", "symbols": ["INDIVIDUAL_EVENT", "newLine", "INDIVIDUAL_EVENT_DETAIL"]},
    {"name": "INDIVIDUAL_EVENT_DETAIL", "symbols": ["EVENT_DETAIL"]},
    {"name": "INDIVIDUAL_EVENT_DETAIL", "symbols": ["AGE"]},
    {"name": "INDIVIDUAL_EVENT_BIRT_CHR", "symbols": ["INDIVIDUAL_EVENT", "newLine", "Level", "D", {"literal":"FAMC"}, "D", (lexer.has("Xref") ? {type: "Xref"} : Xref)]},
    {"name": "INDIVIDUAL_EVENT_ADOP", "symbols": ["INDIVIDUAL_EVENT_BIRT_CHR"]},
    {"name": "INDIVIDUAL_EVENT_ADOP", "symbols": ["INDIVIDUAL_EVENT_ADOP", "newLine", "Level", "D", {"literal":"ADOP"}, "D", "ADOP_ENUM"]},
    {"name": "INDIVIDUAL_EVENT_ADOP", "symbols": ["INDIVIDUAL_EVENT_ADOP", "newLine", "Level", "D", {"literal":"ADOP"}, "D", "ADOP_ENUM", "newLine", "PHRASE"]}
]
  , ParserStart: "input"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
